### ISSUE TITLE
Address PR comments for #981

### ISSUE THREAD

**Issue by W3stside** [gnosis/cowswap#1006]
Address comments in #981 

- [x] Button (approve) stuck to other https://github.com/gnosis/cowswap/pull/981#pullrequestreview-710937349
- [x] Change display info in ConfirmationModal: https://github.com/gnosis/cowswap/pull/981#issuecomment-883288623
- [x] Remove "Fee" amount from second tooltip on swap page at bottom
- [x] add currency symbols to fee breakdown // tooltips for easier formatting
- [ ] Price breakdown font seems different? could be size thing, just check <-- @alfetopito it's a font size thing. Other fonts are 13px this is 14px

**Comment by alfetopito** [comment]
> Price breakdown font seems different? could be size thing, just check <-- @alfetopito it's a font size thing. Other fonts are 13px this is 14px

I'm good then, closing issue
