### ISSUE TITLE
[v.0.17.0] The app is crashed in xDAI when change wxDAI to xDAI token in the To field

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1010]
Related to #924

1. Connect a wallet in xDAI
2. select a token in the From field, specify an amount
3. Select wxDAI token in the To field
4. wait till prices are calculated
5. change token to xDAI in the To field

**AR**: the app is crashed
https://drive.google.com/file/d/1XPQmypLxnrAxc4VMeUK3X2bf6zc2DhhU/view

**ER**: the token is change, prices are recalculated

**Comment by alfetopito** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1011
