### ISSUE TITLE
Change tooltips to be clearer

### ISSUE THREAD

**Issue by W3stside** [gnosis/cowswap#1012]
Based on comment written by @biocom (he edited my message im not smart enough to propose such good changes)

> @biocom fees are denoted all in the same currency so imho it's not necessary to add units

While technically that is the case (fees denoted in the same currency) it's easy to lose context as to what 'the same' currency relates to. I'd say for clarity we should add it. Especially given the tooltip has the primary purpose of making the breakdown clearer and not more abstract.

E.g. comparing a tooltip proposal from a while back:

<img width="350" alt="Screen Shot 2021-07-22 at 09 57 02" src="https://user-images.githubusercontent.com/31534717/126606679-80e3c007-5cbd-4987-a8f6-b64633d24419.png">vs<img width="350" alt="Screen Shot 2021-07-22 at 09 59 30" src="https://user-images.githubusercontent.com/31534717/126606848-f2fcddf1-62fd-4575-aef0-6b3f1d88d566.png">

Btw, notice the dot behind the sum in the last screenshot? That's from this PR.

_Originally posted by @W3stside in https://github.com/gnosis/cowswap/issues/981#issuecomment-884716621_

**Comment by elena-zh** [comment]
Seems to be no longer relevant
