### ISSUE TITLE
'Error loading price' error is displayed when select an unsupported token

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1013]
'Error loading price' error is displayed when select an unsupported token in a From/To field
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/65eab2be-b293-4070-983d-2ce124526201)

Failing request:
https://protocol-xdai.gnosis.io/api/v1/fee?sellToken=0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d&buyToken=0xbcfB2B889F7bAa29Dd7A7B447b6C87Aca572F4f4&amount=500000000000000000&kind=sell

It would be nice to show 'Unsupported token' message instead

**Comment by W3stside** [comment]
closed by #1009
