### ISSUE TITLE
Several values are not displayed - balances, amounts and %  if language is not set to eng

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1016]
**Description**
Several values are not displayed - balances, amounts and %

**How to Reproduce**
1. Open CowSwap on Mobile
2. Connect a wallet
3. Choose a token pair

**Expected behavior**
Values should be displayed 

**Screenshots**
![1626950798618](https://user-images.githubusercontent.com/34510341/126627960-afd61d0f-747d-49d7-914c-999e4b089bd0.png)
![1626950798639](https://user-images.githubusercontent.com/34510341/126627972-187c91d7-a12c-4053-b412-5b14f9bcf8f5.png)

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

**Comment by MareenG** [comment]
![1626951459861](https://user-images.githubusercontent.com/34510341/126628979-b6475f56-075b-4405-8654-c3dc55d0132b.jpg)

**Comment by MareenG** [comment]
Okay, my last issues #1014, #1015 and this one seem all to be connected... 
If we go back to #1014 and click on the artefact: 
![1626949587012](https://user-images.githubusercontent.com/34510341/126630470-4c085659-3e33-4057-8ebb-eeb77aefaac0.jpg)

Everything is displayed correctly: 
![Screenshot_2021-07-22-13-13-10-908_com android chrome](https://user-images.githubusercontent.com/34510341/126630613-5e111716-f37d-4d52-9bbf-95cdc46ff130.jpg)

**Comment by MareenG** [comment]
Note, I experienced this also for other mobile browser, also for the MM injected browswer but not for the imToken injected browser.

**Comment by MareenG** [comment]
It actually occurs on every device or browser if the language is not set to english
compare: https://pr924--gpswapui.review.gnosisdev.com/#/swap?lng=de-DE
to https://pr924--gpswapui.review.gnosisdev.com/#/swap?lng=en-US

**Comment by alfetopito** [comment]
Closed by #1023
