### ISSUE TITLE
[0.17] Mobile - Token list: Token's description overlaps other tokens when it is an unsupported one

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1021]
Related to #1009

1. Open the app in a mobile view
2. Select an unsupported token in the To field
3. Open tokens list and search for an unsupported token there

**AR:** Token's description overlaps other tokens 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/87e4f26d-00d5-4b42-b174-3bf7241334c8)

**ER:** Token's description does not overlap other tokens

**Comment by alfetopito** [comment]
Yiikes

cc @biocom @W3stside

**Comment by W3stside** [comment]
IT'S A FEATURE

**Comment by W3stside** [comment]
thought we fixed this ages ago. Regression from 0.17 maybe. Assigning @biocom

**Comment by biocom** [comment]
We hadn't fix this I believe. This is inherited behavior from UNI:
<img width="458" alt="Screen Shot 2021-07-23 at 10 52 45" src="https://user-images.githubusercontent.com/31534717/126759117-3d7ee074-dbfb-4b73-99de-d1bac67cb5be.png">

Will address.
