### ISSUE TITLE
[0.17] iPhone with 14.6 iOS: Max button is shifted in the From field, text on the action button is truncated 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1022]
Related to #924
I was able to reproduce these issues in  iPhone 12 mini with 14.6 iOS. 
I connected the app with MM wallet in xDAI using WC and played with numbers (entered amounts > balance/selected 'long-name' tokens, etc.)
As a result, I have got Max button shifted in the From field, text on the action button truncated:
![xdai.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/088ea12a-7b57-4c70-bffb-210712c4f1f9)
video: 
https://images.zenhubusercontent.com/192335743/3b811a0f-83bf-4bc6-ab1d-acd023e392a3/xdai.mp4

**Expected**: Max button should not be shifted, text on the action button is not truncated

**Comment by alfetopito** [comment]
cc @biocom

**Comment by biocom** [comment]
Addressed in https://github.com/gnosis/cowswap/pull/1036
