### ISSUE TITLE
[Explorer] User details design

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#1040]
# Summary

Create a design based on the proposed fields defined in the doc https://docs.google.com/document/d/1KRS_vjjJUy2s1SyLJ9eSdMhGMw324JBPXH8mAUoLCRo/edit#

Base the design in the existing wireframes and design for other screens from: https://www.figma.com/file/m7obOydxAhGNmlFYvxTk3Z/GP-Explorer?node-id=0%3A1

## Requirements
- Oveview cards (suggested fields in the doc)
- Tabs (Order and Trades) where each contain a table
- The table contents is also defined on the doc

**Comment by alongoni** [comment]
Here is the protoype for the User details page
https://www.figma.com/proto/m7obOydxAhGNmlFYvxTk3Z/GP-Explorer?node-id=683%3A1280&viewport=-2714%2C-757%2C0.27317145466804504&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=683%3A1280

@alfetopito @michelbio

**Comment by biocom** [comment]
@alongoni Looks good! Couple of comments:
- I'd just do `USDC` or `USD` but not the USD(C) (can be confusing). 
- `Traded Time` --> `Execution Time`. This is more consistent with 'Execution Price'.
- [Nice to have] As for cancelling orders, OPEN orders, a user should be able to cancel this. For the CowSwap UI we're integrating this overview https://www.figma.com/file/bcoZf5RIgVKDItdOaTZq18/GP-Swap?node-id=1468%3A367
So in the current ORDERS table you created, we need to add a similar action. Perhaps just under the status label like the orders sidebar I shared.

**Comment by alfetopito** [comment]
As mentioned in the call today, Agustin, please also make a proposal for a mobile view of the same screens.

**Comment by alongoni** [comment]
Here is the prototype for the mobile view:
https://www.figma.com/proto/m7obOydxAhGNmlFYvxTk3Z/GP-Explorer?node-id=712%3A1322&viewport=-6255%2C-1536%2C0.4506815969944&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=712%3A1322

The idea is to add a horizontal scroll for the table (orders and trades). Some UI components like the search, filter and pagination will be in a fixed position. 
cc @alfetopito

**Comment by alfetopito** [comment]
As I commented in the file, my preference is against horizontal sliders, but the UI looks good and I'm ok if @biocom is ok.

Instead have every row in a "card". One example is the UI for GPv1 (https://mesa.eth.link/#/orders)

Desktop
![screenshot_2021-07-30_10-29-15](https://user-images.githubusercontent.com/43217/127690350-0d8974ad-42a3-4a09-8120-fdef9351362a.png)

Mobile
![screenshot_2021-07-30_10-29-05](https://user-images.githubusercontent.com/43217/127690363-45186bd4-351b-4613-8499-c4017d93a14c.png)

**Comment by biocom** [comment]
Yes the card approach is something I'd recommend. I'd be selective with what elements to show/hide on mobile to keep things compact/minimal.

**Comment by alongoni** [comment]
Something like this?
![UI_Explorer v1 - User details page-_ MOBILE](https://user-images.githubusercontent.com/622217/128252402-d29aa963-3e9c-4f2b-9522-efc14918d7b8.png)

**Comment by alfetopito** [comment]
> Something like this?

Yes, precisely like that!

Couple of comments regarding this initial version:
- Add a switcher icon to limit price, so users can view the inverted prices
- Maybe reduce the gap between cards? (That's @biocom's department, don't trust my design opinions :D)

**Comment by alongoni** [comment]
- Switcher icon added.
 - I've reduce a bit the gap between cards.
![UI_Explorer v1 - User details page-_ MOBILE](https://user-images.githubusercontent.com/622217/128417283-3c1a571d-16d9-4a9e-ba23-2095710c9d7a.png)

**Comment by biocom** [comment]
@alongoni Nice work! 

I'd take @alfetopito 's point into consideration as well. You could reduce the gap of the cards, to have it match the margin of the outer container/page, so they're equal.

Also, perhaps you already did, I'd experiment with a 1px smaller font-size. See if it opens up a bit more space while still making things readable: This would allow for a bit more space for larger text strings (long token symbols or larger buy/sell or price amounts) without wrapping.

**Comment by alongoni** [comment]
@biocom  @alfetopito Thanks for the feedback! Now cards are with a equal gap :)
I've made this two tests: 
| Font-size: 12px        | Font-size: 11px   |
| ----------- | ----------- |
| ![UI_Explorer v1 - User details page-_ MOBILE](https://user-images.githubusercontent.com/622217/128558252-dc8b28e9-1bf1-4cb9-965b-95279a6408c6.png)   | ![UI_Explorer v1 - User details page-_ MOBILE-1](https://user-images.githubusercontent.com/622217/128558243-776ba1d6-1843-4a09-8e6c-dd6470c85a46.png)        |

**Comment by alfetopito** [comment]
> @biocom @alfetopito Thanks for the feedback! Now cards are with a equal gap :)
> Regarding font sizes, I did these two tests:
> Font-size: 12px (0.75rem) 	Font-size: 11px (0.69rem)

Looking good!
I'm fine with either size but prefer the smaller

**Comment by biocom** [comment]
I think smaller looks better. Nice work.

**Comment by elena-zh** [comment]
@alfetopito , @alongoni , 
I'm sorry for this stupid question, but where will the button, that will navigate to the User details page, be present on the GP page?

**Comment by alfetopito** [comment]
> I'm sorry for this stupid question, but where will the button, that will navigate to the User details page, be present on the GP page?

We don't have anything in the landing page yet, so there's no path at the moment.
But users can get there from order detail page.
There, the to/from addresses will link to user detail page.

> And my favorite question: will this page be visible to a not connected user?

Yes. This is first a read-only view.
The second step is to allow user's to manage their orders (cancel order button).

**Comment by alongoni** [comment]
#1048
