### ISSUE TITLE
[v0.17] Re-enable "common bases"

### ISSUE THREAD

**Issue by W3stside** [gnosis/cowswap#1053]
**Description**
We disabled "common bases" in the currency selector modal a few versions ago. I think it's a useful feature that allows users to quickly select a common token

**Proposal**
Literally just uncomment 2 lines. Potentially add more tokens we would consider "common" - no idea on the legal implication here though. 

What it would look like:
![image](https://user-images.githubusercontent.com/21335563/126968464-fdbe92c7-92a2-4442-9717-4ff9dae37be2.png)

**Comment by anxolin** [comment]
Agree on adding this. We can double check with legal, but I think it should be fine
