### ISSUE TITLE
[0.17] Add prices switcher icon

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1055]
Discussion: https://altoros.slack.com/archives/C025G521XQD/p1627299862008000

Currently, a user is able to switch prices by pressing on prices label, however, it is definitely not obvious.
https://drive.google.com/file/d/1V8qBDjJcdZLm1kyoyfawkCII7Tc16PS0/view

Need to add the arrows icon to the label to make it more user-friendly.

**Comment by W3stside** [comment]
done already. closing
