### ISSUE TITLE
[0.17.1] Mobile Sell/Buy confirmation pop-ups exceed screen's height

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1057]
Related to #1033

Mobile Sell/Buy confirmation pop-ups exceed screen's height, so, a user needs to scroll it. As a result, a user has either modal name or Confirm button hidden. 
The reason might be changed 'Receive' section. 

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2beaf4c0-9f11-428f-855a-7333f1eaa41e) !image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/26199342-5a4f-4a8c-a058-4d9558e532fc)

https://images.zenhubusercontent.com/192335743/833e6a82-a278-41c9-b07b-b903ee87888f/svid_20210726_143230_1.mp4

Expected: modal should match a screen's height

**Comment by W3stside** [comment]
I recommend full screening the modal in mobile like:
![image](https://user-images.githubusercontent.com/21335563/127007993-99f87850-9d30-4608-bafd-5793b15e6a0c.png)

**Comment by W3stside** [comment]
at bottom of modal for mobile users, adding a "Close modal [X]" link/button

**Comment by W3stside** [comment]
attempt at handling in: https://github.com/gnosis/cowswap/pull/1063 @biocom
