### ISSUE TITLE
Selected in the 2nd field token looks like disabled

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1060]
Reproducible in Prod/Stage

**Steps**: 
1. Select a token in the From field
2. Select a token in the To field
3. Open the token list in the From/To field

**AR**: Selected in the 2nd field token looks like disabled, however, user is able to select it. 
**Video**: https://drive.google.com/file/d/18hzzFKXw2vl2K_GwsLy-JvdcXJ6RKKND/view
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9cd69fa9-30dd-4c4a-9eed-9b060586d38e)

**ER**: Selected in the 2nd field token is enabled if a user can pick it.

**Comment by W3stside** [comment]
mm I'd say this is intended as it's indicating a difference. It's almost saying "don't click it" since they already have it selected

i would recommend closing this unless @anxolin @biocom @alfetopito disagree

**Comment by biocom** [comment]
As @W3stside I'd say this is intended. For a future iteration we could play with adding labels to it like 'selected' or a checkbox on the left row. But out of scope as for a bug I'd say.

**Comment by elena-zh** [comment]
I'm closing the issue then. Thanks
