### ISSUE TITLE
Unsupported Token flagging

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1066]
**Description**
Currently the unsupported tokens are only highlighted **after the first attempt** to trade them. 
If it is possible it might be good to highlight them directly. 
<img width="498" alt="Bildschirmfoto 2021-07-27 um 12 41 08" src="https://user-images.githubusercontent.com/34510341/127141476-53054614-56f9-4a45-aeea-7b06d230e223.png">

**Comment by alfetopito** [comment]
That's a compromise we make because in order to know whether a token is unsupported, we need to call the backend first.
Given that there are hundreds (or thousands?) of tokens in the list, this would potentially be quite slow.

cc @W3stside

**Comment by MareenG** [comment]
Ok, I was expecting that there might be a limitation to this. Then happy to keep it as it is.
