### ISSUE TITLE
Token list name is not displayed in the dark mode

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1073]
Reproducible in Stage/Dev

1. Open token list
2. Press on the Manage tokens lists
3. Add a token list using  URL/iphs/ENS name option

**AR**: token list is transparent in the dark mode

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/089195b6-126b-4997-8080-6315b665f6c2)

**ER**: token list is visible

**Comment by alfetopito** [comment]
"Aw shit, here we go again"

:sweat_smile: 

cc @biocom

**Comment by biocom** [comment]
> "Aw shit, here we go again"
> 
> 😅
> 
> cc @biocom

/ Jumps on bike 🚲 

Oke will address.

**Comment by W3stside** [comment]
lmao

**Comment by biocom** [comment]
Addressed in https://github.com/gnosis/cowswap/pull/1114
