### ISSUE TITLE
[v.0.17] UI - Receive section boarder line changes it color on hover in the light mode

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1076]
Reproducible in Stage/Dev

1. Open Swap page in the light mode
2. Specify tokens and amount to swap
3. Hover a mouse on the Receive section

**AR**: boarder color is changed to white
https://drive.google.com/file/d/1jnn5Y35DgortWJau16KB67ApIwQWqa8p/view
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f5f8c07c-1f73-45ea-be1a-3259cde2c859)

**ER**: boarder color is not changed

**Comment by alfetopito** [comment]
@biocom @W3stside tiny tiny "feature"

**Comment by biocom** [comment]
Addressed in https://github.com/gnosis/cowswap/pull/1116
