### ISSUE TITLE
[v0.17] FAQ- link has different color

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1077]
**Description**
This link is black instead of orange as the others
<img width="627" alt="Bildschirmfoto 2021-07-28 um 11 03 13" src="https://user-images.githubusercontent.com/34510341/127295548-de71552c-499b-4d56-afd8-36b6a3c20187.png">

Not sure if this is intended as it is a link, linking to a FAQ section.

**Comment by alfetopito** [comment]
It should be a link. Isn't it a link? :thinking:

**Comment by MareenG** [comment]
It is a link, it just doesn't have the same colour as the other links.

**Comment by elena-zh** [comment]
I'd like to add, that all links are in black instead of being in orange on the 'Terms and Conditions' page in the light mode.
![image](https://user-images.githubusercontent.com/70885163/127500287-a299c05c-03f5-4f08-88f0-cf504d3240bb.png)

**Comment by elena-zh** [comment]
seems to be fixed in #1101

**Comment by alfetopito** [comment]
Yes, all links on FAQ (should :crossed_fingers:) have the same color now, which is normally black and orange on hover.

Please re-open if that's not the case.
