### ISSUE TITLE
[v0.17] Wrong mouse icon

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1078]
**Description**
When hovering over the highlighted section the glove appears. 
This gives the user the impression that those sections are clickable but they are not. 
<img width="568" alt="Bildschirmfoto 2021-07-28 um 11 06 50" src="https://user-images.githubusercontent.com/34510341/127296129-da5501e8-2c0f-44a7-931e-8f97c1549286.png">

**Comment by alfetopito** [comment]
cc @biocom @W3stside  any idea whether this is inherited from uniswap?
Anyway, would be just a matter of resetting the cursor to default on those components, right?

**Comment by biocom** [comment]
This is inherited. The reason the balance is clickable, is that on click, it functions as the 'max' feature (which I think is good). Arguably we should disable it at the very least for the USD estimate.

**Comment by biocom** [comment]
Would propose to mark as 'wontfix' / to close as I see it as a feature.

**Comment by biocom** [comment]
Addressed in https://github.com/gnosis/cowswap/pull/1361
