### ISSUE TITLE
Indent in Expert mode

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1093]
**Description**
When the expert mode is enabled the styling of the price section is a bit off. 

<img width="471" alt="Bildschirmfoto 2021-07-29 um 09 38 17" src="https://user-images.githubusercontent.com/34510341/127451685-d0c6a2f9-576b-4d23-9c70-40b0da5af894.png">

**Comment by elena-zh** [comment]
In addition, Price seems to be shifted on the Confirmation modal 
![image](https://user-images.githubusercontent.com/70885163/127471455-b6bfd235-316b-413b-9b87-4183612b1707.png)

**Comment by alfetopito** [comment]
Hmmmm

cc @biocom

**Comment by biocom** [comment]
Likely the 3rd (hidden) arrow. Will investigate.

**Comment by biocom** [comment]
Was something else... fixed in https://github.com/gnosis/cowswap/pull/1121
