### ISSUE TITLE
Confirm Swap Modal not displayed

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1098]
**Description**
I encounter today the case that the confirm swap modal was not displayed and I was directly forwarded to the MM window to sign the transaction. 
I didn't noticed that I did anything differently. I will report more details in case I experience this again

**Comment by elena-zh** [comment]
@MareenG , conform modal is not displayed in the expert mode. 
It appears in the regular mode.

**Comment by MareenG** [comment]
Woah, when did this change happen :flushed:

**Comment by alfetopito** [comment]
I think it always the behaviour? :sweat_smile:
