### ISSUE TITLE
[0.17] Issues with common tokens in other networks

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1103]
Originally reported in https://github.com/gnosis/cowswap/pull/1070#pullrequestreview-717483311
Related to #1099

**xDAI**: 
broken icons
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/01e108bd-00c9-4ec4-a6ba-3cc553429a75)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/8662d10d-2a85-49ff-b4c1-07fc7a9856c7)

**Rinkeby**: 
impossible to pick  token from the Common tokens section
https://drive.google.com/file/d/1XaJfT0ae8cFoL2PvHhrv_4hK7hHiAst3/view

**Comment by MareenG** [comment]
I think this issue is only connected to Rinkeby in Mainnet and XDAI it works

**Comment by elena-zh** [comment]
duplicate of #1123
