### ISSUE TITLE
[0.17] No USD estimation when select a token pair where there's a huge price difference

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1104]
related to #1091, #1099

still I can face the issue when select a token pair where there's a huge price difference: 
![image](https://user-images.githubusercontent.com/70885163/127466842-68136f1a-69ca-4a08-8a61-d8e325c35507.png)
![image](https://user-images.githubusercontent.com/70885163/127473646-f05e7c2f-1776-4266-a5cc-d45cf2603abf.png)

**Expected**: USD estimation should show <0.01

**Comment by elena-zh** [comment]
Ann additional note for this issue is related to xDAI: seems to a be a bit strange that we have a Fee estimation, while we do not have a token price estimation at all: 
![image](https://user-images.githubusercontent.com/70885163/127472972-db28503f-ecc6-497f-ba28-5f841792c93e.png)

btw, as I have mentioned before in #1019 , a lot of tokens in xDAI do not have a USD estimation...

**Comment by anxolin** [comment]
I think the issue is not with a big price difference, I think that when you show the inverse price it doesn't show the USD estimation. 
This happens even for two stable coins which have around the same value. 

https://user-images.githubusercontent.com/2352112/127526124-7a1d8e0a-44b3-45bf-8813-e361950d056f.mp4

**Comment by alfetopito** [comment]
@anxolin it should show IMO.
I'll look into it.

@elena-zh regarding the second point (there's USD for fee but not for the amount), that's because the fee is always in sell token, and there's an estimation for that in your example.
Can't remember why it's in buy token, though

**Comment by alfetopito** [comment]
Precision is too high?

![screenshot_2021-07-29_14-12-08](https://user-images.githubusercontent.com/43217/127566422-a41005fe-5bb4-42ae-9231-a041e05aa6d7.png)

Investigating...
