### ISSUE TITLE
Update discord link in feedback form

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1110]
**Description**
The _contact us_ link in the feedback form links to the Gnosis and not CowSwap discord channel.
<img width="347" alt="Bildschirmfoto 2021-07-29 um 12 34 49" src="https://user-images.githubusercontent.com/34510341/127477576-fc7be9ca-94f7-423d-935d-4bfc0e824802.png">

**Comment by anxolin** [comment]
Solved @MareenG good catch!
