### ISSUE TITLE
BARN - Errors 'Failed to check transaction hash' in console

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1111]
I have the app connected to my MM wallet in the Mainnet. 
I do not do any actions - the app is just opened, and errors 'Failed to check transaction hash' along with 'Unchecked runtime.last error: The message port closed before a response was received.'  appear in console appear each 30 sec.
![image](https://user-images.githubusercontent.com/70885163/128847976-36dffebb-38c8-4f1d-b799-8cbe5265ca45.png)

**Expected**: no errors in console?

**Comment by alfetopito** [comment]
Aha! This is what I'm looking for and couldn't find the source when I checked yesterday https://github.com/gnosis/cowswap/issues/904.

Did the error persist after the tx was mined?

**Comment by elena-zh** [comment]
No, no errors when transactions are mined.

**Comment by alfetopito** [comment]
I suspect then this is just an expect behaviour and should not be treated as error.
We are looking for the tx on the network, but it's still pending in the mempool. Thus, nothing is found.

**Comment by elena-zh** [comment]
I'm closing the ticket then.

**Comment by elena-zh** [comment]
I re-opened the issue and updated its description: today I see a lot of error in console in the https://barn.cowswap.exchange/#/swap without doing any action.

**Comment by alfetopito** [comment]
Is the it the same error as before?

**Comment by elena-zh** [comment]
Yesterday the error was the same. 
But I cannot see it today. Strange things are happening.. =/
I'm closing the issue again..
