### ISSUE TITLE
[0.17] 'To' field is clued to the Swap action button when wrap/unwrap 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1112]
Related to #1099

Fill in the ETH-WETH token pair

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/703404c5-02c8-483f-906d-8862c7aecfc7)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f71a2b0d-753c-4dfb-b9fe-d7169f44c13e)

**Expected**:  'To' field is not clued to the Swap action button

**Comment by alfetopito** [comment]
I was sure @W3stside fixed something quite similar to this.
Guess not :shrug: 

cc @biocom

**Comment by biocom** [comment]
Addressed in https://github.com/gnosis/cowswap/pull/1128
