### ISSUE TITLE
[0.17] 'Recent activity' name is not displayed in the dark mode

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1113]
Related to #1099

1. Connect a wallet
2. Open an account details in the dark mode: 

**AR**:   'Recent activity' name is not displayed in the dark mode
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d45d5cfa-d4e5-4b5f-ae50-acd08af6d465)

**ER**:   'Recent activity' name is displayed in the dark mode
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/875e411b-7334-405e-a1e6-9d2206aaf370)

**Comment by alfetopito** [comment]
I'd say "won't fix" as we are reworking this tab completely

@biocom to keep in mind in your PR https://github.com/gnosis/cowswap/pull/950

**Comment by anxolin** [comment]
Agree with Leandro

**Comment by biocom** [comment]
Same thoughts @alfetopito We're currently working on a new orders/activity component here https://github.com/gnosis/cowswap/pull/950

**Comment by elena-zh** [comment]
will be fixed in #1227 
closed
