### ISSUE TITLE
Issue broken fee price

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#1120]
**Description**
the UI was broken in xDAI where the fee was very small:
![image](https://user-images.githubusercontent.com/2352112/127526982-4d211a14-0098-439d-b37b-f73e25b1ec00.png)

It auto-fixed itself after some minutes:
![image](https://user-images.githubusercontent.com/2352112/127527009-34a51bd6-2b1f-464d-8660-028e64ce9d1e.png)

**How to Reproduce**
1. Go to xDAI
2. Get an estimation

**Expected behavior**
One proposal is something like this:
![image](https://user-images.githubusercontent.com/2352112/127527615-0c740742-5cfd-48e5-a5e5-bab31bc47143.png)

**Comment by alfetopito** [comment]
I take the solution in regards to the USD estimation is to set `smallLimit='0.01` so we can have `< 0.01` in that case.
Similar to what I did on https://github.com/gnosis/cowswap/pull/1091

We don't need all that precision for USD estimations

**Comment by alfetopito** [comment]
It has been reverted, will keep open until it's merged again
