### ISSUE TITLE
Rinkeby base tokens is broken

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#1123]
**Description**
You cannot select a token. They have mainnet addresses so if you click on them, nothing get's selected

**How to Reproduce**
1. Connect to Rinkeby
2. Open the token selector
2. Click on DAI, USDC or USDT

**Comment by alfetopito** [comment]
Related to, duplicate of https://github.com/gnosis/cowswap/issues/1103 ?

**Comment by elena-zh** [comment]
@alfetopito , duplicates #1103, I have closed that one.
