### ISSUE TITLE
Issues with consistent tiny token amounts displaying

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1129]
Related to #1127, #1135

Confirmation pop-up: 
![confirmaiton.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/19300373-7bc2-4ba7-9bcd-8cc89ba6e074)

Notification pop-up: 
![zeros.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f26bc20f-a835-4664-94e5-8efb7b1da085)

Activity log: 
![activity log.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/b9217a8b-e886-4365-9b77-9374be1c3f83)

Amount+balance:
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6b4a0a93-0d8f-4d3d-8dd7-3343949479b4)

Expected: show `0.000001`
![image](https://user-images.githubusercontent.com/70885163/127644171-5b5a8ee4-e57f-42d2-82af-77c04368702d.png)

**Comment by alfetopito** [comment]
Being addressed on https://github.com/gnosis/cowswap/pull/1135
