### ISSUE TITLE
token list settings are displayes in light mode colors in dark mode

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1146]
**Description**
The pop up modal for the token list settings is in the light mode while the whole page is in dark mode

**How to Reproduce**
1. Open _select a token_
2. Click on _manage token list_
3. Click on wheal bar for token list settings
4. See wrong colours

**Expected behavior**
Dark mode colors are displayed

**Screenshots**
<img width="583" alt="Bildschirmfoto 2021-08-02 um 14 46 22" src="https://user-images.githubusercontent.com/34510341/127864589-a900352b-162e-4bc3-a9f7-1295b9fc67cb.png">

**Comment by elena-zh** [comment]
Might be a duplicate of #1072

**Comment by MareenG** [comment]
Jupp :)
