### ISSUE TITLE
Double message - one wrong cancelation message

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1164]
**Description**
I got a message that my trade was canceled shortly afterwards I got one that thet order was filled. 
In the end it was filled

**How to Reproduce**
1. Go to Cowswap
2. Swap token 
3. Cancel order
4. Eventually you will get the two messages

**Expected behavior**
I would expect not to get both notification. 

I know that we only offer a soft cancelation and sometimes the order can get through eventhough it is canceled. 
In this case I was just wondering as it looks like the info about the cancelation came in first and then that the order went through. If you compare the timer in the pop up you see that one is shorter than the other. 
So I was wondering how we can get the info that the order was canceled and shortly after that it went through. 

**Screenshots**
<img width="411" alt="Bildschirmfoto 2021-08-03 um 16 01 19" src="https://user-images.githubusercontent.com/34510341/128030143-686a3d8b-b124-4f1b-bba9-151e3906a6c2.png">

**Additional context**

Mainnet 
20min expiration time
Order: https://protocol-explorer.staging.gnosisdev.com/orders/0x1df9f273b82ff52d0977f350c17d6de5e19e2c39d633d4cbaf3d2c05cd8e525c8bc0fe84022542e1611ff252090028df741ad6706109507a

**Comment by elena-zh** [comment]
@MareenG , I'm sorry about not obvious issues' names, but this bug was reported and discussed in https://github.com/gnosis/cowswap/issues/974#issuecomment-888434777
