### ISSUE TITLE
[T&C] - Numbering is not bold in sections

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1173]
**Description**

The numbering of the section in T&C should be also in bold
<img width="656" alt="Bildschirmfoto 2021-08-04 um 13 14 05" src="https://user-images.githubusercontent.com/34510341/128172063-9217fb3f-79d2-4a3e-b79c-292af187f191.png">

**Comment by elena-zh** [comment]
Might be fixed in #1229

**Comment by alongoni** [comment]
Closed by #1860
