### ISSUE TITLE
Add note informing about new version in the banner

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#1183]
**Description**
Add a message informing about the change in the smart contracts to make users aware about the approval, and explain there's a 48h discount in the gas price.

**Comment by alfetopito** [comment]
We could use the new "banner" component added by Protofire
- https://github.com/gnosis/cowswap/issues/943
- https://github.com/gnosis/cowswap/pull/1001

**Comment by elena-zh** [comment]
Seems to be that it was already added. 
So I'm closing the issue
