### ISSUE TITLE
[BARN] Impossible to approve a token in the integrated MM browser in iOS

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1195]
1. Open MM app in iOS
2. Open an integrated browser there
3. Connect a wallet
4. Specify tokens in From (not approved token)/To fields, amount to swap

**AR**: Prices are recalculated, Swap button is enabled.
Actually, the 'Allow Cowswap to use your token' button appeared 2 times in a while, but:
1st time: I was not able to press on it
2nd tike: I was not able to sigh the transaction
WEB version: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/06824fc3-404d-431b-84b8-47a870a00dea)

MM integrated browser version: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/afbd44fe-16d6-4ab7-944c-83a7782e3b10)

**ER**: 'Allow Cowswap to use your token' button should appear first.

**Comment by anxolin** [comment]
This should be the same version as staging. In theory should affect production and staging too

**Comment by MareenG** [comment]
I tired it today and I could approve new tokens in using an Iphone and the MM app. Did you check if you have enough ETH balance in your account? see #1211

**Comment by elena-zh** [comment]
Yes, I have enough ETH balance in my wallet. 
It seems to be a local issue with my device then.  I will reinstall my MM wallet and will try to re-run these tests. 
Thanks

**Comment by elena-zh** [comment]
Closed.
There were issues with my MM wallet in a device. 
After removing and reinstallation it I was not able to reproduce it.
