### ISSUE TITLE
WC - TrustWallet: 'Connected with CowSwap' is displayed instead of 'Connected with TrustWallet'

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1197]
Connect a Trustwallet using WC
Open Account into

**AR**: 'Connected with CowSwap' is displayed
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1d2add22-1289-4505-9e3d-f70754becf99)

**ER**: 'Connected with TrustWallet'

**Comment by alfetopito** [comment]
lol that's new

**Comment by elena-zh** [comment]
Closed: not reproducible so far
