### ISSUE TITLE
[BARN, mobile] -  dynamic announcement and url warning shown

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1224]
**Description**
When opening Cowswap in the in app MM browswer on Android the new announcement was shown. When closing it the old message with the url was also displayed. 
On Desktop and on Iphone only the new was shown so far. 

**How to Reproduce**
1. Go to https://barn.cowswap.exchange/#/swap in MM browser
2. Observe announcement header

**Expected behavior**
I guess only the new message should have been shown. 

**Additional context**
Can't check if this is reproducible as I closed the messages already.

**Comment by elena-zh** [comment]
some more details https://github.com/gnosis/cowswap/issues/1200#issuecomment-895473239

**Comment by MareenG** [comment]
Didn't see the whole thread before :)  so it happens on web and mobile :). 
If wee keep both announcements we should consider this #1207

**Comment by elena-zh** [comment]
Yes, sure. 
So, let this issue exist as a separate task =)

**Comment by MareenG** [comment]
Just for clarification. 
Do we want both messages to be shown or just the new ones?

**Comment by elena-zh** [comment]
I have just verified the issue: seems to be not reproducible. 
@MareenG , could you please check whether it is still reproducible for you?
