### ISSUE TITLE
[BARN] - Firefox, tricky to close dynamic announcement for reduces screen size

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1226]
**Description**
The dynamic announcement can't be closed on if the uses Firefox on a reduced screen, scroll bar is blocking the close section. There is only a small section where it is actually clickable

**How to Reproduce**

1. Reduce screen size
2. Go to https://barn.cowswap.exchange/#/swap using FF 
3. try to close dynamic message

**Expected behavior**
Should be a bit easier to close the section. 
If possible the area that needs to be clicked in order to close it can be enlarged. 

**Screenshots**
https://user-images.githubusercontent.com/34510341/128880560-3ffb6a6e-4f93-403a-b5cd-b5629a14774b.mov

https://user-images.githubusercontent.com/34510341/128880510-97ab23bf-c4c9-453c-842b-fba4468dedc7.mov

**Comment by elena-zh** [comment]
I'm not able to reproduce the issue in Win10+FF after the latest changes in banners style.
@MareenG , could you please retest it on MacOS+FF?

**Comment by MareenG** [comment]
The banner where adjusted so this issue is solved :)
