### ISSUE TITLE
[xDai] Different fees on swap and confirmation modal 

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1230]
**Description**
When swapping any token to GNO on XDai the fees are different in the swap modal compared to the confirmation modal

**How to Reproduce**
1. Go to Cowswap
2. Set network to  XDai.
3. Insert any from token
4. Chose GNO as to token
5. Insert swap amount 
6. Observe Fees 
7. Click on Swap 
8. Observe the fees displayed in the confirmation modal

**Expected behavior**
Fees should be the same in both modals

**Screenshots**
<img width="1294" alt="Bildschirmfoto 2021-08-11 um 09 34 32" src="https://user-images.githubusercontent.com/34510341/128988851-572c9867-eb3d-4c16-a25d-b5753271874f.png">
<img width="1237" alt="Bildschirmfoto 2021-08-11 um 09 34 44" src="https://user-images.githubusercontent.com/34510341/128988855-3ca5b04e-d11e-4fab-b446-bb5f00efa18a.png">

Note: the Error messages appear when switching to the confirm modal.

**Additional context**
This is not connected to the BARN environment  It is present on cowswap.exchange and barn.cowswap.exchange

So far I only observed it on XDai for GNO

**Comment by elena-zh** [comment]
This issue is related to #972,  #1120, #1127 and should be fixed in #1135

Errors in console ('buy/10000000000' ; [useBestUSDCPrice] Error getting best price Error) say that there is no USD estimation for this token (reported in #1019)

**Comment by MareenG** [comment]
Not present anymore. Should have been fixed by #1135
