### ISSUE TITLE
Connection modal is still displayed when change a connection type

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1240]
Related to #1227 and #1234

1. Connect a wallet
2. Open side bar
3. Press on the 'Change' button
4. Connect another wallet

**AR:** Connection modal is still displayed
https://drive.google.com/file/d/1mZNLbEdppMQnpVSi-DNpsUg9c73tAt5r/view

**ER:** Close the connection modal. 
In the previous version 'Account' modal appeared right after connection of another wallet. Do we need to open side bar now or we just simply could show something like 'Connected! modal?

**Comment by biocom** [comment]
Should be fixed in https://github.com/gnosis/cowswap/pull/1310 @elena-zh

**Comment by elena-zh** [comment]
Yes, thanks @biocom .
I have verified this issue today in #1279 : works fine there
