### ISSUE TITLE
Ledger: no error message displayed if transaction is not signed

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1246]
**Description**
When a user doesn't sign a transaction with the ledger device no error message is shown.

**How to Reproduce**
1. Go to cowswap
2. Place any swap
3. press swap and confirm
4. Confirm MM pop ups 
5. Cancel transaction on Ledger
6. No Error message is displayed
 
**Screenshots**

https://user-images.githubusercontent.com/34510341/129190666-8739ff03-6585-4999-aca0-52fdadfba9d7.mov

User is stuck in waiting for confirmation modal 

**Expected behavior**
The error message: "User denied message signature"
Should appear as it does when the user rejects to sign in MM

https://user-images.githubusercontent.com/34510341/129190677-78ebba8f-4177-440e-88b0-369533a18409.mov

**Comment by alfetopito** [comment]
Does it work otherwise?
Just to understand whether the notification is missing or is the issue with ledger connection reported on https://github.com/gnosis/cowswap/issues/967

**Comment by MareenG** [comment]
It works otherwise. I can do a swap using my ledger. 
But if I personally interrupt the process by pressing ❌ instead of ✅ on my ledger. I don't get an error message I am just stuck in the confirmation modal.
