### ISSUE TITLE
Pending icon problems

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1247]
**Description**
In some cases the pending icon seemed to have disappeared or causing an error without affecting the transaction. 
Reportd by a user: 
https://gnosisinc.slack.com/archives/C025G521XQD/p1628778615015000
He submitted the feedback from Chrome 92 @ 1440 x 821 on Mac, Mac OS X 10.15.7 I guess this is the set up he used for swapping the tokens 

The other case was reported by here by Anxo
https://gnosisinc.slack.com/archives/C025G521XQD/p1628674144001300

**Expected behavior**
Currently the pending should only disappear if recent activities is cleared

**Comment by elena-zh** [comment]
Might be fixed by #1395

**Comment by MareenG** [comment]
Can close it for now
