### ISSUE TITLE
404 Error Page is not defined

### ISSUE THREAD

**Issue by fapesteguia** [gnosis/cowswap#1251]
**Description**
If you insert an URL that doesn't exist, redirects you to the home page and you are able to perform transactions.

**Example:** https://cowswap.dev.gnosisdev.com/dsgsggs#/swap

**How to Reproduce**
1. Go to 'https://cowswap.dev.gnosisdev.com/dsgsggs#/swap'
2. See the error

**Expected behavior**
We need to place a fun 404 Error Page to avoid this issue

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60f596fb1a8ac4a2758a9780/c950a82e-430f-421a-a015-0a46b053792e)

**Comment by alongoni** [comment]
Hey! I've made the design for 404 error page:

- Dark mode:
![v1 - desktop - dark mode](https://user-images.githubusercontent.com/622217/130498440-2eebb854-43cd-40af-95d6-8d3bd3db8936.png)
- Light mode:
![v1 - desktop](https://user-images.githubusercontent.com/622217/130498445-9d567189-f28b-4263-a781-17674cd59411.png)
- Mobile (light mode)
![v1- mobile](https://user-images.githubusercontent.com/622217/130498429-1898a117-0a04-498b-933b-4cfc7e6b1fbf.png)

cc @alfetopito @matextrem

**Comment by alfetopito** [comment]
:+1: for the desktop design

For mobile design, would make sense to extend the page to fill the screen?
Of course, except header/footer/navigation etc.

For the text, suggestions:

`Something went wrong!` -> `Page not found!`

`404 Error` -> `The page you are looking for does not exist.`

`Back to home!` -> `Back home`

@biocom any additional thoughts?

**Comment by alongoni** [comment]
![v1 - desktop](https://user-images.githubusercontent.com/622217/130528530-a71d83fd-ec0d-41f0-9f70-9e47bd3f9eee.png)
![v1- mobile](https://user-images.githubusercontent.com/622217/130528520-1f05fbc1-7590-4d5f-939e-8ab9fd40bbf2.png)
![v1 - desktop - dark mode](https://user-images.githubusercontent.com/622217/130528527-862d8137-077e-4056-9279-88be37872b77.png)

**Comment by biocom** [comment]
I think that works 👍🏼

**Comment by elena-zh** [comment]
> ![v1- mobile](https://user-images.githubusercontent.com/622217/130528520-1f05fbc1-7590-4d5f-939e-8ab9fd40bbf2.png)

On all the rest content pages we display a footer in a mobile view. As @alfetopito has mentioned above, it would be nice to show it on this error page. 
![image](https://user-images.githubusercontent.com/70885163/130595690-2b896c59-96ac-4b9a-9c45-49e1c65b1883.png)

**Comment by alongoni** [comment]
Updated design:
Final design is here:
https://www.figma.com/file/bcoZf5RIgVKDItdOaTZq18/?node-id=2258%3A2
![v1 - desktop - dark mode](https://user-images.githubusercontent.com/622217/130647945-b3000a94-2755-4c35-bc1c-365989e98170.png)
Upda
![v1 - desktop](https://user-images.githubusercontent.com/622217/130647952-02e97ba6-9ce4-4e05-bef9-f622ca850b14.png)
![v1- mobile](https://user-images.githubusercontent.com/622217/130647937-a648fdef-c835-40a8-9271-2a3cea0701d3.png)
