### ISSUE TITLE
Increase default slippage

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#1261]
Our slippage tolerance is 0.5% by default. Some other exchanges have higher ones.

By increasing the slippage, we have more tolerance to prices moving, we generate more surplus, and increase Coincidence of Wants

The argument is, most exchanges use higher slippage tolerance, so it's kind of standard practice, additionally CowSwap can justify higher percentages since the trades have some MEV protection.

**Comment by elena-zh** [comment]
One more related issue I'd like to discuss here: currently, the app allows to set the slippage = 0.00%. 
![image](https://user-images.githubusercontent.com/70885163/129565135-0fdb8b3c-2fe3-4085-b170-741f79abfb5b.png)

Is that OK or it is better to disable this option and allow a user to set at least 0.01%?

**Comment by alfetopito** [comment]
I say 0% is ok, if the user wants absolutely no slippage

**Comment by anxolin** [comment]
> I say 0% is ok, if the user wants absolutely no slippage

Yes, good point, although is as Leandro said. This would affect the default only.

As a reference, for this proposal. 1inch is 1%, that could be a good number. 

![image](https://user-images.githubusercontent.com/2352112/129607892-9dbde4ff-04d2-4c36-a46e-db6ce1183acf.png)
