### ISSUE TITLE
App freezes when selecting unsupported token

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#1264]
**Description**

App freezes when selecting unsupported token

**How to Reproduce**
1. Go to cowswap.exchange
2. Connect a wallet on xDai
3. Select as buy token `FRACTION` (0x2bF2ba13735160624a0fEaE98f6aC8F70885eA61)
4. Insert an input
5. The UI will tell you the token is unsupported
6. Open the token selector and pick `FRACTION` again
7. The UI freezes

**Expected behavior**

The UI should not freeze when an unsupported token is selected

**Screenshots**

https://cdn.discordapp.com/attachments/869170873033166868/876884157857423380/Untitled__Aug_16_2021_8_42_PM.webm

**Additional context**

Reported by a user on Discord

**Comment by alfetopito** [comment]
Update: solved by cleaning browser cache.

Still worth investigating what cause it to break in the first place.

**Comment by MareenG** [comment]
I couldn't reproduce it yet ( tried Chrome, Brave, FF and also other unsupported Tokens).
Do we have more specifications?

**Comment by MareenG** [comment]
I encountered the issue now as well. 
It can freeze in different stages: 
- First try it froze already at step 3 Select as buy token FRACTION (0x2bF2ba13735160624a0fEaE98f6aC8F70885eA61)
- second try it freezes in step 6 ( Open the token selector and pick FRACTION again) when scrolling down to the FRACTION token

**Comment by MareenG** [comment]
I noticed that on Xdai some tokens are already flagged as unsupported tokens ( FRACTION, ADAI, CREAM). 
In #1066 we discussed that this should only happened after the user tried to trade them for the first time. 
For those tokens the app freezes. 
However, if I e.g. try to trade XRT which is not flagged as unsupported in the first place but after the first try the app doesn't freeze.

**Comment by alfetopito** [comment]
I believe they are already flagged as unsupported because you tried them out before.
AFAICT, this information is stored only in your browser as we don't have the unsupported list stored on the code.
I assume if you try again next time with XRT you'll have the same behaviour as FRACTION, ADAI, etc.

**Comment by elena-zh** [comment]
Finally, I was able to catch this issue as well 
https://drive.google.com/file/d/1whIWxxolqV6XZMCmP_S-lYo302jtwYhi/view
