### ISSUE TITLE
FAQ - make titles in TOC stand out more

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1274]
**Description**
The titles in the table of content look like the subtitles. Might be nice to let them stand out a bit.

**Proposal**
<img width="616" alt="Bildschirmfoto 2021-08-18 um 11 03 22" src="https://user-images.githubusercontent.com/34510341/129871855-defacb9a-7175-4f7e-b021-cc46839da00c.png">

**Comment by alfetopito** [comment]
@biocom ?

**Comment by biocom** [comment]
Yes good with me. Additionally I think I'd add an 'anchor'/'url' icon behind it, to indicate a section anchor link.

**Comment by elena-zh** [comment]
@fairlighteth , I think we have already enhanced the section. Closing.
