### ISSUE TITLE
Suddenly the displayed Balance disappeared

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1300]
**Description**
Suddenly the displayed Balance disappeared.
This happend right after the nose picking cow disappeared.
I tried it again and it disappeared again after several price updates. (Couldn't find a clear pattern yet like after 5x times it disappears)

<img width="501" alt="Bildschirmfoto 2021-08-23 um 11 02 04" src="https://user-images.githubusercontent.com/34510341/130420602-e23f9b5a-dfa2-4e99-86aa-34b3ac083d02.png">
<img width="509" alt="Bildschirmfoto 2021-08-23 um 11 01 59" src="https://user-images.githubusercontent.com/34510341/130420610-2fdd56a4-ae86-44ad-8bcb-f77871b37252.png">

Reported here: 
https://github.com/gnosis/cowswap/pull/1281#issuecomment-901776949

**Comment by elena-zh** [comment]
Hey @MareenG , is this still reproducible for you? 🧐

**Comment by MareenG** [comment]
It didn't happen all the time so I can't say 100% that it is not reproducible. 
But it hasn't appeared since then. 
We can close it for now and in case it shows up again reopen it :)
