### ISSUE TITLE
Expert mode- warning message misalignment

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1301]
**Description**
When an warning appear in the expert mode the alignment is a bit off. 

**How to Reproduce**
1trigger a warning/error message (e.g. don't sign the MM transaction)

**Screenshots**
<img width="612" alt="Bildschirmfoto 2021-08-23 um 14 22 18" src="https://user-images.githubusercontent.com/34510341/130446669-b9eecb82-bc08-4fbc-a374-a995112f762d.png">

**Comment by elena-zh** [comment]
Duplicated #1150 =)
