### ISSUE TITLE
Easily change networks

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#1319]
**Description**
Implement an easy way to change networks. It would also make it more explicit what are the supported networks.

There's a proposal for the Explorer already, we could do it for both explorer and CowSwap

![image](https://user-images.githubusercontent.com/2352112/130940329-2b906e8a-5e0b-42ad-9c06-f75756772ad9.png)

We need to also decide on the details:
* When u change, and we discover the network is in another network, what do we do?
* How can we provide an easy way to add xDAI? Do we prompt to add it in his networks when he changes
* What happens if you are in a network and you change the network in your wallet? Do we change automatically in the APP?
* Other things to take into account?

**Comment by MareenG** [comment]
I think it would be good to display the networks after the wallet is connected.
<img width="441" alt="Bildschirmfoto 2021-08-31 um 09 56 14" src="https://user-images.githubusercontent.com/34510341/131465559-4dda07e5-c4e3-4715-b023-790aca0b0583.png">

**Comment by MareenG** [comment]
Usally we don't display Mainnet in this case it might be good to display it.
Could be confusing if the other networks are displayed but not the one you are actually in.
<img width="548" alt="Bildschirmfoto 2021-08-31 um 09 56 54" src="https://user-images.githubusercontent.com/34510341/131465873-4632ec93-34c4-4fb1-942f-6b1b8a563782.png">
Compared to: 
<img width="539" alt="Bildschirmfoto 2021-08-31 um 10 02 26" src="https://user-images.githubusercontent.com/34510341/131465882-1ea5dbae-1d09-4616-a9f3-5c3d70ab34fb.png">

Sth in this fashion
<img width="548" alt="Bildschirmfoto 2021-08-31 um 09 56 54" src="https://user-images.githubusercontent.com/34510341/131466828-62179cb7-c3c5-45e4-8316-ae694a4a15fe.png">

**Comment by alfetopito** [comment]
I've created an issue to deal with the network changer design https://github.com/gnosis/cowswap/issues/1368
We can keep this one to deal with the behaviour/edge cases

**Comment by elena-zh** [comment]
Closed as network selector has been implemented.
