### ISSUE TITLE
Error page improvements on iOS, FF+Win10

### ISSUE THREAD

**Issue by alongoni** [gnosis/cowswap#1328]
**Description**
Reported in #1259 
**How to Reproduce**
1. Force an error by adding e.g:
src/custom/pages/CowGame/index.tsx
inside CowGame function:
`
  if (0 === 0) {
    throw new Error('This cow is dropping some serious milk 🥛!!')
  }`

Open the error page in iOS:
**Expected**: there is no padding in the error log section from the right. And it was removed from the left: as a result, section value is not fully visible in an iPhone device (Android looks good): 
![image](https://user-images.githubusercontent.com/70885163/130442884-0c2e902b-531d-4310-9050-7cc2fe983ea5.png)

**Comment by elena-zh** [comment]
just a note: the issue is also reproducible in Firefox + Win 10
![image](https://user-images.githubusercontent.com/70885163/134385993-d0e136e5-8ff2-46a4-9d3b-5b1d67552f73.png)

**Comment by maria-vslvn** [comment]
@alfetopito @alongoni @elena-zh it’s more logics issue than css though. But i could also help with css, not such flexible way as playing with error formatting, but i could do something like this:![Снимок экрана 2021-10-01 в 18.33.56.png](https://images.zenhubusercontent.com/60a26634acdb8bf86a8e04f1/97f08506-8162-43eb-9ad1-a1df2f5f3859)

**Comment by alfetopito** [comment]
I wouldn't worry too much about this issue to be honest.

First, this is not supposed to be seen often :crossed_fingers: 
Second, users seeing this wouldn't benefit much from a nicely padded error display. As long as the reporting works, user's shouldn't care about the error.
