### ISSUE TITLE
Use price 0.1% better than Uniswap

### ISSUE THREAD

**Issue by W3stside** [gnosis/cowswap#134]
Use price 0.1% better than uniswap, so when we apply the fee, then we have the same price. 

Price calculation as discussed https://docs.google.com/document/d/16fr3ECgwbUCnza8s4p9TM5BFTa3ojX6CHMQZi-ym80M/edit?disco=AAAALb3dXSg&ts=601c53e0&usp_dm=true

**Comment by anxolin** [comment]
@W3stside I assign you to this one, and move it to In Progress, ok?
They create the issues and "PRs" in "New issues", let's try to move them to the right one

**Comment by anxolin** [comment]
@fleupold mentioned there will be 0% at first. So no sure if the 0.1% will be very compatible with the proposal of using a slightly better price than Uni. 

Moving this back to the backlog for further discussions

**Comment by fleupold** [comment]
Maybe we can discount it by the fee amount that the backend returns when you query the fee info (0% for now but could be 0.1% eventually)?

**Comment by anxolin** [comment]
@fleupold this one is in our sprint, so probably David will take it this monday. It should not a big change for us I believe, and I agree that reflects better the solvers compromise of not taking fee if they end up trading in Uni
