### ISSUE TITLE
Affiliate status messages

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#1343]
# Summary

Define messages to be displayed on affiliate states.

Proposal below coming from @anxolin :

---

Regarding the messages. Not sure when we use the term "referral" or "affiliate", but maybe we can try to be coherent. 

Some proposals on the messages:

> 1. Is it own link? (referral address matches connected wallet address) -> "Invalid code: cannot refer yourself"

I think for this message, we should be more positive, and think that the user followed his own link to make sure it works.
One idea on the direction: 

`Your affiliate code works! Anyone new user following this link would credit you his trading volume`

or 
`Valid affiliate code: Anyone new user following this link would credit you his trading volume` (if we want to make it more similar to the others)

> Has account already traded without referral code? (check will come from an endpoint still TBD) -> "Invalid code: referral only valid for new accounts"
 
Like! Maybe `Invalid affiliate code: Referral only ...`

> Has account already traded with a different referral code? (check will come from endpoint TBD) -> "Affiliate already active with a different referral code"

`Invalid affiliate code: The currently connected wallet is already part of the affiliate program"

>  Referall is valid and can be used -> "Affiliate program enabled"

`Valid affiliate code: You can now do your first trade, to join the program`

_Originally posted by @anxolin in https://github.com/gnosis/cowswap/issues/944#issuecomment-906311751_

**Comment by ramirotw** [comment]
Is there any update on this task? To know if I can update the messages or we just put the task on hold until they are 100% confirmed.

**Comment by anxolin** [comment]
There's not update from my side. I've made some suggestion with this comments, but probably until we have a demoable version it will be hard to say exactly, unless you guys want to open a google docs or figma to tackle this. 

Im fine with completing a DEMOable version, and then we try all the cases. We would collect the feedback from the people trying this out.

**Comment by anxolin** [comment]
Can we decided already on this? 

The one i feel more confident on changing is: https://github.com/gnosis/cowswap/pull/1405#discussion_r723238236

Other than that, I would either leave it as it is, or if u really want to get someone to validate (probably Anna), you could add the screenshots to a google doc and then share it with her, and in the broader team so people can suggest.
