### ISSUE TITLE
Side bar: incorrect transaction status when Approve/Wrap/Unwrap token is failed

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1353]
**Steps:** 
1. Run approve transaction 
2. Specify transaction conditions in the connected wallet to get an unsuccessful result (low gas limit or so)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2848a84d-1918-41e9-bce6-14763084ea77)
3. wait till transaction fails

**AR**: approve token transaction status = expired
![failed](https://user-images.githubusercontent.com/70885163/131133309-6c1e8208-0375-47d1-a89b-c851248f71cd.jpg)

the same is for the Wrap/Unwrap transactions
![image](https://user-images.githubusercontent.com/70885163/131134156-03e3e918-72aa-4da2-800a-ed58bf58da4e.png)

**ER**: approve token transaction status = failed.

**Comment by anxolin** [comment]
YEs, I also thing this should be included in `v1.1`
