### ISSUE TITLE
Design network changer

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#1368]
# Summary

Propose a design for a network changer on CowSwap.

Bellow is a comment by Mareen with her suggestions.

Another sources for inspiration are the Safe
![screenshot_2021-08-31_09-52-42](https://user-images.githubusercontent.com/43217/131543931-16659f4e-5816-4146-8440-60106a48506b.png)

and Balancer UI
![screenshot_2021-08-31_09-52-02](https://user-images.githubusercontent.com/43217/131543856-1447530d-ec4a-4fb2-a1c3-2ce8d22a1077.png)

---

Usally we don't display Mainnet in this case it might be good to display it.
Could be confusing if the other networks are displayed but not the one you are actually in.
<img width="548" alt="Bildschirmfoto 2021-08-31 um 09 56 54" src="https://user-images.githubusercontent.com/34510341/131465873-4632ec93-34c4-4fb1-942f-6b1b8a563782.png">
Compared to: 
<img width="539" alt="Bildschirmfoto 2021-08-31 um 10 02 26" src="https://user-images.githubusercontent.com/34510341/131465882-1ea5dbae-1d09-4616-a9f3-5c3d70ab34fb.png">

Sth in this fashion
<img width="548" alt="Bildschirmfoto 2021-08-31 um 09 56 54" src="https://user-images.githubusercontent.com/34510341/131466828-62179cb7-c3c5-45e4-8316-ae694a4a15fe.png">

_Originally posted by @MareenG in https://github.com/gnosis/cowswap/issues/1319#issuecomment-909002525_

**Comment by alongoni** [comment]
Here are some designs/[prototype](https://www.figma.com/proto/bcoZf5RIgVKDItdOaTZq18/GP-Swap?node-id=2609%3A1493&viewport=424%2C48%2C0.49&scaling=scale-down-width&page-id=2609%3A2&starting-point-node-id=2609%3A1493) for the network selector:
![v1 8 - desktop](https://user-images.githubusercontent.com/622217/132904984-3d04e95b-5c35-4e99-81fc-db63d52d61e3.png)
![v1 8 - desktop-1](https://user-images.githubusercontent.com/622217/132904979-7e30e051-c538-4a15-8e3d-10f17388db81.png)

Selector with a background variant (related to the new ui design):
![v1 8 - desktop-2](https://user-images.githubusercontent.com/622217/132904976-39d7b560-25fc-46e0-9a97-80aeb2924d4f.png)
![Screenshot from 2021-09-10 16-12-17](https://user-images.githubusercontent.com/622217/132905355-3e44ea52-cdca-44ab-b80b-e889bb3935dc.png)


Selector on mobile:
![v1 8 - mobile](https://user-images.githubusercontent.com/622217/132904974-a3bb3b1f-0a43-4b2f-9ff7-9818c0e79d2b.png) ![v1 8 - mobile-1](https://user-images.githubusercontent.com/622217/132904971-cbb4a047-5926-4b45-add8-dac700f5f13e.png)

cc @alfetopito @biocom

**Comment by biocom** [comment]
Thanks for the updates. My feedback:
- I'd stick to the non neomorphism style (without the shadow effect)
- Use network icons instead of the dots. In terms of recognition I think that could work better.

**Comment by alongoni** [comment]
@biocom Something like this?
![v1 8 - desktop](https://user-images.githubusercontent.com/622217/133128439-4c6c35b9-fb04-4f2f-8a39-4511feecb0a8.png)
![Screenshot from 2021-09-13 14-19-21](https://user-images.githubusercontent.com/622217/133128461-d7acf644-4f33-42d4-ba99-abe4e5b72d2e.png)

**Comment by biocom** [comment]
Yes something like that. I think a good example is 1inch:
<img width="231" alt="Screen Shot 2021-09-14 at 10 15 40" src="https://user-images.githubusercontent.com/31534717/133221504-ab73c188-e5e3-4a08-ac1c-4ca7f8edd57f.png">

**Comment by alongoni** [comment]
@biocom Design updated:
![selector](https://user-images.githubusercontent.com/622217/133292641-561638b7-8c8c-4bbf-951d-945c9606a729.png)

**Comment by elena-zh** [comment]
Hey @alongoni , cool!
But still 1 question from my side: how will token selector be called when open the app in a mobile view, as clicking on the address info calls Recent activity modal?

**Comment by biocom** [comment]
I think at this point we should consider hiding the main menu items (the ones on the right of the logo) on mobile. And just show the network switcher icon on the right E.g. 1inch 
<img width="371" alt="Screen Shot 2021-09-20 at 16 11 14" src="https://user-images.githubusercontent.com/31534717/134017286-41a212c8-fa7b-491a-9022-d75c0f0ce7a8.png">

Our main menu is already covered in the footer (3 dots).

**Comment by alongoni** [comment]
> Hey @alongoni , cool!
> But still 1 question from my side: how will token selector be called when open the app in a mobile view, as clicking on the address info calls Recent activity modal?

He @elena-zh Good point. [In the previous proposa](https://github.com/gnosis/cowswap/issues/1368#issuecomment-917151349)l I was thinking to add the selector over the navbar on mobile
![v1 8 - mobile](https://user-images.githubusercontent.com/622217/134077787-6ef52a63-c33a-4bd0-9df0-fbfb23286d14.png) ![v1 8 - mobile-1](https://user-images.githubusercontent.com/622217/134077777-a91ac1f9-6033-4bbe-b0cd-7befd9e9533b.png)

But, as @biocom suggested we can add the network selector inside the menu on the modal. By replacing the current network indicator:
![selector-on-menu](https://user-images.githubusercontent.com/622217/134078440-1be67b9d-943c-4027-aa25-348b8db0845d.png) ![selector-on-menu-open](https://user-images.githubusercontent.com/622217/134078279-1c8bce78-901b-45c2-9276-5563c1c12332.png)

I'm not sure about using only the networks logo/brands (E.g. 1inch). I would prefer "logo + Network Name". 🤔

**Comment by biocom** [comment]
As a note, in my opinion it's better to not use the selector inside the orders sidebar, but only on the top right header.

**Comment by alfetopito** [comment]
I like the proposal and personally prefer to have the network names.
My reason for that is (I assume) most users are not aware of networks, even less can recognize which they are connected to by the icon alone.

**Comment by alongoni** [comment]
> As a note, in my opinion it's better to not use the selector inside the orders sidebar, but only on the top right header.

Maybe It can look like this:
![v1 8 - mobile](https://user-images.githubusercontent.com/622217/134230212-3ea477dd-9d09-4f7a-bb68-421430094505.png) ![v1 8 - mobile](https://user-images.githubusercontent.com/622217/134230551-9c43b202-11f1-412c-a0df-370c64fdce3a.png)

**Comment by biocom** [comment]
Still two suggestions on your last screenshot:
- Hide the network name on mobile for the 'selected' / 'active' network -> But show them all on the visible/selected dropdown menu. This saves space/reduces noise on mobile. On desktop show as is.
- Instead of the hamburger icon, use the three dots, so that is matches with the desktop experience.

**Comment by alongoni** [comment]
Thanks @michelbio!
Design updated:
Option 1: Network selector + 3 dots menu on top:
 ![v1 8 - mobile](https://user-images.githubusercontent.com/622217/134424665-c4100ebd-7fbe-415d-801e-c36ecab4f699.png) ![v1 8 - mobile-3](https://user-images.githubusercontent.com/622217/134424683-3e0352dc-d7bb-46d2-a355-5a1f5e0ffdf7.png)

Option 2: Network selector on top. 3 dots menu on botton (as it is now implemented):
![v1 8 - mobile-1](https://user-images.githubusercontent.com/622217/134424659-25b21cf1-03bf-4bae-a80d-d79af5c15b73.png) ![v1 8 - mobile-2](https://user-images.githubusercontent.com/622217/134424692-c679a188-0c70-41b1-9f75-84cc34cd463c.png)

**Comment by alfetopito** [comment]
I'm in favor of the second option.
Not strongly against the first though.

**Comment by biocom** [comment]
Yes, perhaps for now let's use what's already implemented (in terms of 3 dot menu icon position).

**Comment by biocom** [comment]
As a reference, this is a PR done by @anxolin https://github.com/gnosis/cowswap/pull/1451 - just for your reference to keep in mind.

**Comment by biocom** [comment]
@alongoni To eloborate on #1451 - Aside from the token picker, we also need to account for when a user is connecting with a non-supported network. In that scenario two things could happen:
- We show an error next to the network label 'Wrong network....'. (look at Uniswap how that is shown)
<img width="351" alt="Screen Shot 2021-09-27 at 14 20 59" src="https://user-images.githubusercontent.com/31534717/134906972-9366cdf1-67e3-4189-9258-e6ab1eb00762.png">

- A modal is popped up automatically stating 'Wrong network.....please switch to any of these supported networks'. This is a screenshot based on @anxolin 's PR:
<img width="496" alt="Screen Shot 2021-09-27 at 14 26 50" src="https://user-images.githubusercontent.com/31534717/134907684-c9413afd-007e-4c12-9e20-1cacad601a50.png">

I think we'd need a style for this modal as well to show the network list in a similar fashion.

**Comment by alongoni** [comment]
hey @michelbio
I think we can try to do this in a single component (by extending the network selector with a "wrong network" label).
So this way we don't need the modal to suggest the user to select an available network.


![v1 8 - desktop-wrong-network](https://user-images.githubusercontent.com/622217/134963697-5a626c6d-3bd8-4998-9bb8-981b18508af8.png)
That make sense? 

cc @anxolin @alfetopito

**Comment by biocom** [comment]
@alongoni Yes makes sense, in terms of combining the 'wrong network' label with the selector. 

Still, I think it might be overlooked by a user, that they're on the wrong network. Hence the idea to at least trigger the 'wrong network' modal, so it's a more explicit warning. 

Otherwise for expediting this PR we could do this separately.

**Comment by anxolin** [comment]
> Still, I think it might be overlooked by a user, that they're on the wrong network. Hence the idea to at least trigger the 'wrong network' modal, so it's a more explicit warning.

Yes, both things can be done independently. I like the proposal of wrong network. Then for the modal we could even potentially reuse the component or just enumerate the supported networks.

**Comment by alongoni** [comment]
I've change the Rinkeby color on selector and made some improvements. 
![v1 8 - desktop-wrong-network](https://user-images.githubusercontent.com/622217/135161602-38aa67a3-824a-4ce4-a80a-4e4c5fc0f5c1.png)


![v1 8 - desktop-wrong-network-1](https://user-images.githubusercontent.com/622217/135161590-c855aa0d-86a1-4518-9e8e-45d0f4473c6e.png)

Detail:
![image](https://user-images.githubusercontent.com/622217/135161366-7436e5d2-a5b4-4097-ba98-71a059e430fa.png)

**Comment by biocom** [comment]
My only comment here is, that in your example you show the KOVAN network selected + stating it's the wrong network.

There are quite a few networks like Polygon, Optimistic, Arbitrum, which won't be listed by name, if they're selected (correct me if I'm wrong). Curious what happens in that scenario. Looking at Uniswap, this is what is shown if I select POLYGON in my MetaMask:
<img width="354" alt="Screen Shot 2021-09-29 at 09 47 22" src="https://user-images.githubusercontent.com/31534717/135225402-b07ec72d-6c33-400b-9433-fd955c845547.png">

Which in my view could be better handled in terms of UX.

**Comment by alongoni** [comment]
hey @michelbio now I've the same question! 😂
I was assuming that we can obtain the network name from MetaMask (or others wallets) and show it in our network selector component, even it's not a supported network (e.g. Kovan in Cowswap).

In case that is not possible, we can only show the network selector with a "Wrong network" label. E.g:
![image](https://user-images.githubusercontent.com/622217/135328686-d959576f-3475-4800-9902-dbd103b5c83f.png)

**Comment by biocom** [comment]
Yes, I can see that work 👍🏼

**Comment by elena-zh** [comment]
Hey @alfetopito ,  are we going to implement this?
Or we are OK with the currently implemented network switcher and can close the current issue?

**Comment by alfetopito** [comment]
I believe it has been superseded when Uniswap added it to their UI and we inherited it in a merge. Closing it.
