### ISSUE TITLE
[Dev/Barn] Impossible to cancel an order

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1373]
Reproducible only on Dev servers [Dev/Barn] 
Stage and prod work fine. 

1. Place an order
2. Press on the 'Cancel order' in the side bar
3. Confirm transaction in the connected wallet

**AR**: `error cancelling the order ` pop-up is displayed. 401 error in the console
![error.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/bed2f2c1-fe55-46f1-b9da-80eef7937001)

**ER**: request to cancel an order is sent

**Comment by biocom** [comment]
<img width="357" alt="Screen Shot 2021-09-01 at 19 09 11" src="https://user-images.githubusercontent.com/31534717/131714069-556160c1-b431-4d32-b54d-3feee39a5ed2.png">

**Comment by elena-zh** [comment]
Fixed in https://github.com/gnosis/gp-v2-services/pull/1063
