### ISSUE TITLE
Propose gas estimation display/notification on UI

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#1375]
**Description**

Right now, CowSwap users have no way to tell (using the UI alone) what's the current gas price.
Although orders placed cost no gas, the fees charged on the execution are dependent on gas prices.
So it might still not be a good idea to place an order during gas spikes, as you can spend a large amount in the trade you might not want to.

On top of that, when Smart contract wallet orders are integrated, these users will have to send onchain txs when placing orders.

The goal of this task is to create a proposal on how to better indicate current gas prices to users, in a way they are aware of possible network congestion, possibly blocking/issuing a warning when unfavorable (similar to high slippage warning)

**Additional context**

**Comment by anxolin** [comment]
By the way, Aegent has something in these lines:


![image](https://user-images.githubusercontent.com/2352112/132244858-1e2e2b88-4104-4dd0-ba0c-f82e2706d842.png)

```
Network congestion and transactions in Argent

If you've seen a popup informing you that there's network congestion, it means that the Ethereum network is extremely busy.

This can have two main impacts:

Some transactions may fail - for both Argent users and everyone else on the network. 
Network fees (gas) will be very high due to the high demand.
What can you do?

Please pay attention to what the transaction fee will be.
Consider waiting for congestion to decrease before making your trade.
What are we doing to help?

Warning you when the network is busy.
Clearly labelling transaction fees.
Automatically picking gas prices based on network conditions to give your transaction the best chance of succeeding.
Researching solutions for more scalable Ethereum infrastructure.

```

**Comment by alongoni** [comment]
Here is a proposal for displaying an indicator for the network congestion. 
Maybe we can add the current gas price.

![gas-estimation](https://user-images.githubusercontent.com/622217/133831524-9cc81ce2-9d0f-4968-be5e-a72b66464ea0.png)
cc @biocom @alfetopito

**Comment by biocom** [comment]
Thanks for the proposal. My first impression:
- The slider looks like you can interact with it, whereas that is not the case and merely functions as an indicator. On a second look, I feel the slider can be ditched all together and we could stick to:
<img width="304" alt="Screen Shot 2021-09-20 at 10 22 02" src="https://user-images.githubusercontent.com/31534717/133974064-ef1783f3-1d31-4996-9544-6e6325869300.png"> with a simple text label 'High' 'Low', etc. 

Looking at we have now for the fee/price impact, we might want to use a similar approach:
<img width="511" alt="Screen Shot 2021-09-20 at 10 23 28" src="https://user-images.githubusercontent.com/31534717/133974220-9540e824-9a4b-4e22-b638-f2de0ad4c680.png">

Meaning, if there's LOW congestion, we wouldn't bother showing it (why add the noise when it's not required?). Whereas when there is quite some congestion, we show the warning.

**Comment by alongoni** [comment]
Thanks @biocom!! Maybe something like this? or I can try a similar approach with a full-with container like you mentioned above.

![gas-estimation-high](https://user-images.githubusercontent.com/622217/134205790-0c35e851-ea4f-4b18-843e-bd6751102e34.png) 
![gas-estimation-low](https://user-images.githubusercontent.com/622217/134205784-66c22d00-c683-4eb3-b301-559c457f8670.png)

**Comment by anxolin** [comment]
Great feedback Michel. 

I like way better this like proposal Agustin 👌

Maybe we can think about what to write in the tooltip. I think it's a nice opportunity to explain how this network congestion might affect the displayed fee

I'll share with the broader team for input

**Comment by avsavsavs** [comment]
Maybe we could put something along these lines: 

_Currently, the Ethereum network is congested, meaning that block space is quite expensive due to the high gas prices. As you know, CowSwap only charges the user the cost of executing the transaction (gas price), meaning that if you trade at this moment of time, the fee will be significantly higher than at times when there is no network congestion. If you are not in a hurry, we recommend you to wait until the network is not congested, so that the fee value is much lower._

**Comment by biocom** [comment]
@alongoni a suggestion based on your last screenshot:
<img width="637" alt="Screen Shot 2021-09-22 at 10 34 00" src="https://user-images.githubusercontent.com/31534717/134310407-5c2d826f-f134-4372-be95-e7f826d071b7.png">

- Reduce text amount on the labels (ditch `gas price`)
- Move labels to the left <--- and values/statuses to the right ---> just like the other elements above.
- If we most, we could rename `Network congestion` to `Network / gas congestion` or `Network congestion / gas price`. IMO the least amount of text we can get away with, the better.
- Could add the warning triangle **inside** the MEDIUM label instead. But IMO not necessary.

**Comment by annamsgeorge** [comment]
I very much like the last proposal. I think my preference would be to keep "Network congestion" and not to rename it: if we use the term "gas" here it might lead to confusion to users, they might be assuming the fee wouldn't incorporate the gas yet.

**Comment by alongoni** [comment]
Design test: Medium label + warning icon.
![image](https://user-images.githubusercontent.com/622217/134427979-d23d90e2-381b-48bb-9bc0-aad84640433e.png)
