### ISSUE TITLE
The app is changing light-dark modes when press on the space

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1381]
I noticed this issue when started to play the Cowgame. 
However, the issue is reproducible on any app's page

**Steps**: 
1. Open a page
2. Press on the sun/moon icon (using mouse click)
3. then start pressing the space button

**AR**: the app is changing light-dark modes. 
Might be not critical, but irritating when play the Cowgame
https://drive.google.com/file/d/1KaV9hSbmY7WnFwYMZBX7KxPsW52zfFB_/view

**ER**: the app is not changing light-dark modes when press on the space button

**Comment by alfetopito** [comment]
Yes, we've seen this one before.

The issue is that the focus remains on the theme toggle when you open the game after clicking on the toggle.

Although annoying, very low priority in my opinion.

**Comment by elena-zh** [comment]
Closed as duplicates #868
