### ISSUE TITLE
Filled on time in activity modal slightly different than in etherscan

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1383]
**Description**
The execution time displayed in the side bar is slightly different than in etherscan

**How to Reproduce**
1. Go to cowswap
2. Place an order and wait until it is executed
3. go to explorer and open transaction in etherscan
4. compare **filled on** in sidebar with time stamp in Etherscan

**Expected behavior**
Should be the same time or? 

**Screenshots**
<img width="1915" alt="Bildschirmfoto 2021-09-03 um 10 37 30" src="https://user-images.githubusercontent.com/34510341/131977363-c6fcae9c-18b2-41cd-8677-aacb15eb1369.png">

<img width="1893" alt="Bildschirmfoto 2021-09-03 um 10 34 52" src="https://user-images.githubusercontent.com/34510341/131977374-d0b6026d-eae7-4210-8ab3-b540a3e40a8c.png">

**Comment by alfetopito** [comment]
Yeah, it'll reamin different for now.

We are using the local time when the order execution is detected.
This causes 2 problems:
1. We check every 10s for updates
2. Local time is very likely not in sync with block times

We are working with the backend to have the execution time returned in the API call.
