### ISSUE TITLE
To value changes in waiting for confirmation modal

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1390]
**Description**
Not sure is it was always like this or introduced at one point. 
If a user doesn't sign the transaction asap the TO value changes with time. 
It even goes below the min received amount displayed before. 
What I observed so far was that the trade itself it executed as displayed at the confirmation modal. 

**How to Reproduce**
1. Go to cowswap
2. Place an order 
3. Confirm
4. Don't sign it
5. Observe the waiting for confirmation modal
6. Can take quite some time

**Expected behavior**
The value shouldn't change as the user accepted the amounts displayed in the confirmation modal before. 

**Screenshots**

https://user-images.githubusercontent.com/34510341/132007684-1cd675f5-a626-42d2-a364-3d82edd2d50f.mov

**Additional context**
The video was recorded in #1385. However it also happens in production but the time until the values change take longer.

**Comment by MareenG** [comment]
I guess it definitely belongs to the issue #1155. Will close this one and add the additional info to yours :)

**Comment by elena-zh** [comment]
Thanks!
