### ISSUE TITLE
Add Analytics to tx speed up/blocknative interactions

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#1392]
**Description**

Follow up to https://github.com/gnosis/cowswap/pull/1302

Add Analytics to tx speed up/blocknative interactions

The goal is to track how often txs are sped-up, cancelled and failed.

**Proposal**

Track tx speed-up, tx cancellation and tx failure.

**Good to have** (not sure if data is available)

- As a bonus, we could also track the original and current gas price on tx speed-up
- On tx failure, we could store the tx hash and gasLimit.

**Open questions**
Or maybe it maybe it makes sense to track every tx event with all available data for completeness?

Tx events:
- tx created
- tx mined
- tx sped up
- tx cancelled
- tx failed

Tx data:
- account
- nonce
- hash
- gasLimit
- gasPrice

**Comment by anxolin** [comment]
I think the additional metadata would be possible by using https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets. We've used this, for example to post the network

When we do this one, I would consider to do:
* https://github.com/gnosis/cowswap/issues/618 
* https://github.com/gnosis/cowswap/issues/1059

**Comment by ramirotw** [comment]
Closed by #https://github.com/gnosis/cowswap/pull/1535
