### ISSUE TITLE
Dev: Partial token approval: transaction may hang in 'Open' status after speeding it up

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1409]
Low priority, as the issue is not always reproducible (more like an edge case)
Reproducible on DEV environment. 
Related to #1302

Transaction may hang in 'Open' status after speeding it up. Actually, I'm not sure, but another case that might cause this behavior is last second transaction speeding up. 

**Steps**: 
1. Call Approve token transaction
2. Specify a partial token approval amount
3. Select a Low transaction speed 
4. Run the transaction
5. Speed up the transaction

**AR**:  transaction may hang in 'Open' status after speeding it up
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/89831bb6-8dea-43bb-b664-4930b225bdc8)
Pending transaction from the Cowswap navigates to https://rinkeby.etherscan.io/tx/0x8df07f764af96c611b007723f88d7d0b726076e20014b0a9fb224478d6035860

Transaction log from MM account navigates to  https://rinkeby.etherscan.io/tx/0x47b58f72843ebf3dd17919c34681f958d6c231d9f94e5e131dfe069ca1618713

Btw, clearing the app storage resolves this issue: there is no pending transaction after it. 

**Expected**: transaction is Approved and replaced.

**Comment by ramirotw** [comment]
@elena-zh could you please try to reproduce this on top of https://github.com/gnosis/cowswap/pull/2474 ?

**Comment by elena-zh** [comment]
That is fixed in #2474
