### ISSUE TITLE
Cancelled and speeded up wrap/unwrap transactions hang in 'Open' status

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1410]
I thought all these transactions (wrap/unwrap) had been fixed by #1302, but it appeared that they are still reproducible.
**Tested in DEV environment**

Run wrap/unwrap transaction, then cancel it in the connected wallet. 
The same is when speed up these transactions.
As a result, transaction is cancelled, however it hangs in 'Open' status in the Cowswap. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/083b6389-b7bc-44d0-82af-9534d8ae2d66)

**Wrap transaction:** 
Cowswap refers to: https://rinkeby.etherscan.io/tx/0x6ea4fcc769f76a4ec2599c15b0f0d8eeac3591110982211831b04526f8035ac4
MM wallet refers to: https://rinkeby.etherscan.io/tx/0xff5ab58f691f6abef476f681b00348092a65bfea649807000ad0be3b1f004a89

**Unwrap transaction:** 
Cowswap refers to: https://rinkeby.etherscan.io/tx/0x9045f33a31d960f862c3e8956ed223126076c1682fad83a9739e1ac71c32e44a
MM wallet refers to: https://rinkeby.etherscan.io/tx/0x585b4cc1ea1fb16ca1bb7842df8405e9e77a8ec57f5432e814c18105499ac9a9

**Speeded up transaction:** 
Cowswap refers to: https://rinkeby.etherscan.io/tx/0xde708abf6ee54c876671390624845f66ab3331dbf54417a417444a3028f7d3f8
MM wallet refers to: https://rinkeby.etherscan.io/tx/0x1219eea452cdd27f7d23baeffb8f49a31997fe14db47cf8fd4e1f1d1f1cadbf7
![image](https://user-images.githubusercontent.com/70885163/132533389-61d77fce-cd3d-46aa-b33e-254f601d8931.png)

**ER**: transactions should be cancelled.

**Comment by alfetopito** [comment]
@ramirotw could you check whether this is an edge case from your changes?

Regarding the blocknative api, I can see we are still far off from the limit, so that's not it
![screenshot_2021-09-08_13-38-22](https://user-images.githubusercontent.com/43217/132581834-8f2862e5-5301-45a7-8594-97d9145559f0.png)

**Comment by elena-zh** [comment]
Might be related to #1832

**Comment by ramirotw** [comment]
Will be fixed in #1832
