### ISSUE TITLE
Update metadata doc

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#1412]
# Summary

There are small changes to the affiliate doc, which require changes to https://github.com/gnosis/cowswap/blob/develop/src/custom/utils/metadata.ts#L26-L50

- Set the version fields to 0.1.0
- Remove kind
- Rename inner referrer property to address

Example:

```json
{
  "version": "0.1.0",
  "appCode": "CowSwap",
  "metadata": { 
    "referrer": {
      "version": "0.1.0",
      "address": "0x424a46612794dbb8000194937834250Dc723fFa5"
    }
  }
}
```

**Comment by ramirotw** [comment]
@alfetopito there was already a ticket and PR (https://github.com/gnosis/cowswap/pull/1190) for this that wasn't merged. I'll take care of resolving the conflicts and let the bot merge it

**Comment by alfetopito** [comment]
Ah thanks Ramiro, completely forgot about it :)

I'll close this one as a duplicate
