### ISSUE TITLE
MM asks for permission to connect to Uniswap.

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1421]
**Description**
When selecting a fresh MM account or removing all your connected sites. MM ask you to connect with Cowswap and with Uniswap.

**How to Reproduce**
1. Clear all (or Uniswap and Cowswap related) connected sited from your MM account 
2. Click on Connect Wallet and follow instructions
3. Change network (e.g. Mainnet to xDai)
4. Observe MM icon 
5. Observe pending MM requests

**Expected behavior**
The app should not ask the user to connect with Uniswap

**Screenshots**

https://user-images.githubusercontent.com/34510341/132816358-de7d1545-4c24-4cb3-89e4-cc8683bcfa90.mov

Note, this was recorded in PR 1413, however, this is also present in production. 

**Additional context**
It not only asks you to connect to Uniswap but also to an older PR (1408)

**Comment by MareenG** [comment]
Now it also asks to connect to Sushi

**Comment by elena-zh** [comment]
MM asks to connect to all opened apps with active connections. 
So the issue is on the MM side, not on the Cowswap side.
