### ISSUE TITLE
Nothing is displayed in 'Balance' field when no token balance in connected wallet

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1426]
Reproducible in **Dev** environment

1. Connect to a wallet
2. Select a token in From/To field with 0 balance
3. Verify token balance in the field

**AR**: empty balance (`Balance: AAVE`) 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/badb0b68-9eba-4eba-bd77-020ae7a8c3f1)

**ER**: 0 balance (Balance: **0** AAVE)

**Comment by anxolin** [comment]
@alfetopito @W3stside i tagged this RELEASE, cause this one should be addressed before deploying the `v1.2.0` since it feels important.

**Comment by elena-zh** [comment]
related to #1447
