### ISSUE TITLE
Balances are not detected when switching between ETH/WETH to WETH/ETH

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1428]
**Description**
When switching between wrap and unwrap the prior inserted values or balances are not correctly detected.

**How to Reproduce**
1. Go to cowswap
2. Chose ETH as sell and WETH as buy token
3. Insert value to wrap/unwrap within your balance
4. Click switching arrow

**Expected behavior**
Should detect that the user has enough balance

**Screenshots**

https://user-images.githubusercontent.com/34510341/132846670-3ad07728-3567-4797-b5ab-d6561c6a311b.mov

**Comment by elena-zh** [comment]
I will link #928 issue with the current one: it is not a duplicate, but they might be related.

**Comment by elena-zh** [comment]
The same is for xDAI/WXDAI

**Comment by elena-zh** [comment]
The issue is no longer reproducible. 
I'm closing it.
