### ISSUE TITLE
From token in Fee range throws error (DAI/WBTC on Rinkeby)

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1436]
**Description**
Swapping DAI to WBTC 
When inserting a DAI value close to the fee amount an error is shown 
Error: [big.js] Division by zero
So far only experienced this for DAI/WBTC

**How to Reproduce**
1. Go to https://pr1425--gpswapui.review.gnosisdev.com/#/swap set Network to Rinkeby
2. Dai as from token and WBTC as to token
3. Insert sell amount close to fee

In production the 'Error loading price' is displayed

**Screenshots**
RC v1.2.0: 

https://user-images.githubusercontent.com/34510341/133424726-8e3c06e9-0ef6-49a0-93f5-554a80206798.mov

<img width="1436" alt="Bildschirmfoto 2021-09-15 um 13 08 08" src="https://user-images.githubusercontent.com/34510341/133424736-a2a1993f-0546-4416-adf3-16872ea85c80.png">

Production: 

<img width="1038" alt="Bildschirmfoto 2021-09-15 um 13 25 04" src="https://user-images.githubusercontent.com/34510341/133424899-93ac4c09-593f-4b47-8d88-998743eadab5.png">

**Comment by anxolin** [comment]
The screenshot says `v1.1.2` but the title says `RC-1.2.0`. if it's true that is `1.2.0` @W3stside this is super important to address before releasing the version.

**Comment by MareenG** [comment]
I just checked and it was already present in older versions e.g. if you check the PR of the hotfixes of v 1.1. 
However it seems to be only present if you test directly in the PR. 
In staging and production you get the Error loading price error instead.

**Comment by MareenG** [comment]
solved by #1456
