### ISSUE TITLE
Error when copy-pasting amounts with more decimal amounts than the precission of the token

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#1441]
**Description**
I get an error in the console if i try to sell `231717.20669652` USDC (note usdc has precission of 6 decimals)

As you see in the screenshot, there's no info in the UI. 

![image](https://user-images.githubusercontent.com/2352112/134060374-33447c67-633c-47fc-9315-b61ec544c099.png)

Probably, we should just trim? otherwise, we should inform

What do you think the UI should do in this case?

This issue I believe has some relationship with https://gnosisinc.slack.com/archives/CSGLUC1BN/p1632153396009900

**Comment by elena-zh** [comment]
I have to notice, that the issue is reproducible when add additional zeros to the max decimal part. 
When add numbers, 'Enter an amount' is displayed as the error: reported in #1039

**Comment by anxolin** [comment]
Yes, it seems connected with https://github.com/gnosis/cowswap/issues/1039

Probably, after we address the parsing logic, both things will be solved. Thanks Elena
