### ISSUE TITLE
[v.1.2]Firefox: impossible to create an issue on Github after hard error 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1460]
related to #1447

**Steps:** 

1. simulate a hard error in Firefox
2. Press on the Create an issue on GitHub link

**AR**: user is redirected to the error page
![hard error - navigate to github.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a79f98f4-798a-4aa8-b76f-eeabc9001128)
![ff.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e29f4aec-70fc-4a4e-88be-96ac9939b092)

**ER**: create an issue page should be opened in GitHub

**Note**: might be related to a long error log and be reproducible not only in FF...

**Comment by anxolin** [comment]
approve

**Comment by alfetopito** [comment]
> approve

You approved the issue, not the PR =P
