### ISSUE TITLE
[presign] Gas estimation fail for Gnosis Safe

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#1469]
**Description**
Issue estimating gas in Gnosis Safe

![image](https://user-images.githubusercontent.com/2352112/134545780-6e202f1b-e54b-4356-9f8b-16fb696c14e2.png)

When you try to unwrap WETH i get an error. Possibly is that the RPC method for gas estimation is not implemented.

Steps:
* Connect using Wallet Connect
* Open Gnosis Safe App in Rinkeby, u can use one safe with 1 signer only for this
* Open app in gnosis safe: “Wallet Connect” (should be near the bottom of all the apps)
* Take a screenshot of the QR shown in CowSwap, paste in Gnosis Safe Web to connect
* Try to Unwrap Weth: sell WETH for ETH

Use branch `presign/enhanced-safe-transactions` as a base

**Comment by nenadV91** [comment]
Created a new issue on ethers.js https://github.com/ethers-io/ethers.js/issues/2164 for this
