### ISSUE TITLE
Blur background on all but Swap pages

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#1485]
Minor thing i missed:
- The profile container misses this setting `backdrop-filter: blur(50px);`

Otherwise OK to go as is.

_Originally posted by @biocom in https://github.com/gnosis/cowswap/issues/1376#issuecomment-928944645_

**Comment by elena-zh** [comment]
@maria-vslvn , is this fixed? If yes, pls, close the issue

**Comment by maria-vslvn** [comment]
@alfetopito @elena-zh please check https://github.com/gnosis/cowswap/pull/1829
