### ISSUE TITLE
Bar with action buttons is shifted when scroll the side bar to the bottom

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1489]
Related to #1395

Bar with action buttons is shifted when scroll the side bar to the bottom (related to this pr only): 
![recent shifted](https://user-images.githubusercontent.com/70885163/135083714-b3076d40-e1ef-4fbe-a27b-cdf4bd792a6d.jpg)

In FF browser the bar looks too transparent --> seems like text overlaps order details: 
![image](https://user-images.githubusercontent.com/70885163/135249363-717613f2-6259-4d3c-8e62-78ec08cc45a7.png)

**Comment by alfetopito** [comment]
FYI, I can reproduce this as well on Prod with Firefox
![screenshot_2021-09-29_10-01-07](https://user-images.githubusercontent.com/43217/135315376-6d4d25ff-74c2-4c31-904e-fe2732766517.png)

And with Chrome too
![screenshot_2021-09-29_10-04-10](https://user-images.githubusercontent.com/43217/135315763-d99f0cba-8fd8-4032-98d2-97f5d25bd939.png)

**Comment by elena-zh** [comment]
Closed as Side bar is removed in v1.5.0
