### ISSUE TITLE
[mobile] -increase clickable area of Etherscan link in side bar 

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1509]
**Description**
The clickable area of the Etherscan/Blockscout link in the sidebar is limited to the text itself.
Espec. for mobile devices it could be beneficial to increase the area to the full region. 

<img width="496" alt="Bildschirmfoto 2021-10-05 um 09 32 09" src="https://user-images.githubusercontent.com/34510341/135979851-c61d9401-69d4-4c12-ab1f-12fb9a47e61f.png">
<img width="491" alt="Bildschirmfoto 2021-10-05 um 09 32 19" src="https://user-images.githubusercontent.com/34510341/135979866-ae52cb3e-94b7-459b-9506-3276f565618c.png">

**Comment by alfetopito** [comment]
The next iteration @biocom is working on conflicts with this suggestion, as there will be more links in that row.
See the WIP on https://github.com/gnosis/cowswap/pull/1513

**Comment by MareenG** [comment]
Yes, will be redundant with the new changes. Closing it
