### ISSUE TITLE
Profile: warn a user that stats is available in the Mainnet only

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1512]
Related to #1506
Currently, nothing is displayed in the stats when a user is connected to Rinkeby/XDAI, as the stats is available in the Mainnet only. 
It would be nice to show a warning to a user about it. 
![warning.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/273e750b-367c-4ca9-b4e5-25bbc0a09772)

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1714
