### ISSUE TITLE
Presign - include FAQ 

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1521]
Please ignore if this is already planned. 

I feel we should add an additional FAQ section for interacting with the safe or SC wallets. The main reason here is that the user now has pay gas for signing the transaction. This should be explained somewhere a bit more. 
Users should know this when using a SC wallet but that is not always the case.

It is mentioned in one of the tooltips but should be highlighted a bit more.

**Comment by alfetopito** [comment]
Great idea, we do not yet have that AFAICT

cc @anxolin @avsavsavs
