### ISSUE TITLE
Presign- you can now trade Token XY message appears for already approved tokens

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1522]
**Description**
Every now and then the successful token approval appears out of nowhere when selecting a token. 

**How to Reproduce**
1. Go to https://pr1515--gpswapui.review.gnosisdev.com/#/swap or https://pr1513--gpswapui.review.gnosisdev.com/#/swap
2. Chose a from token you already approved
3. Chose a to token
4. In some cases you can see the token approval message that is displayed after approving tokens

**Expected behavior**
Should not be visible when selecting a prior approved token.

**Screenshots**
![Bildschirmfoto 2021-10-06 um 14 39 11](https://user-images.githubusercontent.com/34510341/136204819-56eed7b1-f1ec-437c-95f2-6dbc9d3ba859.png)

**Additional context**
So far I only experienced this for the PR mentioned above.

**Comment by elena-zh** [comment]
I faced this issue before #1233

**Comment by MareenG** [comment]
Ok closing it then
