### ISSUE TITLE
[Uni merge] Mobile: 'Connect' button is cropped in the app header + menu is shifted

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1539]
Originally reported in https://github.com/gnosis/cowswap/issues/1501#issuecomment-937821657 (case 11)

in iPhone Android devices: 'Connect' button is cropped
![image](https://user-images.githubusercontent.com/70885163/136398321-a6e36dc6-5640-4b7a-9012-cbaa643d5232.png)

Also, menu seems to be shifted
![image](https://user-images.githubusercontent.com/70885163/136401382-7045edae-5368-4b95-bb1e-9d4ac06ddd31.png)

**Expected**: show full button OR remove 'wallet' from its name in order not to show a cropped button

**Comment by biocom** [comment]
Addressed in https://github.com/gnosis/cowswap/pull/1565
