### ISSUE TITLE
[Affiliate] user is not warned about an invalid referral link

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1570]
Originally reported in https://github.com/gnosis/cowswap/issues/1405#issuecomment-940154401

user is not warned about an invalid referral link: 
![image](https://user-images.githubusercontent.com/70885163/136820612-0efae684-2b13-4c44-9408-3213c6b64eef.png)

**Expected**: validate the link to have a correct eth address as a referral

**Comment by elena-zh** [comment]
hey @alfetopito , I have just realized that we can have ENS names instead of wallet addresses in the referral URLs. 
So, my question is: will the app be able to validate this when sharing a referral link with an ENS name in the URL?
If yes, we should include ENS name validation into the current task along with wallet address validation rules.

**Comment by alfetopito** [comment]
Great idea Elena!
I've created another task to address is https://github.com/gnosis/cowswap/issues/1682 and added to the Epic https://github.com/gnosis/cowswap/issues/1575 as good to have.
Not a blocker for release but would be a great addition

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1714
