### ISSUE TITLE
[Affiliate] Banners styles look different 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1571]
Originally reported in https://github.com/gnosis/cowswap/issues/1405#issuecomment-938750268

Banners styles look different. May be we should show these banners one by one? Or, at least, apply a similar design for both?
![display one by one](https://user-images.githubusercontent.com/70885163/136586445-7f14f505-b6c1-4dad-82f7-5ce1c900ea7f.jpg)

**Comment by elena-zh** [comment]
Hey @alongoni , could you please clarify what colors for banner will be for: 
 - positive message (as in your screenshot) for the light mode
 - negative message (something like 'you already have trades' or 'the program is eligible in the Mainnet only') for the light and dark modes?

**Comment by alongoni** [comment]
**Light mode**

- Positive message:
![CowSwap - Account page (affiliate-v1 8 - desktop](https://user-images.githubusercontent.com/622217/137992337-47df67cd-ff6c-40f2-ac03-9f46b9f76f98.png)
- Negative message:
![CowSwap - Account page (affiliate-v1 8 - desktop-1](https://user-images.githubusercontent.com/622217/137992731-efc8584a-f146-4bef-9464-599fa53c4d42.png)

**Dark mode**
- Positive message:
![CowSwap - Account page (affiliate-v1 8 - desktop - dark mode](https://user-images.githubusercontent.com/622217/137992443-0e1edb34-e0b6-4796-b0f7-a11b70f2af6f.png)
- Negative message:
![CowSwap - Account page (affiliate-v1 8 - desktop - dark mode-1](https://user-images.githubusercontent.com/622217/137992438-d2af1271-b76a-4468-9470-3e61a0ab97d2.png)


cc @elena-zh @biocom @alfetopito

**Comment by alongoni** [comment]
Hey @biocom, I've made this draft PR that you can test [here](https://pr1703--gpswapui.review.gnosisdev.com/). There are a couple of options that I was thinking with Eamiro and Henry about the position and width of the `<AffiliateStatusCheck />` component. 

A) Set the component width to 50% and looks like this (as in the draft PR):
![image](https://user-images.githubusercontent.com/622217/139502320-eb15899e-1617-4454-9aa4-d7894e9b64e1.png)
![image](https://user-images.githubusercontent.com/622217/139502350-b81adac5-1eeb-4515-93f6-ff703f8d4230.png)

B) Another option, if we want to match the `<AffiliateStatusCheck />` component width with the Swap / About / Profile container width, we need to add this component in each page. And if we add a new page we need to add the component too. 

It will look like this:
![image](https://user-images.githubusercontent.com/622217/139502852-62b46e48-a00b-4025-ac4d-c843d75bfb31.png)
![image](https://user-images.githubusercontent.com/622217/139502922-233e36eb-bd06-4e19-8669-272d4326cabb.png)

WDYT?

cc @ramirotw @henrypalacios @elena-zh

**Comment by henrypalacios** [comment]
Considering what @elena-zh mentions in the diagram above.
>In all other cases the banners are displayed on the exchange page/all over the app until a user closes >them/the affiliate program status is changed.

Option A for me would be the most appropriate.

But maybe we can define it with @biocom

**Comment by elena-zh** [comment]
Hey @alongoni , option A looks better to me. 
However, I'd moved the banner up a bit
![image](https://user-images.githubusercontent.com/70885163/139659346-08da00bf-89d9-4642-9939-03383c999661.png)

Also, I wonder how these banners will be displayed in a mobile/tablet views?

**Comment by alongoni** [comment]
> Hey @alongoni , option A looks better to me. However, I'd move the banner up a bit ![image](https://user-images.githubusercontent.com/70885163/139659346-08da00bf-89d9-4642-9939-03383c999661.png)
> 
> Also, I wonder how these banners will be displayed in a mobile/tablet views?

Thanks @elena-zh, I've fixed in the PR #1703

**Comment by biocom** [comment]
@alongoni Had just reviewed https://github.com/gnosis/cowswap/pull/1703 and then I saw this issue. I think you already made the suggestion I tried to make :)

I think you suggestion B is what I'd go with. We could make it a more 'generic' purpose component 'Page alert box' or something. I can see other scenarios where we want to show a message similar to the affiliate one.

**Comment by alongoni** [comment]
Closed by #1703
