### ISSUE TITLE
[Affiliate] 'You are following your own link...' banner disappears after the app reload

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1572]
Originally reported in https://github.com/gnosis/cowswap/issues/1405#issuecomment-938750268

'You are following your own link...' banner disappears after the app reload when press on the CowSwap logo. 
https://watch.screencastify.com/v/Qc4G55L7HlO2FcCvY6RV

I think, it would be good to keep it displayed until a user closes it

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1714
