### ISSUE TITLE
[Affiliate] Info banners do not appear/are not removed when I change accounts in the connected wallet

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1573]
Originally reported in https://github.com/gnosis/cowswap/issues/1405#issuecomment-938750268

Banners do not appear/are not removed when I change accounts in the connected wallet.
I mean: when I follow my own link, I see the warning banner. But when I change an account in the connected wallet to another one, I still see this banner. Or vice versa: I follow a referral link as a new user, then change the MM account to get 'You are following your own link...' banner, but it does not appear.
https://watch.screencastify.com/v/rWCrXDwpANMi9y9VQ38o

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1719
