### ISSUE TITLE
[1.5.0]Mobile: toast notification is displayed above the page and it is Impossible to close 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1609]
Reported in https://github.com/gnosis/cowswap/pull/1552#issuecomment-942464073

In the latest release it has become impossible to close a toast notification in a mobile view. 
Moreover, it is displayed above the page and info banners
![image](https://user-images.githubusercontent.com/70885163/139433852-ea6a0175-0fec-45cf-b440-ef173006128e.png)

![cant close](https://user-images.githubusercontent.com/70885163/137172507-bf7e911a-ca16-41e6-a0cc-22848c748b29.jpg)

**Expected**: it should be possible to close a toast notification

**Comment by elena-zh** [comment]
UPD: 'View on Etherscan' link is not clickable on these notifications either

**Comment by elena-zh** [comment]
I have got the next issue: I see a toast notification in the app, and I can't close it. 
Moreover, it appears again and again, and my wallet is disconnected

https://user-images.githubusercontent.com/70885163/141974100-f7f70f65-9e12-4c03-90b6-49da044b1c29.mp4

**Comment by biocom** [comment]
Fixing it here https://github.com/gnosis/cowswap/pull/1861
