### ISSUE TITLE
Warning for orders that are unfillable

### ISSUE THREAD

**Issue by W3stside** [gnosis/cowswap#162]
(price moved beyond slippage)
AFTER confirmation modal and price changes, maybe show warning in "Pending" order history

Confirmation modal will warn user when price changes before submitting, but once you send that order nothing will warn the user if the price changes after submitting and that it may not fill.

Could add a warning to the "pending" order notification in the toast or in the History Transactions comp

When cancellation is possible users can then leverage that option as to not have failing tx.

**Comment by anxolin** [comment]
Maybe we can simplify the name and description if I understand this issue, I what we discussed in the challenge of today

Basically that is nice to know when the price moves beyond your slippage, so you can (well, when implemented) cancel the orders. When this happens, it's very unlikely that the trade is executed before expiration. It can happen if the price goes up again. 

In any case, it's nice to inform the user about this. 

In Uni, when it happens, it reverts. In our case, it should show a message and ask the user if he wants to cancel the order

**Comment by anxolin** [comment]
@biocom maybe we can make a wireframe proposal for this
