### ISSUE TITLE
[v.1.3.0] Token approval message is displayed when switch networks

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1631]
Related to #1594
1. Approve WETH token in Rinkeby
2. Switch to XDAI
3. Select WXDAI in the From field

**AR**: Token approval message is displayed
![approve.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f2a0c44c-937e-4e0a-934b-6041fc3ca14f)
Moreover it appears when switch accounts
![image](https://user-images.githubusercontent.com/70885163/137477414-f69693e4-f8e7-414e-986a-665d326ab5b7.png)

**ER**: No token approval message from another network

**Comment by W3stside** [comment]
hmm i followed your steps exactly but cannot reprod in #1648 

Can you try it again and let me know if still persists?
