### ISSUE TITLE
[v.1.3.0]  0 is missing in the ETH balance in the header

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1649]
Related to #1594

0 is missing in the ETH balance in the header when connected to an account with 0 ETH balance
![0 eth.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/bac15ace-2350-45bb-a4ac-c349d7ff8bc6)

**Comment by W3stside** [comment]
#1649 is latest, i tagged the wrong version of the release branch in my comment above (fixed)
