### ISSUE TITLE
[v1.3.0] Network indicators (dots) are not placed in 1 vertical line

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1658]
Originally reported in https://github.com/gnosis/cowswap/issues/1638#pullrequestreview-781761485 : case 3
Network indicators (dots) are not placed in 1 vertical line. See the image: 
![image](https://user-images.githubusercontent.com/70885163/137741244-448ce9c2-76ce-429f-97fc-130a6f6b5700.png)

**Expected**: all dots should be placed in 1 line vertically

**Comment by W3stside** [comment]
aligned in #1594
