### ISSUE TITLE
[Rinkeby] USDT token has a wrong price 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1676]
I found a great mismatch in prices displayed in the Cowswap for the [USDT token ](https://rinkeby.etherscan.io/token/0xd9ba894e0097f8cc2bbc9d24d308b98e36dc6d02) and in the Explorer. 
![usdt](https://user-images.githubusercontent.com/70885163/137894824-305fd089-ee31-4863-98b4-25d0051296c1.jpg)

Order details in the Explorer
 https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x2b10c4f99535c4fa7800e5a7bd366280c6a24cbf83e5278c5fae5f3998116ca6ff714b8b0e2700303ec912bd40496c3997ceea2b616ea078

Additional details: https://github.com/gnosis/gp-ui/pull/782#issuecomment-948008822

**Comment by alfetopito** [comment]
I believe this is due to how the rinkeby token list implements the USDT token versus the deployed token version.
Probably a won't fix
