### ISSUE TITLE
Different colors for 'Connect Wallet' and 'Connect to a wallet' buttons in active/hovered states

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1677]
I assume that colors should be the same for 'Connect Wallet' and 'Connect to a wallet' buttons. 
Currently, they are different. 

**Hovered state:** 
![hovered.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a952cde7-ddbe-4d67-8b93-7c5b874d08f7)
![hover light.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/45e51687-4c88-4e1a-8aa1-ad7700a36c4c)

**Active state:** 
![active lignt.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/083d363f-3e17-49d0-a7fc-e79440381919)
![active state.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3e0007d4-1dc1-4755-963f-b398708de1e2)

**Comment by alfetopito** [comment]
I don't really know why that is the case.
Would need to wait for @biocom 's  input on the reasoning
