### ISSUE TITLE
[Affiliate] FAQ

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#1683]
# Summary

Add FAQ entry regarding affiliate program/profile page

First step is to define the text based on some/all topics below.
Second step is to add this to the UI

## Topics to cover
* What is the Profile page
* In which networks it's available
* What are the rewards for sharing the referral link
* What are the rewards for following the referral link
* Who can share
* Who can follow
* What is needed to qualify

Doc with proposed content https://docs.google.com/document/d/1BC66i33FT3eAK3o3B01uM7xDha9fJ1pvNN5TuBBzwCA/edit?usp=sharing

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1691
