### ISSUE TITLE
[1.5.0] Firefox: activity modal has a square right corners 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1688]
Related to the latest PRs with pre-sign feature (#1639, #1684, #1652, etc.)
 Originally reported in https://github.com/gnosis/cowswap/pull/1639#issuecomment-949644668 (case 5)

Activity modal looks weird in FF when scroll presents there. 
![modal look like ff](https://user-images.githubusercontent.com/70885163/138463997-a7a1f8c2-9911-418f-84bd-73ac9072a193.jpg)

**Expected**: boarder radius should be the same for all corners in the modal

**Comment by elena-zh** [comment]
Besides, it would be nice to adjust network indicator icon in the modal 
![image](https://user-images.githubusercontent.com/70885163/140533576-ffd9c69d-f5bf-4364-8a11-9eec278214ba.png)

**Comment by biocom** [comment]
@elena-zh Unfortunately, using a native CSS solution only, this is not supporte by Firefox. Specifically the `border-radius` aspect. The only other way is to use a JS library or some other hacky CSS ways (clipping perhaps). The only properties for now natively supported with CSS on Firefox for a scrollbar:
- scrollbar-color
- scrollbar-width

(https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars)

I did apply these properties now in PR https://github.com/gnosis/cowswap/pull/1848 to try to improve the UI here.

**Comment by elena-zh** [comment]
Hey @biocom , thank you for the notes. 
I retested changes in #1848, added notes [there ](https://github.com/gnosis/cowswap/issues/1848#issuecomment-970246297)
