### ISSUE TITLE
[Profile] Add a message to tooltips/FAQ section about stats from Blockchain

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1705]
Related to #1575 and #1681

Discussed in https://altoros.slack.com/archives/C026K00F676/p1635343412032800

Currently, stats comes from the blockchain and there is no separation for orders for Dev and Prod servers. 
It would be nice to add a message to tooltips/FAQ section about this.

**Comment by alongoni** [comment]
Closed by #1721
