### ISSUE TITLE
[Affiliate] Show a user info about affiliate link owner

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1708]
Currently, we do not indicate which affiliate link user is following and under which link the 1st trade was done. 

Even if we follow the same link once again, we will see the common message 'Invalid affiliate code: The currently connected wallet has traded before or is already part of the affiliate program.'

So it would be nice to add an info about affiliate link user followed into the Profile details page. 
Also, show a different banner to a user when he/she follow the same link after a successful trade. 
Something like 'Affiliate program: You have already traded with this affiliate code' or so

**Comment by alfetopito** [comment]
I think the first step is to display in the profile page the address of the referrer (the one whose link you have followed) in your profile page, if any.

**Comment by alongoni** [comment]
Maybe we can add a: "Referred by:`address`" info.
I've made the design taking in account the last changes added by @matextrem in PR #1935
Option 1: referral info at the botom. 
![referrallink2](https://user-images.githubusercontent.com/622217/146207853-7840ab0f-9632-4377-90de-1ce4fb7c9f96.png)
Option 1: referral info at the top, beside the link to the order explorer. 
![referrallink1](https://user-images.githubusercontent.com/622217/146207838-850dff4b-c431-4285-b92f-c3676da2f069.png)

**Comment by elena-zh** [comment]
As another option, we could redesign 'Your referral URL section: 
 - Rename it to 'Referral program' or so
 - Add a field 'Your referral URL' with a referral link and copy icon
 - Add a field 'You referred by' with an address/ENS name info
![image](https://user-images.githubusercontent.com/70885163/146210281-235294e7-c3d4-41e4-ace8-861da0aa934d.png)

@alfetopito , @alongoni , WDYT?

**Comment by alfetopito** [comment]
I like Agustin's first proposal, with the address at the bottom right.

@biocom @anxolin thoughts?

**Comment by biocom** [comment]
I would go with this approach: 

<img width="564" alt="Screen Shot 2021-12-16 at 15 59 05" src="https://user-images.githubusercontent.com/31534717/146395328-e4eed29a-6cf1-4703-ac88-d5d7cca75aa1.png">

**Comment by anxolin** [comment]
Im also in favour of option 2. Is this something that is common to show? like the user who brought you in? I normally haven't seen this. Is this something we feel strong it adds value?
