### ISSUE TITLE
[Affiliate] Referral URL was not added to the trade after navigating between pages

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1717]
Referral address is missing when navigate across pages
https://watch.screencastify.com/v/oYfeX1YbCG8IPkCM9xQQ

I copied and followed a referral URL https://pr1681--gpswapui.review.gnosisdev.com/#/?referral=0x50885525Ee3aD9C2f074606e282BC5D8ec9B5e7B

I connected this account: 0xFa433e5B2B5Ab9440039b4dd23ED2D3e151A8AbD

Then I navigated across pages: went to About/Profile, then returned to the Swap page and placed an order

The order was filled https://protocol-explorer.dev.gnosisdev.com/address/0xfa433e5b2b5ab9440039b4dd23ed2d3e151a8abd

But there is no info about a referral trade  for the owner: 
https://protocol-mainnet.dev.gnosisdev.com/api/v1/profile/0x50885525Ee3aD9C2f074606e282BC5D8ec9B5e7B 

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/88da99e3-b2a9-4438-9428-c54dfbed5734)

**Expected**: URL should remain when an order is placed

**Comment by josojo** [comment]
@elena-zh I changed the backend: we are now pulling the ipfs from the new api. Could you test it one more time?

**Comment by elena-zh** [comment]
@josojo , I will retest thoroughly a bit later, but as the result of a smoke test, I was able to see missing referral data for the account I reported in this issue. 
![image](https://user-images.githubusercontent.com/70885163/139826250-e28ecf83-e44f-4f23-b219-91a4a941f62a.png)

Thanks!
