### ISSUE TITLE
[Affiliate]: Remember decision when banner is dismissed

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1730]
Related to #1681, #1719, #1575

Originally reported in https://github.com/gnosis/cowswap/issues/1719#pullrequestreview-792468677

> One thing (that was not part of the requirements) but might be good to have:
> Remember decision when banner is dismissed, and only show when status changes (different account)

**To reproduce:** 
1. Connect a wallet in the Mainnet with the app
2. Open profile page and copy a referral link
3. Paste the link into the browser
4. Close the info banner
5. Refresh the page

**AR**: banner appears again

**ER**: banner should not appear when it is closed for the current account
Need to show banner again when switch to another account

**Comment by maria-vslvn** [comment]
@alfetopito @ramirotw @elena-zh about this issue, i have a solution. i prepared it (i created a custom small hook, that sets a value to the localstorage, that becomes true on the banner closing event), but i'm not sure i know exactly when we should see the banner and whether my solution is suitable and acceptable. i can push or show what have i created

**Comment by elena-zh** [comment]
@maria-vslvn , will it show a banner again when we switch between accounts?

**Comment by maria-vslvn** [comment]
@elena-zh it did so

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1808
