### ISSUE TITLE
Cannot place an order in BARN

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1736]
Cannot place an order in BARN
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d3d77a83-9bfd-4ea8-a1d2-1ccd532db848)

**Expected**: user is able to place an order in Barn

**Comment by alfetopito** [comment]
FYI, Ramiro pushed a fix for this on https://github.com/gnosis/cowswap/pull/1743

Not related to `signatures` but instead with affiliate data on redux state.

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1743
