### ISSUE TITLE
[Profile] implement boarder radius for info banner

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1738]
Related to #1575 and #1681

Reported and discussed in https://github.com/gnosis/cowswap/issues/1714#issuecomment-953965125

I'm agree! E.g.: we can add `border-radius: 14px`
![image](https://user-images.githubusercontent.com/622217/139288908-daf846eb-155a-436b-9207-83db169217d8.png)

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1755
