### ISSUE TITLE
Connect Wallet button has a light-orange boarder hovered/active states

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1746]
Originally reported in https://github.com/gnosis/cowswap/pull/1673#issuecomment-954781967

 'Connect button' has orange boarder color in hovered/active states
 ![connect wallet](https://user-images.githubusercontent.com/70885163/139428861-bc4efef1-598f-48ef-8d44-aa0a91ddeb80.jpg)

A proposal how to fix is here
https://github.com/gnosis/cowswap/pull/1673#issuecomment-954903219

**Comment by maria-vslvn** [comment]
@alongoni @elena-zh i could tke this issue, also could you please note or show the right behavior?

**Comment by elena-zh** [comment]
Closed . Decision is in https://github.com/gnosis/cowswap/issues/1673#issuecomment-957168379

**Comment by maria-vslvn** [comment]
@alfetopito @ramirotw @elena-zh about this issue, i have a solution. i prepared it (i created a custom small hook, that sets a value to the localstorage, that becomes true on the banner closing event), but i'm not sure i know exactly when we should see the banner and whether my solution is suitable and acceptable. i can push or show what have i created
