### ISSUE TITLE
[Affiliate] Delete an info about an invalid referral code from the localstorage

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1749]
Related to #1714 , #1575 , #1681

Currently, when I follow a link with an invalid referral code, I get the error banner. 
I can close this, but it will appear again after a page reload as the info about an invalid code is stored in the localstorage. 
It would be nice remove an info about an invalid code from the local storage, I think
https://watch.screencastify.com/v/NDxfcWkAkV9V6uYgswgf

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1754
