### ISSUE TITLE
[Profile] Mobile: No margin between profile page elements and app header when screen width < 325 px

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1751]
open profile page and specify a screen width to be < 325 px

**AR**: No margin between profile page elements and app header 
![no margin.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c3603b28-b8c4-4230-9eaa-1dd4c57540ca)

**ER**: margin should present: see the Swap page
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/7db09636-921d-43fb-aa17-3bd15b40ca33)

**Comment by alongoni** [comment]
Closed by #1703
