### ISSUE TITLE
[MEV Slicer] Icon for the game is incorrect on the Trade confirmation modal 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1764]
Place an order
Verify the icon on the 'Play Cow Slicer game' 

**AR**: icon for the Cow Runner
![change icon.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/421884f6-1a37-4155-9830-063d590d6d44)

**ER**: icon should be for the MEV Slicer game
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/80c2671b-845d-4ca8-b04b-58b257cda744)

**Comment by alfetopito** [comment]
I would suggest to update this with either:

1. `Play a game!`
    1. leads to a page with both games OR
    2. randomly opens one game

OR

2. Add a button for each game

`Play the Cow Slicer Gamer`
`Play the Cow Runner Gamer`

**Comment by elena-zh** [comment]
According to the discussion in https://altoros.slack.com/archives/CSGLUC1BN/p1637180786130400 , it would be nice to return `Cow Runner Game` to the modal

> Also, should we make the CowSwap Runner Game the default again after trade execution? It keeps you on the CowSwap site, whereas the slicer opens a new tap.


> In addition, my instinct is that it makes more sense to users who don't know the full Cowswap/MEV narrative. One user was pretty confused by the slicer game this week. (It starts off with a message like "the cow doesn't run from sandwiches anymore" which doesn't make sense if you haven't played the runner game.)

**Comment by elena-zh** [comment]
I still think it would be great to fix this issue.

**Comment by anxolin** [comment]
cc/ @alfetopito

**Comment by alfetopito** [comment]
Indeed, we just got a request to have the Cow runner game be default again.

@alongoni can you add this to your queue?

Not high priority, no need to stop anything in progress, just a small task to squeeze in when you have the chance.
