### ISSUE TITLE
 Tool tips network switcher

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1771]
**Description**
If your wallet does not support a network switch we display tooltips. I feel the display is not ideal especially not for mobile. 
Eventhough they have different colours it feels like they are both clickable. 
On Desktop the changed mouse icon indicated that the **!** is not clickable but on mobile this is not obvious. 
![IMG_92F9786197B5-1](https://user-images.githubusercontent.com/34510341/140277598-39d32f66-22c1-4643-ab0d-28dc2bae1671.jpeg)

**How to Reproduce**
1. Open cowswap in mobile browser
2. Connect with MM via Wallet connect
3. Open network switcher
4. See toolips

**Suggestion**
It might be good to remove the ! tooltip and instead gray out the name and icon of the network.

**Comment by elena-zh** [comment]
Based on the changes in #1982 , network switcher won't be opened when a wallet does not support several networks. 
The issue is no longer relevant.
