### ISSUE TITLE
[Affiliate] Add 'later' to several error messages

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1776]
Related to #1575, #1675

It would be nice to add  'later' to the phrase 'Please try again.' into several error messages. 
In particular: 

 - Affiliate program error: There was an error validating existing trades. Please try again **later**.

 - Affiliate program error: There was an error while uploading the referral document to IPFS. Please try again **later**.

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1691
