### ISSUE TITLE
Add spacing in fee overview

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1779]
**Description**
If a token amount is entered with 9 or more digits the fee break down shows quite a cramped layout

<img width="209" alt="Bildschirmfoto 2021-11-04 um 13 27 05" src="https://user-images.githubusercontent.com/34510341/140313926-7d81d3d9-0ae7-413d-9551-6625e777f1b0.png">

**Expected behavior**
Ad an additional spacer between before fee and the value

**Comment by MareenG** [comment]
Actually it is also the same for values with less digits
<img width="186" alt="Bildschirmfoto 2021-11-04 um 13 34 45" src="https://user-images.githubusercontent.com/34510341/140314331-39c8b1db-ba15-43a9-a4c9-8a67475610e1.png">

**Comment by MareenG** [comment]
@michelbio that was the small spacing issue I was referring to.

**Comment by elena-zh** [comment]
The issue is not reproducible in the latest release deployed to prod environment
![image](https://user-images.githubusercontent.com/70885163/141446363-c2f8d2b9-03bd-46f3-b1ad-500a92a7f79a.png)
