### ISSUE TITLE
[Recent Orders] - Orders displayed in the wrong network

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1785]
**Description**
First reported in PR #1639 
https://github.com/gnosis/cowswap/pull/1639#issuecomment-949576661
https://github.com/gnosis/cowswap/pull/1639#issuecomment-949589087
Also appeared in #1783 

Some orders of other network are displayed in the activities overview. 
Eg. Xdai trades in Mainnet or Rinkeby trades when selecting xDai

First it only happened when using FF or Brave now also for Chrome

**How to Reproduce**
1. Go to  PRs 1639 or 1783  and open cowswap
2. Perform trades in different networks
3. Open trading activites and cross check the trades
4. trades are displayed in wrong network

**Expected behavior**
xDai trades only shown when xDai selected 
Mainnet for Mainnet 
Rinkeby for Rinkeby

**Screenshots**

<img width="836" alt="Bildschirmfoto 2021-11-05 um 10 35 13" src="https://user-images.githubusercontent.com/34510341/140494865-c9fa90d7-2076-437f-bf53-f48e08061b67.png">
<img width="845" alt="Bildschirmfoto 2021-11-05 um 11 03 56" src="https://user-images.githubusercontent.com/34510341/140494858-f4032cc8-a3e1-42cc-a2e9-c43eaed75a1a.png">
<img width="1362" alt="Bildschirmfoto 2021-11-05 um 10 33 53" src="https://user-images.githubusercontent.com/34510341/140494869-d2275bc9-a630-4f16-a57d-243edbb195a6.png">
<img width="1361" alt="Bildschirmfoto 2021-11-05 um 10 33 28" src="https://user-images.githubusercontent.com/34510341/140494874-85c70ebd-eae7-49b3-8855-9789d9703685.png">

**Comment by MareenG** [comment]
Also it looks like it doesn't properly update the recent activities of the wrong network:
<img width="1149" alt="Bildschirmfoto 2021-11-05 um 11 40 03" src="https://user-images.githubusercontent.com/34510341/140498609-cff4dbe9-7479-4b0c-970e-3f8e1dd84097.png">

**Comment by MareenG** [comment]
Deleting` redux_localstorage_simple_orders` cleared the order activites and the orders of the wrong network where removed

**Comment by elena-zh** [comment]
It seems that I faced a similar issue a couple of weeks ago #1618 
Anyways, let these issues be linked.

**Comment by alfetopito** [comment]
To be clear, is this happening ONLY on my PR where orders are loaded from api or ALSO regular loading (stored in the browser)?

**Comment by MareenG** [comment]
@alfetopito The orders displayed in the wrong network ONLY happen in your PR (#1639) and the one from Anxo (#1783)

That orders might not update properly happened to Elena before as described in #1618

**Comment by alfetopito** [comment]
Hmm, then this is more general and not necessarily related to account separation nor orders from API, as reported by Elena on #1618 
At least we know this hasn't been introduced with any of those changes.

I suspect this might be there for awhile and it should be reproducible on develop / 1.5 branches, if introduced with the SC integration, or even be on prod.

Need more debugging to find out what's causing it

**Comment by elena-zh** [comment]
No longer reperoducible.
