### ISSUE TITLE
Give a name to the file when upload IPFS

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1803]
Related to #1575 

Originally reported in https://altoros.slack.com/archives/C026K00F676/p1636449598155200

when we upload to IPFS we could give a name to the file to make sure we know later what it is. I.e. `appData-affiliate`

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/76611bb7-921c-4bb6-8f85-b7c9b1b7ffb5)

**Comment by anxolin** [comment]
Thanks so much for tracking it! 🙏
