### ISSUE TITLE
[Affiliate] Banners do not appear after closing them

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1806]
it is  a task as a waterflow from the #1756 issue. 

In the #1756 PR once a user closes an affiliate banner, it will never appear when: 
 - change an account in the connected wallet
 - change an affiliate link 

Besides, I see a lot of ` state.affiliate.isNotificationClosed ` messages in the console in that PR
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d837af6d-091d-416f-8c70-9d4960130bd9)

**Expected:** 
1. remember banner's style state for an account (closed/opened)
2. show/hide a banner when change an account when switch between accounts
3. show a banner again to a user who follows another affiliate link

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1808
