### ISSUE TITLE
[Affiliate] 'Closed' banner for an account may appear on accounts switching

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1812]
Related to #1808

**Steps:** 

1. Connect a wallet and copy an affiliate link into the URL
2. The main Affiliate banner should be displayed
3. Close the banner by clicking the X
4. Switch to another account --> banner appears
5. Switch back to the 1st account 

**AR**: closed banner is displayed. But disappears when navigate to another page/reload the page

**ER**: banner should not be displayed

**Comment by elena-zh** [comment]
Additional case https://github.com/gnosis/cowswap/issues/1808#issuecomment-965121757

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1875
