### ISSUE TITLE
[1.4.2] FAQ: move FAQ footer to 'Stats from Blockchain' section

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1815]
Related to #1721,#1575

1.  open FAQ https://pr1721--gpswapui.review.gnosisdev.com/#/faq#why-do-i-see-more-trades
2. Scroll down to the 'Stats from Blockchain' section

**AR**: FAQ footer is displayed above the section
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/04017edf-c9af-4cc7-a672-87371c9a5c14)

**ER**: move FAQ footer to 'Stats from Blockchain' section

**Comment by elena-zh** [comment]
In addition, it would be nice to add a space between on and  https://barn.cowswap.exchange
![image](https://user-images.githubusercontent.com/70885163/141266754-6d8aef1b-fa86-405d-a7c8-fa87bbc548aa.png)

**Comment by alongoni** [comment]
Hey @elena-zh I thinks it's a cache problem. Please can you try again (with a hard refresh or using incognito mode).
![image](https://user-images.githubusercontent.com/622217/141296184-91051356-2885-40fd-a907-26a36b036265.png)
On barn looks fine too. Thanks!

**Comment by elena-zh** [comment]
@alongoni , 
Indeed. Sorry about that 😟
