### ISSUE TITLE
[Profile] Do not show tooltip for Total trades when no trades

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1816]
Related to #1721, #1575

Currently, I see the tooltip that I can see 'more trades..' when I have a dash instead of the value in the Total trades section. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f7e9e44c-33d8-4f09-8bf3-ee8a9f8c3283)

It would be nice not to show it when: 
 - a user is not connected 
 - a user is not connected to the Mainnet
 - totally new user without trades

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1824
