### ISSUE TITLE
[FAQ - affiliate]: some links are not underlined

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1828]
1. Open FAQ
2. Scroll down to the 'Why do I see more trades and referrals in my profile page than I actually see in the activity list?' question

**AR**: 2 links are not underlined
![links.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f21f2143-a42f-43e0-9d37-80ed565eea47)

**ER**: all links should be underlined

**Comment by alongoni** [comment]
Closed by #1833
