### ISSUE TITLE
[1.5.0] MM injected browser: impossible to connect the app in BARN and DEV environments

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1830]
Reported in https://altoros.slack.com/archives/C025G521XQD/p1636724589026500
1. Open MM injected browser
2. Open the app in Barn/Dev/Stage environments

**AR**: the apps are not connected to MM wallet account
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e405e1de-7319-469b-b00d-2e8edf0e13cd)

https://user-images.githubusercontent.com/70885163/141478503-c5cff91b-9a68-44f2-91a9-9b7b1bebb49e.mp4

**ER**: apps are connected

**Comment by anxolin** [comment]
@elena-zh I think this one is solved by https://github.com/gnosis/cowswap/pull/1870
