### ISSUE TITLE
[1.5.0] Pop up modal doesn't close

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1836]
**Description**
I had an old pop up modal that was still there when visiting the website.
I couldn't close it and even if the timer run down it didn't disappear. 
When connecting a new wallet it disappeared. 
But reappeared once **no** wallet was connected. 
Also hard refresh didn't help

**Expected behavior**
Should be closed when pressing the x or when the timer is down

**Screenshots**

https://user-images.githubusercontent.com/34510341/141809625-b27781e1-5c4f-47fd-92c8-23bcf9b1a245.mov

https://user-images.githubusercontent.com/34510341/141810124-b12f7aea-04ee-491f-8eb9-0f013eb07180.mov

**Comment by MareenG** [comment]
New pop ups also remain and can't be closed
<img width="1370" alt="Bildschirmfoto 2021-11-15 um 17 17 30" src="https://user-images.githubusercontent.com/34510341/141816469-b5e9d98f-50bf-4abd-9f0e-1f2319bee88a.png">

**Comment by MareenG** [comment]
Only transactions pop ups remain. Sell and buy orders pop ups disappear as expected

**Comment by elena-zh** [comment]
I can close all transactions' toast notifications in Win10 + all supported browsers, But I can't close them in mobile devices (both Android and iOS). 
I reported a separate issue for this #1609 and would like to link these issues together.
