### ISSUE TITLE
[1.5.0] Pillar logo really bad quality 

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1837]
**Description**
Pillar logo is just a blur bloob

**How to Reproduce**
1. Connect Pillar wallet via WC

**Expected behavior**
Not 100% sure but it would be great if the logo can be displayed better

**Screenshots**
![Bildschirmfoto 2021-11-15 um 16 26 21](https://user-images.githubusercontent.com/34510341/141811867-531de729-5e4d-4c78-984e-fbdfc99b3d60.png)

![Bildschirmfoto 2021-11-15 um 16 26 25](https://user-images.githubusercontent.com/34510341/141811884-7d93145d-bcd8-487c-bd6c-15dfd5aec189.png)

**Comment by alfetopito** [comment]
As far as I know, the logo is provided by the wallet.
Maybe reaching out to them if they care about it.

**Comment by MareenG** [comment]
Hard refresh solved the issue... closing
