### ISSUE TITLE
[1.5.0] Can't place an order due to 'can't define property' error

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1844]
The issue is not always reproducible, but more than 2 times I was able to get this error
`can't define property "0x58688fc899d881e3bf075d5acdbdea148f707a823dcfdec3adcb84cf8b561e18ff714b8b0e2700303ec912bd40496c3997ceea2b619389ba": Object is not extensible`

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/aa78d7ee-c1eb-4bd4-8895-61a91739cebb)

Video: https://watch.screencastify.com/v/u6k7pj9kjVtzg83zNZo8

The issue might be connected to #1618, #1785

**Possible steps to reproduce:** 
1. Place an order in 1 network
2. change  a network in the connected wallet
3. try to place an order in another network

**Comment by elena-zh** [comment]
Note: refreshing of the page helps to resolve the issue

**Comment by MareenG** [comment]
Maybe connected to https://github.com/gnosis/cowswap/pull/1684#issuecomment-949545325
