### ISSUE TITLE
[1.5.0] Enough signatures section is shifted in activity modal

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1850]
Enough signatures/Expired order section is shifted in activity modal
see the image: 
![section with enough.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/8377901d-3cea-4baf-90c0-0badf28bce69)

**Expected**: section should be left-aligned like all fields on the form

**Comment by biocom** [comment]
Let me know if this fix works for you https://github.com/gnosis/cowswap/pull/1862
