### ISSUE TITLE
[1.5.0] Expired order is sill in 'Signing' status when reject on-chain transaction is Safe

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1855]
1. Connect to a Gnosis safe
2. Create a Sell/Buy order transaction
3. Sign the transaction as the 1st owner
4. As the 2nd owner, reject the transaction
5. As the 1st owner, execute rejection transaction
6. Verify the Cowswap transaction's log when the order is expired

**AR**: Expired order is sill in 'Signing' status 
![expired.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3f018f08-cffb-44e1-bec9-de42e052073f)

**ER**: Expired order is sill in 'Expired' status

**Comment by elena-zh** [comment]
It took a while, but the status was changed in the end, So I'm closing the issue.

**Comment by alfetopito** [comment]
> It took a while, but the status was changed in the end, So I'm closing the issue.

How long was "a while"?

Ok to take a couple of seconds but anything over 1 minute we should probably investigate

**Comment by elena-zh** [comment]
@alfetopito , for about 1 min or up to 2.  
It is reported in the #1362 issue (an old one).
