### ISSUE TITLE
Error when switch to xdai without adding it to MM

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1867]
Discussed in https://altoros.slack.com/archives/C025G521XQD/p1637140554000800

1. Do not add xDAI network to MM
2. Switch to XDAI using network switcher

**AR:** error in the console

**ER:** offer a user to add the network to MM
examples here: https://chainlist.org/

**Comment by anxolin** [comment]
Good catch. Ideally we could try to add it. Metamask has another method to do that.

We can do exactly what https://chainlist.org/ does:

![image](https://user-images.githubusercontent.com/2352112/142186115-62227137-6560-4132-8251-d6c1d8e55e3b.png)
