### ISSUE TITLE
Error with insufficient fee in the latest PRs

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1868]
Related to #1861

I get the 'insufficient' fee warning when sign a trade with low amounts in xdai
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/dcd4a7e7-71e2-4a7d-8c78-9505002a6fbe)

Video: https://watch.screencastify.com/v/G9ygeO3uCunIgpMkDHqi

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/bf313e17-05a0-4bab-ae74-237992cde3f9)

I can't reproduce the issue in Prod/Stage/Dev

**Comment by elena-zh** [comment]
I was able to get this error message when I was testing changes for #1639 PR.
And trading amounts were high..
![image](https://user-images.githubusercontent.com/70885163/142243109-cdc43153-2d70-48df-b8eb-60c37fbe4153.png)

**Comment by nlordell** [comment]
Does this happen when you sign right away?

This is somewhat expected if you take too long to sign and the fee you were quoted expired (and the newly computed fee changed to something higher).

I know this may be quite tricky, but could you also record API request times?

**Comment by elena-zh** [comment]
@nlordell ,
I'm able to reproduce it in https://pr1639--gpswapui.review.gnosisdev.com/#/swap

Here is the video with exact steps I do in order to get this error in Rinkeby. I tried to filter  API requests for Fee in the Network tab and show all errors
https://watch.screencastify.com/v/NORzuConZV873fbnauvz

Requests time and timing (I get 2 requests for the 1st trade)
![image](https://user-images.githubusercontent.com/70885163/142266053-3f3e9c37-ebed-4571-9873-9e4c96d98ee7.png)
![image](https://user-images.githubusercontent.com/70885163/142266006-22ad8163-5698-4fa3-8014-61e10220eaf7.png)

Let me know please if I you have any questions.

**Comment by elena-zh** [comment]
No longer reproducible.
