### ISSUE TITLE
[ABA 🎵 ] - Fallback message in case of 🚫 Fiat impact && 🚫 ABA impact 

### ISSUE THREAD

**Issue by W3stside** [gnosis/cowswap#1908]
**Description**
Fallback message in case of 🚫 Fiat impact && 🚫 ABA impact 
What should we do if we can't show a fiat price impact NOR an ABA price impact?
Show some sort of warning, probably.

**Proposal**
Show a warning similar to the HighFeeWarning (underneath) on swap page and swap confirmation modal

**Alternatives**
Show a warning in the CurrencyInputPanel (where we show inputs and token dropdown)

## Screenshots
Swap page
![image](https://user-images.githubusercontent.com/21335563/143240816-06516d65-8154-4bef-931c-64fa7a5f5f94.png)

Modal
![image](https://user-images.githubusercontent.com/21335563/143240766-48ef3f0f-a331-437a-a4c0-78ae2cd05f09.png)

Mouseover content
![image](https://user-images.githubusercontent.com/21335563/143241587-de21a193-f017-495e-afcf-a5709d852a21.png)

## Content
Mouseover content:
```
<small>
  We are unfortunately unable to calculate any price impact for this trade.
  <br />
  <br />
  <u>
    <strong>
      We strongly advise you to compare this trade across other dexes and for you to do your due diligence before
      advancing.
    </strong>
  </u>
  <br />
  <br />
  You may still move forward with this trade but there is a potentially high risk of executing an unfavourable
  execution.
</small>
```

**Comment by alfetopito** [comment]
I'm not sure about pointing people to other dexes. We are supposed to offer the best price so people don't have to do that. I vote to leave that out.
Something like:

`We strongly advise you to do your due diligence before advancing.`

Also, tiny changes on the last sentence:

`You may still move forward with this order but there is a potentially high risk of executing an unfavorable trade.`

**Comment by anxolin** [comment]
Happy to separate in different PRs, but we need to discuss also what do we do while we don't have the USD estimation yet? For example, if this is slow and the user managed to trade fast he wouldn't get any warning. Open questions: do we block the user? do we show any warning?

**Comment by anxolin** [comment]
I like the suggestions of Leandro, for the first.

For the second, i would soften it up a bit:
`You may still move forward with this order but make sure the receive amounts are what you expect."

Also, I don't like to have two warnings. Can we use the same one? This way we can block the user while the USD estimation is not loaded. 

Not for this PR but I could see a logic like:
1. Loading USD estimation + swap button is disabled
2. After XXXs (i.e. 1.5s) if we still don't have USD estimation but we have price, we show the warning
3. The user can decide either to wait (until we have USD estimation) or check the checkbox to continue
3.1 If they check the checkbox, they would be able to trade without a price impact
3.2 if they wait, and we get a price impact, we continue with the normal flow as we do today
3.3. If they wait, and there's no price impact, we show the message in this issue
