### ISSUE TITLE
[1.10] GNO icon is not visible in the dark mode

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1913]
GNO icon is not visible in the dark mode: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2b345c75-72bd-4623-8e8d-06bd6670b36e)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/24d6f26c-9550-4947-8d5d-bea6e113e4b7)

**Expected**: make the icon visible

**Comment by MareenG** [comment]
Also other dark/black tokens or token lists logos with a transparent background are difficult to recognize in dark mode

<img width="207" alt="Bildschirmfoto 2021-11-25 um 12 23 41" src="https://user-images.githubusercontent.com/34510341/143432919-e97dd541-202e-46a3-a838-9d740c38ade2.png">
<img width="140" alt="Bildschirmfoto 2021-11-25 um 12 23 22" src="https://user-images.githubusercontent.com/34510341/143432934-34ecc892-7cfe-4190-b8e7-6b1bcfe7af46.png">

**Comment by anxolin** [comment]
Maybe relevant for applying a solution to this

https://www.npmjs.com/package/node-vibrant

Used for extracting the prominent color from the token logos: https://github.com/gnosis/cowswap/blob/6fb3ded2ba3bbc284477b1c2d78bf2a4bf201538/src/hooks/useColor.ts#L8
