### ISSUE TITLE
Reorganize app menu

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1956]
Originally reported in https://github.com/gnosis/cowswap/pull/1935#issuecomment-984923327
and 
https://github.com/gnosis/cowswap/pull/1935#issuecomment-984926169

Menu has become too long. This need a full redesign, not everything there is equally important, and it's hard to use that menu.
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6cb4297c-8d2c-4d56-a369-0f6f16d61619)

**Comment by W3stside** [comment]
would say this is low prio

**Comment by elena-zh** [comment]
Closed as will be fixed in #2113
