### ISSUE TITLE
Error in ETH amount estimation for wrapping ETH max value

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1990]
> Not sure if it's the same issue or related, but the display "0.0000000002 wrapping, unwrapping or enabling operations" is not really useful or user-friendly.

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3f7c511b-a99e-4f79-80c4-1d51fa864311)

**To reproduce:** 
1. Select ETH as a sell token
2. Fill in max ETH value
3. Select From token
4. Press on the 'Wrap my ETH' button

**Expected**: show more accurate estimation

**Comment by anxolin** [comment]
@W3stside can you take a look to this? (or if you give the pointers to @nenadV91 , hand it to him)

I understand, probably there's an error with USD estimation. But additionally, we should round down the wrappings, in in this case it would be a 0! 

On top of this, I think we need to do a couple of changes:
![image](https://user-images.githubusercontent.com/2352112/145803249-e8643b38-4afb-4f96-b262-71070eb300b2.png)

**Comment by elena-zh** [comment]
Seems to be fixed
