### ISSUE TITLE
Add vCOW balance to Profile

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#2007]
**Description**

Add vCOW balance to Profile

Crude wireframe:
![Screenshot from 2021-12-17 10-41-34](https://user-images.githubusercontent.com/43217/146553203-a2c612a5-a34a-4daf-bcc4-89a3b776b667.png)

**Proposal**

Split page into 2 sections:
1. Profile: containing only `vCOW` balance for the connected network
2. Affiliate Program: what we already have

When no `vCOW` balance, don't show anything on the `Profile` section

**Good to have**
When there's a vesting, show a dropdown with additional details
![Screenshot from 2021-12-17 10-46-15](https://user-images.githubusercontent.com/43217/146553774-1d15383e-fa9b-43ff-99da-d28c5e8593d1.png)

**Additional context**
- Data will be mocked for now, later they will read from a hook we provide
- While only the mocked data is available, show it only on dev, prs and localhost. Do not show on staging, barn nor prod. (There are flags in the code to identify the current environment)
- Wireframes: https://www.figma.com/file/DPp3awAUcqpwpV1dD4wFB9/CoW-claiming?node-id=33%3A4161

**Comment by anxolin** [comment]
The wireframes for the menu where it explains the voting power doesn't have very good numbers. Also, the claim button we won't need that for now. I wouldn't do it.

**Comment by alongoni** [comment]
Hey, here is a design for this. It's based on the new branding made by @michelbio:

![vCOW Balanceens](https://user-images.githubusercontent.com/622217/147261323-c38b2f94-5bbd-483a-a743-c50b26ae79e8.png)
![vCOW Balance openens](https://user-images.githubusercontent.com/622217/147261309-947bcc14-1dbe-4e33-a3f0-a805d61bfc33.png)

**Comment by elena-zh** [comment]
Hey @alongoni , how is it going to be displayed in a mobile view? 
Also, may be we could decrease a bit this balance section? Personally to me it looks too big and draws a lot of attention.

**Comment by alongoni** [comment]
Design Updated:
![CowSwap - Account page (affiliate-v1 8 - vCOW Balance](https://user-images.githubusercontent.com/622217/147283097-ecfb43d2-0669-44ce-9461-519706a04c63.png)
![CowSwap - Account page (affiliate-v1 8 - vCOW Balance open](https://user-images.githubusercontent.com/622217/147283089-cacb6985-8b76-4218-89e0-28e94262c65d.png)

![CowSwap - Account page (affiliate-v1 8 - mobile](https://user-images.githubusercontent.com/622217/147283106-ce8ec803-3089-4d01-bdaf-e2cf12e67604.png) ![CowSwap - Account page (affiliate-v1 8 - mobile-1](https://user-images.githubusercontent.com/622217/147283102-134a631e-4bc5-4544-86e7-ff782dc2911e.png) 

cc/ @elena-zh @biocom @alfetopito

**Comment by alongoni** [comment]
🧑‍🔧Experimental WIP🧑‍🔧. Just trying another approach to this UI but without the dropdown. I was thinking maybe a dropdown it's no needed here.![CowSwap - Account page Draft](https://user-images.githubusercontent.com/622217/147503532-dbab0827-76d4-4f5d-b0c5-16bb65f1acdb.png)

**Comment by elena-zh** [comment]
Hey @alongoni , nice approach!
But I'd second the previous option due to: 
 - all amounts will be displayed in one place ( in dropdown), 
 -  again, a bit not clear how these amounts will be displayed in a mobile screen

**Comment by alfetopito** [comment]
For now I'd stick with the first version, but anyway, we'll at first focus on implementing only the balance.
The details can keep being iterated on.

I'm happy with how it looks so far 👍
