### ISSUE TITLE
App's logo is missing on the hard error page in the latest PRs

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2020]
Originally reported in https://github.com/gnosis/cowswap/pull/1982#issuecomment-990976835

Also reproducible in https://pr2017--gpswapui.review.gnosisdev.com/#/swap

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3509cbc4-d244-4bae-a665-0a64bc56de88)

**Expected**: app logo should present on the hard error page. Should navigate a user to the main page
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0b5f43f2-e588-4b07-9e28-95b53a61dd6e)

**Comment by maria-vslvn** [comment]
@elena-zh I think it was fixed in https://github.com/gnosis/cowswap/pull/1829

**Comment by elena-zh** [comment]
@maria-vslvn , I can check this only after you update the branch for #1829 PR to the latest one so I will be able retest it.
