### ISSUE TITLE
[1.8.0] Tokens' description in still contains 'xDAI'

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2036]
Originally reported in https://github.com/gnosis/cowswap/pull/2023#pullrequestreview-837137906
Related to https://github.com/gnosis/gp-ui/issues/919

Tokens in the token list show xDAI 
![token list](https://user-images.githubusercontent.com/70885163/146895388-fba1d082-9041-4974-986c-ba1b09c0f1c4.jpg)

The same is for token names when import custom tokens
![import token](https://user-images.githubusercontent.com/70885163/146895447-d2518a76-29fc-4576-a51f-7c8af6c69423.jpg)

**Comment by elena-zh** [comment]
@alfetopito , @anxolin , will we be able to fix this?
If the issue is not on our side, we can close this issue...

**Comment by alfetopito** [comment]
We can still do a renaming on the frontend

Simple regex match `on xdai` and replace it with `on Gnosis Chain`, or `from Ethereum`

**Comment by anxolin** [comment]
But this comes from the token lists, right? I would not change it. We could reach the token lists and tell them to update the description

I guess this one is honeyswap

**Comment by anxolin** [comment]
Created an issue in HoneySwap, I don't think we should do any regex replacement on our side https://github.com/1Hive/honeyswap/issues/154

**Comment by alfetopito** [comment]
I thought that was coming from the contract, not from the list 🤔 

In that case, we can wait for them and close the issue on our side.
