### ISSUE TITLE
[1.10] Claim:  adjust margins in sections in Profile page in a mobile view

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2076]
It might seem that margins are different in Profile and Affiliate program sections when open the profile page in a mobile view. 
Moreover, there is  a lot of useless space at the top of the page.
See the image: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/48deb8fc-5b55-4901-a156-5b96b7b442fc)

I think, it would be nice to adjust margins to be the same in both sections (reduce it in the Profile section).

**Comment by alongoni** [comment]
closed by #2156
