### ISSUE TITLE
Claim: show 0 when no claimable tokens for an account

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2080]
Related to #2000 #2009

Currently, there is no 0 in the vCOW field when there are no claimable tokens for an account
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/285de376-d6aa-4dd7-91ca-fbae64ebdebd)

**Expected**: show 0 in the amount field

**Comment by nenadV91** [comment]
This is not relevant anymore
