### ISSUE TITLE
Claim: 'Claimed!' message is displayed when a transaction fails

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2082]
Related to #2000, #2009

1. Connect an account with tokens available to claim in Rinkeby
2. Connect a wallet
3. Open Claim  vCOW page
4. Press on the 'Claim vCOW' button
5. Specify conditions in transaction settings to get it failed (low-low gas fee, as an example)
6. Confirm the transaction in the connected wallet

**AR**: User gets a message about a successful Claim, however, the transaction fails
![Screenshot_1.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c91cae76-b9a3-4e8d-ac93-d30ed0da1634)

**ER:** it would be nice to show the 'claiming' state until transaction is successfully executed

**Comment by elena-zh** [comment]
Besides, it would be nice to navigate a user to the 'vCOW claim breakdown' page after Tx fails. Currently, user stays on the 'Claimed!' page and needs to reload it in order to see claim breakdown again.

**Comment by elena-zh** [comment]
Also, it would be nice to change Activity log entry to 'Claim ...vCOW' instead of 'Claimed ...vCOW', as Tx is failed, and tokens were not transferred to an account
![image](https://user-images.githubusercontent.com/70885163/149932079-a26c74ad-a493-41dd-99ef-0eb2ec364f3b.png)

**Comment by anxolin** [comment]
By the way, the "Calimed!" part is solved. It says now "Claim"


The part i think is more important to fix from this issue, is that if we fail we don't go to the SUCCESS page and we let the user re-attempt
