### ISSUE TITLE
[CLAIM] Hook: Approve token to invest in vCOW (also get balance)

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#2087]
Set the approval of the token. We already have an approval logic, it should be very similar. It change that we use the vCOW contract as the once receiving the allowance.

* Set MAX AMOUNT for approval
* Get allowances and balaces"

**Comment by W3stside** [comment]
Parts:

- [ ] GNO approve
- [ ] USDC approve
- [ ] show token balances
