### ISSUE TITLE
[CLAIM] Switch account functionality

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#2097]
- Switch account is allowed in step 1 and 2, but not in the last one
- Make sure all cases are taken into accoun (i.e. nothing is broken if you refresh or change account in any moment in the process)

**Comment by W3stside** [comment]
TO repeat what i said elsewhere - the logic will be:
User changes account in ANY stage? they will be brought back to the available claims table

"Change account" button: available until the last step: 
![image](https://user-images.githubusercontent.com/21335563/149815982-93d7e938-e697-4f7e-a743-ba7508f2f040.png)
