### ISSUE TITLE
Change The Gnosis Chain Logo In The Network Switcher

### ISSUE THREAD

**Issue by sacshin** [gnosis/cowswap#2136]
![gnosis chain](https://user-images.githubusercontent.com/55705611/149371970-f8b4984c-3305-4d09-bf66-793c0570113c.png)

**Comment by alfetopito** [comment]
Thanks for reaching out!

The requested change has been implemented and is currently pending deployment https://github.com/gnosis/cowswap/pull/2073

Closing it
