### ISSUE TITLE
[Claim] Create better handling of deadline UI

### ISSUE THREAD

**Issue by W3stside** [gnosis/cowswap#2183]
We should better handle the way we tell users they have claims based on state: 
(user has not claimed)
1. user is currently before claim time
2. user is after claim time 
(user has claimed)
* same as above 1) and 2)

comment: i agree with @biocom - we should create another fn to handle states:
```ts
_getHumanReadableClaimDeadline(end: number) {
    const now = Date.now()

    if (end > now) {
        contextString = 'Unfortunately your claim opportunity time is in the past. Your free claim opportunities expired on'
    } else {
        contextString = 'As an important member of the CowSwap Community you may claim vCOW to be used for voting and governance. You can claim your tokens until'
    }

    return contextString + ' ' + new Date(end).toLocaleString()
}
```

_Originally posted by @W3stside in https://github.com/gnosis/cowswap/pull/2178#r786631005_

**Comment by anxolin** [comment]
We discussed this, and i agree, although we mentioned its a good to have (for now we removed the oporunities)

You can dd it to the sprint as a low prio, or thing to do at the end.

**Comment by elena-zh** [comment]
Closing it as Claim is no longer available
