### ISSUE TITLE
Claim airdrop shows an infinite loader on it when Claim Tx fails

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2188]
1. Connect an account with several claim options
2. select airdrop only
3. Start claiming TX
4. Specify log gas price to get failed transaction
5. Wait till T fails
6. Open vCOW claim breakdown page

**AR**: Claim airdrop option shows an infinite loader on
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2d5d965d-458c-488a-a8f6-9a70d8441821)

**ER**: grid color is not changes, no loader on it, option is checked and disabled

**Comment by anxolin** [comment]
Great catch, I guess we never delete those claim ids from the state.

**Comment by anxolin** [comment]
@W3stside if you can handle this one, I think it may be somehow related to this other one https://github.com/gnosis/cowswap/issues/2082

**Comment by alfetopito** [comment]
I think this is fixed by https://github.com/gnosis/cowswap/pull/2355

**Comment by elena-zh** [comment]
@alfetopito , yes, thanks!
I have linked the issue with the #2355 pr
