### ISSUE TITLE
Claiming page: 'View transaction on Explorer' link navigates to Cowswap app

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2189]
Connect an account with free airdrop claiming
Start claim procedure, confirm transaction in the wallet
Verify Claiming' screen

**AR**: 'View transaction on Explorer' link is displayed there. Navigates to the Cowswap when press on it
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1a6e352d-d31c-40e1-91c1-0a052266e6f4)
**ER**: 'View transaction on Etherscan/Blockscout' link is displayed there. Navigates to the Etherscan/rinkeby.etherscan/Blockscout when press on it (depends on a network selected)

**Comment by anxolin** [comment]
Closed by https://github.com/gnosis/cowswap/pull/2263
