### ISSUE TITLE
'Invest max positive' button sets 100% pn the progress bar when 0 tokens in the wallet balance

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2201]
Related to #2191

1. Connect to an account with investment claims
2. Select all investment options
3. Make sure that you have 0 tokens balance on on of claim options
4. Approve tokens spend
5. Press on the 'Invest max positive' button when token's balance = 0

**AR**: Available investment used = 100%
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/14880f94-51b8-4db7-96a7-087e3678b700)

**ER**: Available investment used = 0%

**Comment by nenadV91** [comment]
Fixed in https://github.com/gnosis/cowswap/pull/2200
