### ISSUE TITLE
Formatic and Portis integrations

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#223]
When connecting a wallet (e.g. Portis, Fortmatic) the popups have a Uniswap branding

<img width="775" alt="Bildschirmfoto 2021-03-10 um 09 23 00" src="https://user-images.githubusercontent.com/34510341/110622975-78699a00-819c-11eb-83b5-ba613d3952d4.png">
<img width="433" alt="Bildschirmfoto 2021-03-10 um 09 25 22" src="https://user-images.githubusercontent.com/34510341/110622979-799ac700-819c-11eb-921d-7f42ea2be72b.png">

## Tasks
* [x] Integrate with Portis #279
* [x] Integrate with Formatic: #275 

## QA
* Make sure the integrations work. Please use the individual PRs for validating. Each PR contain a URL of the app with the feature implemented

**Comment by MareenG** [comment]
PRs stated above
For Fortmatic I couldn't see any more Uniswap branding. 
For Portis I still get the Uniswap branding

CowSwap
Portis has Cowswap branding 
Formatic can't connect at all 
<img width="409" alt="Bildschirmfoto 2021-03-23 um 09 58 40" src="https://user-images.githubusercontent.com/34510341/112120520-9c76a380-8bbe-11eb-9d53-d7d1d312ec60.png">

**Comment by anxolin** [comment]
@MareenG oh, right, we need to verify the domains for Formatic.
I verified only the domain for that PR. So it was working only on that URL. I need to go through another approval process.

I leave this PR: https://github.com/gnosis/gp-swap-ui/issues/329


For portis, not sure whats wrong, but in DEV its working: https://gp-swap.dev.gnosisdev.com/#/swap
![image](https://user-images.githubusercontent.com/2352112/112214328-5aca1500-8c1f-11eb-9e56-8495d52c326d.png)

**Comment by MareenG** [comment]
When connecting with Portis the instructions still show Uniswap branding in release v0.8.
<img width="402" alt="Bildschirmfoto 2021-04-08 um 10 27 57" src="https://user-images.githubusercontent.com/34510341/113993849-25dfd400-9855-11eb-96e6-d46edfd60bf6.png">

**Comment by MareenG** [comment]
Closing it for now as we disables Portis and Fortmatic
