### ISSUE TITLE
Investment amount is reset when go back from the last investment screen

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2242]
1. Connect to an account with an investment option
2. Approve a token
3. Specify an amount to claim
4. Press on the Review button
5. Go back to the Set allowance screen

**AR**: Investment amount shows 0
https://watch.screencastify.com/v/03bKKeWuyuWPKGq6l9kE

**ER**: it would be great to save the previously filled in investment amount

**Comment by anxolin** [comment]
Yes, it seems like an issue. @nenadV91 is this in your radar for recovering the right amounts from REDUX?

**Comment by nenadV91** [comment]
Yes I can take a look at this.
