### ISSUE TITLE
[Claim + Approve] - Connect acct approve remains approved for 3rd party connect

### ISSUE THREAD

**Issue by W3stside** [gnosis/cowswap#2244]
Referring to https://github.com/gnosis/cowswap/pull/2175#pullrequestreview-858643322

To test:
Approve logic cowslip claim

A. Connected acct is approved, 3rd party acct also shows approved for same token
1. Add acct and connect via: `0xfD40fcF9AD20C8fe4936E552833696496EA88E01` (copyable PK below)
```
 0xd1628862ad6361fbc5d376ccb0aa4f07c2125a9a3c84e8d4231da30342d11958
```
2. Claim GNO
3. See approved
4. Click “Change account”
5. Paste 3rd party acct: `0x97EC4fcD5F78cA6f6E4E1EAC6c0Ec8421bA518B7`
6. Claim GNO
7. See approved

3rd party acct from scenario A. above, not approved
1. Add acct and connect via: `0x97EC4fcD5F78cA6f6E4E1EAC6c0Ec8421bA518B7` (copyable PK below)
```
0x57bec3b25f07930bbec339aa7ec15eb12244f609f705cf3320ce8650244361a8
```
2. Claim GNO
3. See NEEDS TO BE APPROVED

**Comment by elena-zh** [comment]
Could I get a preview link pls?

**Comment by W3stside** [comment]
https://pr2175--gpswapui.review.gnosisdev.com/

**Comment by elena-zh** [comment]
At a first glance, works for me. But I was able to see 'Approve GNO' button again after the Claim transaction: 
1. Connect an account with GNO option
2. Approve GNO token
3. Do a Claim with GNO investment option for the account
4. Change an account to claim on behalf

---> GNO required approval 
Video: https://watch.screencastify.com/v/uS48l4exVhDwTCMpceCz
