### ISSUE TITLE
Show a loader when claim page is loading

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2245]
Claim page show different data when it is loading, so it would be nice to add a loader until everything is loaded.
See the video: https://watch.screencastify.com/v/JB5kx7Ojt1jfb9baZVxr

**Expected**: Show a loader when claim page is loading

**Comment by anxolin** [comment]
Yes, this one is annoying! 

We discussed it, and we will add a loading parameter, so we wait a bit before displaying the information
