### ISSUE TITLE
'Change account' and 'Switch to connected account' links are enabled on 'Claiming' page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2271]
'Change account' and 'Switch to connected account' links are enabled on 'Claiming' page

![disable.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3a698260-3543-46e8-91bb-fb307039bb06)

**Expected**: disable or remove these buttons

**Comment by anxolin** [comment]
I believe this one is closed by https://github.com/gnosis/cowswap/pull/2266
