### ISSUE TITLE
Incorrect validation message when claim amount is too low, and number of decimals > required

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2274]
Select investment option USDC to claim
Enter too low amount 0.000000001  (with 9 decimals)
For ETH/GNO option enter an amount with 19 decimals (0.0000000000000000001)

**AR**: 'Your investment amount can't be zero' validation message
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3d4d3348-09a1-4416-83f0-d478e2361996)

**ER**: I'd expect  'Enter a valid amount' or so as the validation message for this case

**Comment by anxolin** [comment]
well, true, we could limit for the precision of the token, although i think is super low prio.

The case affects just the warning message of users who try to add 19 decimals for ether and 7 decimals for USDC. And not even that, we allow it as long as its over one wei in the unit. 

Closing cause its not worth the effort imo. Re-open if you think is imp
