### ISSUE TITLE
Can't connect to a wallet using WC from the http://mature-leaf.surge.sh/#/swap environment

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2275]
The issue appeared during testing session on http://mature-leaf.surge.sh/#/swap environment
When try to connect a wallet using WC code/link, the connection does not work.
Error in console is displayed: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/bc05556a-51e9-4b28-86a1-1e84dab3ca6d)

However, everything works as expected when connect using WC in PRs, https://cowswap.dev.gnosisdev.com/#/claim :
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/259c0b1b-e364-4907-880b-36e38b670529)

**Comment by anxolin** [comment]
ahhhh!

I see, look at this:

![image](https://user-images.githubusercontent.com/2352112/150877574-9b685e16-19da-4bda-b491-3f86199106e1.png)



It's just because it's HTTP, not HTTPS
