### ISSUE TITLE
Rounding issues: 'not enough funds' message is displayed when balance=investment balance

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2276]
1. Connect to a wallet
2. Try to claim on behalf of an account
3. Make sure you have exactly the same amount of an investment token in the connected wallet that is displayed on the form to invest

**AR**: 'not enough funds' message is displayed when balance=investment balance. 
This is due to rounding issues, as slightly more token's balance is needed for 100% investment
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d5892298-365c-4d77-aef4-035de3fd7d0a)

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/02a1e967-cf39-4cdb-8839-a81f51bbca87)

**ER**: several options: 
 - show the whole amount needed for investment
 - show the whole amounts on hover a mouse?

**Comment by elena-zh** [comment]
If come up with decision to show amounts on hover, it would be nice to add it to the amounts on the next screen as well
![image](https://user-images.githubusercontent.com/70885163/150848506-62607049-334a-43f2-85f5-5fd6ff476a91.png)

**Comment by alfetopito** [comment]
No longer applies as the native balance is no longer blocking https://github.com/gnosis/cowswap/pull/2279

The amounts on hover are still valid and will be added

**Comment by elena-zh** [comment]
> No longer applies as the native balance is no longer blocking #2279

I described the issue based on ETH, but I believe, I will face this rounding issue when I try another investment token.
