### ISSUE TITLE
Claim balance field does not appear when change networks

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2296]
**Sometimes** Claim balance field does not appear when change networks:

**To reproduce:** 
1. Connect to MM wallet 
2. Change networks several times

**AR**: you can get the form without vCOW balance
![vcow field.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/04b4fbf3-1fbc-4d54-a76d-c680bfcd1ddf)

**ER**: vCOW balance field should be always displayed on the Claim page

**Comment by nenadV91** [comment]
I couldn't reproduce this one.

**Comment by elena-zh** [comment]
@nenadV91 , that is why I mentioned, that **'Sometimes'** .
I faced it yesterday 2-3 times, that is why I reported it.

**Comment by elena-zh** [comment]
Hey @nenadV91 , I have found the exact steps to reproduce the issue: 
1. Connect to an account with an investment opportunity
2. Check any investment option
3. when on the 2nd, 3rd and the last investment screens, switch between networks --> You will see the screen with no vCOW balance

See the video: https://watch.screencastify.com/v/rrrOLx2ivDrniJ5eBbQn

Moreover, you will be navigated to the 2nd/3rd/last investment screens with empty balance in case you have active claims for this account in another network 
![image](https://user-images.githubusercontent.com/70885163/151213725-dcde5ce6-6afb-42f4-ac23-613228feb7ac.png)

As expected result here I can see navigating a user from every step to the main claim page when switch between networks. 

I'm changing the issue priority to medium.
