### ISSUE TITLE
Claim: 'connect a wallet' button stays in the clicked state when close connection modal

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2309]
1. Open Claim page as a not connected user
2. Paste an address with active claims on Mainnet
3. Press on the Connect a wallet button at the bottom of the page
4. Close the connection modal

**AR**: 'connect a wallet' button stays in the clicked state
![clicked state.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/822f2cae-917f-4de5-bbb8-9acd91bd8a83)

**ER**: the button is in the 'default' state

**Comment by anxolin** [comment]
I mean, I don't see the issue :) 

It's because i need to click outside for the button be pressed. I find it ok if so. I would close this one
