### ISSUE TITLE
Force to connect to Ethereum when connect from the Claim page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2310]
1. Open claim page as a not connected user
2. Paste an address to verify claims
3. If there are active claims, press on the 'Connect to a wallet' button

**AR**: user is connected to another network if it is selected in the MM
video: https://watch.screencastify.com/v/FWHkZs5CyGhi1XCNTz14

**Expected:**
If user selects MM, it would be great to force a user to connect to Mainnet as we do for the network switcher, due to user sees claims for the Mainnet network

**Comment by anxolin** [comment]
I think it will not be worth the effort. It's nice we detect the network change, then we load the data for the new network. I would leave it as it is.
