### ISSUE TITLE
Account info remains to be displayed when disconnect a wallet

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2311]
Open Claim page as a connected wallet
Disconnect the wallet/Lock MM/

**AR**: Account info remains to be displayed when disconnect a wallet
Video: https://watch.screencastify.com/v/mfX8ujS9NZYuJsUkuoSm

**ER**: account info is not displayed

Moreover, the account info with active claims is still displayed when remove a wallet
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9a83b6bf-fc3f-42a2-9f5a-edf39abedf4b)

**Comment by anxolin** [comment]
Yes, the connect wallet and claiming account are two different things. I think you are right, but i also thing is fine to leave it like this. 

The app is not broken, it's just selected your previous wallet.
