### ISSUE TITLE
A lot of errors in the console in Dev  environment when connect to the Gnosis Chain

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2360]
A lot of errors in the console in Dev  environment when connect to the Gnosis Chain, especially when swap a token pair several times: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f08aea39-e220-4363-866a-7fa33fde6fbb)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0e164810-d9f5-4925-852f-41e86b64a514)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/493159a8-22ad-4db9-a304-3d0a78894bf2)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/37394ddc-9da3-4520-9ca5-c343b88ab674)

**Comment by elena-zh** [comment]
@nenadV91 , I think we have the issue for the Coingecko on the board https://github.com/gnosis/cowswap/issues/1672

**Comment by nenadV91** [comment]
Ok I will close this one then since those claim issues are fixed.
