### ISSUE TITLE
[1.10] Change gas recommendations for GC when claim xDAI

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2389]
The app shows too huge Tx gas estimation in xDAI . Sometimes it might show estimation > available xDAI balance in the wallet.  
In fact, it requires mush less than is described.
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f0ac7b23-cab6-467e-b4e6-81c977a38c6b)

It would be nice to change gas recommendations for the Gnosis chain network. 

Discussed in https://gnosisinc.slack.com/archives/C025G521XQD/p1643889349414839

**Comment by alfetopito** [comment]
Well, this is happening because the estimation is using mainnet gas prices https://github.com/gnosis/cowswap/blob/f86ed9f9be9ed0f7b94cabf047b4060b91f09261/src/custom/constants/index.ts#L102

Checking with the Safe team for a gchain endpoint
