### ISSUE TITLE
'Already claimed' button appears on the Claim successful screen

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2416]
Do a successful claim (for yourself or on behalf)
Verify the Claim successful screen

**AR**: 'Already claimed' button appears on the Claim successful screen
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a29378fb-68ac-4054-b0b4-7cc6b520ced0)

**ER**: no 'Already claimed' button on the Claim successful screen

**Comment by W3stside** [comment]
@nenadV91 i think u fixed this no?

**Comment by elena-zh** [comment]
Seems to be still reproducible 
![image](https://user-images.githubusercontent.com/70885163/154675855-4b891902-f24a-4fe4-a1ad-1504fab15c55.png)

**Comment by nenadV91** [comment]
@W3stside Nope, this is something else, I worked on this https://github.com/gnosis/cowswap/pull/2420

**Comment by nenadV91** [comment]
This should fix it https://github.com/gnosis/cowswap/pull/2478
