### ISSUE TITLE
Sometimes vCOW balance is empty when switch between networks + no loader

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2417]
**Sometimes** vCOW balance is empty when switch between networks. 
In order to reproduce the issue try to switch between networks using MM. 
I was able to get empty vCOW balance field twice.
![0.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1f8b33da-796e-48fa-ae3c-3aa1e6b27b05)
![image](https://user-images.githubusercontent.com/70885163/154473588-67a60b57-483c-4bbe-a0d3-ed43a1aa29d0.png)

**Expected**: the field should not be empty. 

The balance is updated when refresh the page.

**Comment by elena-zh** [comment]
To add: there is also no loader when an amount is loaded after switching networks. See the video: https://watch.screencastify.com/v/owMPs5TEvnOTDu6tpDWL 
So it would be nice to add it. I think, it might help to resolve the issue with an empty balance field.

**Comment by anxolin** [comment]
Closing, as @nenadV91 says its solved. Elena, reopen if this is not the case
