### ISSUE TITLE
Rounding issue on Claim when claim for yourself

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2425]
Reported in https://gnosisinc.slack.com/archives/CSGLUC1BN/p1644938072913749

I've noticed a rounding bug in the claim transaction for paid claims when claiming for yourself: if selecting max, the executed amount is not the maximum claimed amount by the user, but the nearest rounded float approximation of that amount.
This means that some users will receive (and pay) negligibly less than the maximum, but also some users might see the transaction reverting if the rounding makes the amount go beyond the maximum allowed. Somewhat surprisingly this doesn't happen when claiming for other addresses.
Reproduce: use the impersonator wallet connect wrapper and impersonate address `0x56eB62E08FADBD1280fA57656C3Ea456864bD192`. Try to claim its GNO claim and look at the generated calldata. The theoretical max is `0x23cf3f9ccf107d0e9c` but the claimed value is `0x23cf3f9ccf107d0955`. Both correspond to `660.5698698823669` vCOW.

**Comment by anxolin** [comment]
Not relevant anymore, just the part of post-mortem @alfetopito is looking into, just to see if theres a math problem, or this comes from the python script and  we didn't take into account "not exact" vCOW calculations
