### ISSUE TITLE
repeatedly asked to add token to MM

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#243]
After each order I get asked repeatedly to add the received token to MM eventhough I added it already.

**Comment by anxolin** [comment]
This sounds like a bug. I CC @W3stside , maybe was related to some changes in the lists of tokens. There was some changes we did today in this part, so it's possible this error went away. We need to review.

**Comment by anxolin** [comment]
We discussed internally, and we don't see it as a big issue for these reasons:
- The app cannot know if the user has the token or not
- Metamask don't tell you this info for privacy reasons
- We could "save in the browser" that we added something to MM, so next time is not offered, but we can't know for sure if the user deleted in his metamask the token, changed accounts, or reseted his MM. Therefore we can end up not showing it to a user that we should, so the problem would be actually worse not to show it to this user than show it always to all users

**Comment by MareenG** [comment]
Totally agree with your decision. The only thing that puzzled me that when I started using swap I believe this didn't happen but since last week it repeatedly started to ask me.

**Comment by anxolin** [comment]
mm, strange, it should be exactly as uniswap, if you say this happens in our app and not uni, then it's indeed an issue and we should look at it

**Comment by MareenG** [comment]
Sorry, a misunderstanding.  The first times I used GP swap I wasn't asked repeatedly to add the token to MM. 
But I think last week I was asked everytime this is why I noticed it. 
On Uniswap I also get asked everytime to add the token to MM

**Comment by MareenG** [comment]
Could this have been implemented with the change from uni v3.0.8 to v3.2.3? 
I think I didn't get asked before when using staging but got asked in dev

**Comment by anxolin** [comment]
yes, this was added in v3.0.8 to v3.2.3, but those changes have been in our app for a while... 
never mind :)
