### ISSUE TITLE
Change warning on the profile page when connected to Rinkeby/GC

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2513]
1. Connect to a wallet in Rinkeby/GC
2. Open Profile page
3. Check the warning message

**AR**: 'Profile data is only available for mainnet. Please change the network to see it.' message is displayed
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5845ae6a-e04d-4707-bac1-668384e2d60e)

**ER**: Change to  '**Affiliate data is only available for Ethereum. Please change the network to see it.**' as everywhere in the app

**Comment by anxolin** [comment]
Hopefully soon, we can have this program in any change thanks to the graph :)
