### ISSUE TITLE
The app is crashed when update Claim page in the dev environment 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2538]
1. Open https://cowswap.staging.gnosisdev.com/#/claim
2. manually change URL to https://cowswap.dev.gnosisdev.com/#/claim

**AR**: the app is crashed
Video: https://watch.screencastify.com/v/mb3jZ8UtrpnNEpSDy3Lc
![image](https://user-images.githubusercontent.com/70885163/157899416-e4237b60-f62b-420e-9012-123a9d5fd0ab.png)

**ER**: the app is loaded

**Comment by alfetopito** [comment]
What do you see if you click on the `git.io` link?

Anyway, not sure what could be causing this just looking at it

**Comment by elena-zh** [comment]
@alfetopito , I see this 
![image](https://user-images.githubusercontent.com/70885163/157907067-d89af5da-4589-4ad9-8390-5fca82791da4.png)


https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/utils/errors.md#1

**Comment by elena-zh** [comment]
I have changed the issue priority as it is appears that the app is crashed when I reload the Claim page. 
So to reproduce: open the Claim page, reload it.

**Comment by anxolin** [comment]
This issue has to do with a circular dependency

We've made the MOD `CurrencyInputPanelMod` to import `AuxInformationContainer` which is redefining the styles using the Container `styled(Container)`, however, the container is not yet initialized!

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/2352112/158802945-91991b45-ef97-4024-94e4-82fbca305bb3.png">


See https://github.com/gnosis/gp-swap-ui/blob/5d43dc5baa8639bd32e0a02184a3d6599d5081fe/src/custom/components/CurrencyInputPanel/CurrencyInputPanelMod.tsx#L29


... and
https://github.com/gnosis/gp-swap-ui/blob/6fb3ded2ba3bbc284477b1c2d78bf2a4bf201538/src/custom/components/CurrencyInputPanel/index.tsx#L40



@W3stside can you review it?

**Comment by anxolin** [comment]
@W3stside since this will go to prod next week. Could you take a look?
