### ISSUE TITLE
Mobile: Fee discount tooltip overlaps Fee CoWmunity modal

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2561]
Originally reported in https://github.com/gnosis/cowswap/pull/2551#issuecomment-1071039983 (case 4)

In a real mobile device, when I try opening the Fee discount tooltip, the modal is opened:
 ![image](https://user-images.githubusercontent.com/70885163/158634024-28ad8235-c139-48b8-b4ad-c2b76ba33c95.png)

**Expected**: tooltip is shown without opening the modal

**Comment by fairlighteth** [comment]
@elena-zh I think addresses and can be close?

**Comment by elena-zh** [comment]
@fairlighteth , thanks, closed.
