### ISSUE TITLE
COW token icon is not displayed in the activity modal 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2604]
Trade with the COW token, then open activity modal: COW token icon looks like a broken one
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c577064f-59ea-4311-b810-c4be705a5006)

**Expected**: the icon is displayed

**Comment by W3stside** [comment]
because
[there is no image on uni](https://raw.githubusercontent.com/Uniswap/assets/master/blockchains/ethereum/assets/0xdef1ca1fb7fbcdc777520aa7f396b4e015f497ab/logo.png)

**Comment by anxolin** [comment]
Is it in Trust @W3stside , also make sure u poke the people/project needed to get it. Or evaluate if we need to fork this trust project ourselves too.. (i hope not)

cc/ @avsavsavs

**Comment by avsavsavs** [comment]
![image](https://user-images.githubusercontent.com/80408352/160608206-8126597b-0ede-4e10-985b-bd9f0c314a82.png)

waiting for the last check to submit the PR to add the token in trust wallet

**Comment by anxolin** [comment]
Please, remember to add it also in Gnosis Chain.

Once you have the PR/PRs give it to me, I might be able to accelerate it

**Comment by avsavsavs** [comment]
Yes, but that needs to be a separate PR, cant put two tokens in the same one.
