### ISSUE TITLE
 vCOW token icon is not correct on the Claim button

### ISSUE THREAD

**Issue by alongoni** [gnosis/cowswap#2607]
**Description**
This vCOW token icon should be changed.
![image](https://user-images.githubusercontent.com/622217/160609806-9437db54-d88e-4960-b778-4d34c05dfc3e.png)

vCOW:
![image](https://user-images.githubusercontent.com/622217/160609965-35003a37-c390-44da-aca3-99eff55314b4.png)

COW: 
![image](https://user-images.githubusercontent.com/622217/160610013-d101cc8f-8980-4b20-9c65-471c128e51d8.png)

**Comment by elena-zh** [comment]
@alongoni , this is being fixed/discussed in #2606 / #2604

**Comment by elena-zh** [comment]
Hey @alongoni , I have updated the issue description to the one that is still valid and not fixed in #2609 RC

**Comment by fairlighteth** [comment]
This issue will become obsolete in favor of https://github.com/gnosis/cowswap/issues/2639 / cc @elena-zh

**Comment by elena-zh** [comment]
@fairlighteth , closing the current one then. Thanks!
