### ISSUE TITLE
Notification Delay and wrong label in recent activities

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#261]
# Description
For 2 trades I noticed a notification delay and wrong labeling. I could only document one of them.
According to the Explorer and Etherscan the trade was executed. GP Swap however showed a still pending sign. 
After 20 min+ past the submission the the trade was marked as expired. 

# to Reproduce
normal swap on Rinkeby 
transaction deadline 20min

# Expected Behaviour

Once the trade is executed GP swap should show a notification pop up and it should be shown under recent activities

# Screenshoots and Infos
**Explorer** _the trade was filled in around 1min_  https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x2973e1edc471429ddfb039b54e5b969c7e0d363ca360dd6ac954182079098cb752df85e9de71aa1c210873bcf37ec46d36c99dc26051e6d7

**GP Swap** _after aprox. 15min_
![Bildschirmfoto 2021-03-17 um 12 20 43](https://user-images.githubusercontent.com/34510341/111461304-52ed0b00-871d-11eb-8d81-1727467f25f9.png)

**GP Swap** _aprox. 22 min after the trade was submitted
<img width="410" alt="Bildschirmfoto 2021-03-17 um 12 36 30" src="https://user-images.githubusercontent.com/34510341/111461482-8d56a800-871d-11eb-9140-37903f7f0ae2.png">

# Note
I did some other trades with a transaction deadline of 1 min right after. They also got marked as expired in GP swap but got executed 
https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x7c5a12a74810cd98e9a1e7ef1dec5cb586eef9d20b3d4c0c7463a757a992ef8352df85e9de71aa1c210873bcf37ec46d36c99dc26051e5c7
https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x4206b9064ef31d1140fe1b3ef1d3daddec8e88791e0d458c9b7b8f1d1568949d52df85e9de71aa1c210873bcf37ec46d36c99dc26051e50d

I noticed that GP swap is usually a bit delayed compared to the the Explorer but in average not more than a min.

**Comment by anxolin** [comment]
@MareenG there can be connectivity issues that produced this. If for some reason the app doesn't receive the notification of the order execution, then it will think it's expired after 20min. 

I put it with moderate prio in the backlog for further review, but if you can reproduce easily we will increase the prio so we make sure we look asap into it.

**Comment by W3stside** [comment]
as written in PR #269 - i believe a better solution could be to use the `invalidated` prop of `OrderMetaData` to check if order is invalidated due to expiration

**Comment by anxolin** [comment]
> as written in PR #269 - i believe a better solution could be to use the invalidated prop of OrderMetaData to check if order is invalidated due to expiration

"Invalidated" only shows the order has been canceled. It doesn't work for expiration. You could use "executedAmount" to know if the user traded, but even the backend might be affected by a reorg or network issue. We can change it anyways to use the API instead of the ethereum events, just to show always the same view as the backend if we think this has better UX.

**Comment by MareenG** [comment]
I encountered this issue again several times today. 
Marked as failed in Cow UI but went through
https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0xdc6114b9e2faf4c409047b9346094d27f1ad87b0ac5c209f0bf28ad813760cb88bc0fe84022542e1611ff252090028df741ad67060630125
https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x3b00c04dda6d72d1fd2775663c2499df118352c66dd139b10c3db83251a618a38bc0fe84022542e1611ff252090028df741ad6706062f975
Marked as failed and failed
https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x1d927da5ff15e03c5096d8a613ac33c23051856861d75f8bdd7563ee2a25db368bc0fe84022542e1611ff252090028df741ad6706062f97f

<img width="400" alt="Bildschirmfoto 2021-03-30 um 12 51 14" src="https://user-images.githubusercontent.com/34510341/112977750-b2eca400-9156-11eb-80f5-ed00170a719f.png">

**Comment by MareenG** [comment]
It should be fixed with the next release then?

**Comment by alfetopito** [comment]
I was going to say you can try it out in the PR link, but there's an issue that's causing the PR to not be deployed :(

**Comment by alfetopito** [comment]
@MareenG the fix has been deployed everywhere.
Let me know whether you still see any of the reported behaviour

**Comment by MareenG** [comment]
Yes
