### ISSUE TITLE
Menu update

### ISSUE THREAD

**Issue by nenadV91** [gnosis/cowswap#2623]
We want to change current way the menu is displayed 
![Screenshot from 2022-03-31 14-25-25.png](https://images.zenhubusercontent.com/61093afdffd52dc74263a8d2/e47e4eb9-e5b8-4f73-bb27-b6fe4e1d1c7b)

**To be determined**
- Do we want to do something like Uniswap like 1Inch for example?

**Uniswap**
![Screenshot from 2022-03-31 14-27-10.png](https://images.zenhubusercontent.com/61093afdffd52dc74263a8d2/7cb90162-0dda-427a-bdad-c72c626afb17)

**1Inch**
![Screenshot from 2022-03-31 14-22-34.png](https://images.zenhubusercontent.com/61093afdffd52dc74263a8d2/3b50bcd9-e791-4fbc-a7d8-b59b3ad96c33)

![Screenshot from 2022-03-31 14-28-50.png](https://images.zenhubusercontent.com/61093afdffd52dc74263a8d2/7cd7828e-709d-4505-93e2-0cdaae021ace)

- How will this implementation affect server side rendering if we decide to implement it?

**Comment by elena-zh** [comment]
Might it be related to #2456 ?

**Comment by fairlighteth** [comment]
Closing in favor of #2456
