### ISSUE TITLE
Remove analytics and Chats links

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#274]
Points to uniswap

**Comment by MareenG** [comment]
I just noticed the same. 
How about to link to the explorer instead. 
There is no explicit link yet on the interface.

**Comment by anxolin** [comment]
> How about to link to the explorer instead.

Yep, I also considered it, but for now there's no much point, since you can only see orders. So I think is best to only point to it using your orders.

If in the future we include market information, stats, and so on, I think is indeed valuable. But for now, simpler (less links) feels better
