### ISSUE TITLE
Remove translations: The app is only partially translated

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#276]
Some parts of the website get translated into German and some remain in English. 
Personally, I find this confusing and dislike this a bit, would prefer rather the all or nothing approach. 
Note: it is the same on Uniswap

<img width="1548" alt="Bildschirmfoto 2021-03-18 um 09 45 23" src="https://user-images.githubusercontent.com/34510341/111598327-68227200-87cf-11eb-9020-07924efdf645.png">

**Comment by alfetopito** [comment]
Good point!
I've noticed there are translation files in the project source, but we are not maintaining them in any way with the text changes we are making.

The short term solution is to disable them completely.

**Comment by MareenG** [comment]
I think disabling would be good if it is not maintained

**Comment by anxolin** [comment]
yep, lets disable then. I'll update the title and move this to the product backlog.
