### ISSUE TITLE
Wallet Connect is broken for xDAI

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#300]
Steps to reproduce:

1. Open Metamask mobile
2. Connect to xDAI in MM
3. Open app, connect using wallet connect

![IMG_2AEFA7FC7CBF-1](https://user-images.githubusercontent.com/2352112/111770180-6083cb80-88aa-11eb-8773-6a51c0f6433e.jpeg)

**Comment by elena-zh** [comment]
Hey @anxolin , 
I was not able to reproduce this issue. 
Is it still reproducible for you?
