### ISSUE TITLE
Switching between accounts - activity is not changed

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#320]
# Description 
When switching between different MM accounts the recent activities overview show all trades corresponding to the MM account. It doesn't differentiate between the different accounts within MM. 

# How to reproduce

1. Have different accounts in MM 
2. Connect MM to Cowswap activate account 1
3. Trade
4. Change to account 2
5. Trade

# Result 
Both trades are displayed under recent activites
<img width="432" alt="Bildschirmfoto 2021-03-23 um 11 46 54" src="https://user-images.githubusercontent.com/34510341/112135564-3265fa80-8bce-11eb-87de-25642cc2550b.png">
<img width="409" alt="Bildschirmfoto 2021-03-23 um 11 47 13" src="https://user-images.githubusercontent.com/34510341/112135568-33972780-8bce-11eb-8fe1-23ef0360771c.png">

# Expected Results

I don't know what the expected result should look like (in Uniswao it is the same)  but I think it is odd that for both accounts the same trading history is displayed. 
Also if changing to a Portis or Fortmatic wallet my recent history displays only the corresponding activites of this wallet.

**Comment by anxolin** [comment]
Probably inherit from Uniswap too. I also think it would be weird! If it's the case, Im surprised they implemented like this and users don't complain. 

I believe the app shows only activity stored in your browser, not related to your account.

**Comment by MareenG** [comment]
Yeah, there are a lot of things inherit from Uniswap, where I wonder why people haven't complaint before :).

**Comment by elena-zh** [comment]
I'd add an issue here: account window is still displayed when change accounts. 
In the end, it is difficult to understand under which account my transaction is running
https://drive.google.com/file/d/1cGUqKpKiEPeJIWuwWxI2CQX5W4OdRy6X/view
