### ISSUE TITLE
Wrong Network - Wallet Connect and MM

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#332]
# Description
Connecting through WalletConnect with MM fails if app is set to Rinkeby. 
User gets stuck until clearing all site data

# Reproduce

1. Connect Wallet- chose WalletConnect
2. Open MM app on phone set network to Rinkeby
3. Scan QR code
4. Follow instructions on app 
The Following Error Message is shown: 
<img width="2545" alt="Bildschirmfoto 2021-03-24 um 11 43 21" src="https://user-images.githubusercontent.com/34510341/112297441-32c9c880-8c96-11eb-80ce-6917b140a30a.png">
 5. You are basically stcu here as you also can't change the wallet anymore
 6. Changing to Mainnet in the app doesn't fix it
 7. Clear Data site and a refresh is needed to get to be able to start from the begining. 

# Expected behaviour
I would assume that you could connect to Rinkeby and mainnet. 
If only Mainnet is supported as for Fortmatic and Portis #296 the user shouldn't get stuck. 

# Others
The notification is in the uniswap branding scheme

<img width="293" alt="Bildschirmfoto 2021-03-24 um 11 57 13" src="https://user-images.githubusercontent.com/34510341/112299494-22b2e880-8c98-11eb-9f0a-54611c7cb48c.png">

**Comment by MareenG** [comment]
Note: When I do the same in Uni it also shows that I am in the wrong network but I am not getting stuck. 
I can chose another wallet. However, Walletconnect also doesn't work  anymore until I clear the site data

**Comment by elena-zh** [comment]
Seems to be not reproducible so far

**Comment by MareenG** [comment]
Not reproducible
