### ISSUE TITLE
Inverted prices in the UI

### ISSUE THREAD

**Issue by nlordell** [gnosis/cowswap#367]
I believe the prices in the swap UI are inverted:

![image](https://user-images.githubusercontent.com/4210206/113119756-13d8b280-9211-11eb-8341-7f8faabbb5d0.png)

Here, a price for the [GNO/OWL currency pair](https://www.investopedia.com/terms/c/currencypair.asp) means that the price is denoted in OWL. From the link above:
> The quotation EUR/USD = 1.2500 means that one euro is exchanged for 1.2500 U.S. dollars.

This means that the UI suggest that 0.0069 OWL can buy you 1 GNO. Another way to think of it is, the price of beer at the store is for the pair `beer/$`, so amount in dollars to buy a beer. 

The price should either be: `0.00688433 OWL / GNO` (i.e. buying 1 OWL with GNO costs you 0.0069 GNO) or `0.00688433 GNO per OWL`.

**Comment by elena-zh** [comment]
Seems that it is already implemented: https://watch.screencastify.com/v/yUdZgPnQoUqzAm75Oa5X
I'm closing the issue.
