### ISSUE TITLE
Custom slippage around 5%

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#395]
**Describe the bug**
When setting a custom slippage around 5% a wrong notification is shown for some values

**How to Reproduce**
1. Go to settings
2. Set custom value between 5.00 - 5.1% in 0.01% steps
4. See error for 5.02% and 5.06% - `Enter a valid slippage percentage`

**Expected behavior**
`Your transaction may be frontrun should` be shown

**Screenshots**
<img width="316" alt="Bildschirmfoto 2021-04-08 um 11 02 38" src="https://user-images.githubusercontent.com/34510341/114000077-f0d68000-985a-11eb-8b3e-3bca4d0f5fa8.png">
<img width="325" alt="Bildschirmfoto 2021-04-08 um 11 02 32" src="https://user-images.githubusercontent.com/34510341/114000091-f59b3400-985a-11eb-9e4a-7809c01168bd.png">
<img width="320" alt="Bildschirmfoto 2021-04-08 um 11 02 47" src="https://user-images.githubusercontent.com/34510341/114000102-f764f780-985a-11eb-802e-5659f30c5f18.png">
...
<img width="317" alt="Bildschirmfoto 2021-04-08 um 11 02 58" src="https://user-images.githubusercontent.com/34510341/114000117-faf87e80-985a-11eb-91b0-358a04ce8074.png">

**Comment by annamsgeorge** [comment]
<img width="369" alt="Screenshot 2021-05-26 at 13 30 39" src="https://user-images.githubusercontent.com/33424780/119652584-91422d00-be26-11eb-8bb4-43376e693157.png">
I see a different issue here: We shoudln't display the text "your order might be front run". This can't happen in GP, I guess we copied this from Uniswap but it doesn't apply in GP. I will create a new ticket for this.

**Comment by annamsgeorge** [comment]
--> opened new issue for my point, suggesting to remove the error message:
Wrong message about slippage and being front run #675

**Comment by elena-zh** [comment]
The issue with `5.02` and `5.06` slippage percentages is still reproducible in v.0.17: slippage value is reverted to a previous one when enter these amounts.

**Comment by MareenG** [comment]
Not reproducible in v1.0.0 closing it

**Comment by elena-zh** [comment]
I'm able to reproduce the issue in v.1.0.0
https://drive.google.com/file/d/1wrbyzc-cUpiDBNya0so3wJEDGejXFfYc/view

**Comment by MareenG** [comment]
True, it still reverts but doesn't show enter a valid slippage percentage anymore
