### ISSUE TITLE
Invalidate cache on new version

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#400]
Multiple people had cache issues being "stuck" with an older version of the UI.

The task would be to have every new release somehow force the browser to download the latest version.

Might need to check with devops to do that in the uploaded static files AND/OR do some hashing in the build files.

**Comment by anxolin** [comment]
@davidalbela and I spent some time yesterday trying to debug this. 
I see the headers are ok, theoretically the index.html is not being cached, and the static files like the JS has a hash that would change if the content changes.

We saw that there can be some propagation times between zones.

In our tests, new versions were automatically updating the version. Tests take quite some time cause generating versions is quite slow, I suggest we keep an eye on this, and do a check on every version we do and try to document in which browsers and conditions this happens, so we can find the pattern.
