### ISSUE TITLE
Click wrap

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#444]
Similar to what the Safe has:
![image](https://user-images.githubusercontent.com/2352112/111311409-7dc45a00-865e-11eb-9f8c-6bd5f630ef8d.png)

Sister issue of https://github.com/gnosis/gp-ui/issues/303

**Comment by elena-zh** [comment]
Hey @anxolin ,  @biocom , @alfetopito , could you please take a look into the issue and clarify whether we still need to implement this?
If not, we can close the issue..

**Comment by alfetopito** [comment]
It was a legal question whether we'd need to have it.

I assume by now we are not doing it.
If we ever do we'll re-open.
