### ISSUE TITLE
Review Fees Exceed from amount

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#452]
**Description**
Improve message/tooltip when the trade is too small. 

**How to Reproduce**
1. Select DAI in the `From`, and WETH in the `To`
2. Input 0.1
3. Observe the tooltip next to the Fee

**Details**
![image](https://user-images.githubusercontent.com/2352112/115059000-342d9000-9ee6-11eb-9e33-23cbb5473ca1.png)

* I think this message in the tooltip is a bit strange (the zero fees part).
* Also the label is wrong (although this part was addressed already in other PR)

**Proposal**
Imo, it should be using the same tooltip as this:
![image](https://user-images.githubusercontent.com/2352112/115059199-7fe03980-9ee6-11eb-9d74-5f504bf135c6.png)

We could show the before fee as the FROM, then we show the fee (that is bigger). Then in the total we show a negative number, and we include a message explaining that the sell amount is too small.

I think this can be problematic if we are not clear. In uniswap you can trade as little as you want. 

cc: @annamsgeorge @MareenG @alfetopito @michelbio

**Comment by annamsgeorge** [comment]
I agree this is not ideal, but rather than trying to improve this particular part, I would rather spend the time on doing a UX review now of different mockups previously designed by Michel, iterating on them, and only when we are confident about a new solution actually implement it.
