### ISSUE TITLE
Token list displayed twice

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#460]
**Describe the bug**
The GP Rinkeby token list is displayed twice

**Screenshots**
<img width="424" alt="Bildschirmfoto 2021-04-20 um 10 36 01" src="https://user-images.githubusercontent.com/34510341/115365168-6aa82b00-a1c4-11eb-96d3-72e044361bb8.png">

**Comment by anxolin** [comment]
Not for me, 
![image](https://user-images.githubusercontent.com/2352112/115768307-6e95a200-a3aa-11eb-9557-e5598d905650.png)

Anyone else having this issue? @annamsgeorge @alfetopito

**Comment by alfetopito** [comment]
Hmm nope.
Tried around switching between networks and couldn't see the double entry.
I wonder if this is a race condition or an older version stored in local storage.

**Comment by MareenG** [comment]
I still had it this morning but after clearing all site data it was removed.

**Comment by MareenG** [comment]
...and it is back 
<img width="545" alt="Bildschirmfoto 2021-04-23 um 11 24 43" src="https://user-images.githubusercontent.com/34510341/115850860-9aef0400-a426-11eb-8fd5-c7f380581e60.png">
Clearing all site data doesn't remove it anymore

**Comment by annamsgeorge** [comment]
hmm doesn't happen for me either. Any chance it only happens on Rinkeby? Then I wouldn't care too much

**Comment by MareenG** [comment]
Yes, so far it looks like only a Rinkeby issue
