### ISSUE TITLE
Show WETH always as the first currency in the list

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#465]
**Description**

When you select tokens in the token selector, ETH is the first item in the list.

ETH is not directly supported. I believe it's ok to be one on the top (or second element), however WETH should be the first element in the list and is not.

**Describe the solution you'd like**
- Make sure WETH is the first token (or wxDAI in xDAI network)
- Make sure ETH is the second token

**Describe alternatives you've considered**
We could argue that since ETH is not supported, it shouldn't even be in 2nd position, however, many users will have ETH and will want to use it for wrapping, it is very relevant currency so it's good to be shown in second position. 

Additionally, it's good to show ETH and WETH balance next to each other. 

cc/ @annamsgeorge

**Comment by elena-zh** [comment]
It seems to be already implemented

**Comment by alfetopito** [comment]
Agree, task is obsolete with the addition of "common tokens" on top of the list.
