### ISSUE TITLE
Add "Analytics" to top right "..." menu

### ISSUE THREAD

**Issue by annamsgeorge** [gnosis/cowswap#477]
(Not needed before launch) 

Once Ben has created the Dune Dashboard for CowSwap analytics, we can add it to the top right "..." menu as "Analytics" - linking to the Dune Dashboard.

**Comment by annamsgeorge** [comment]
Lets reevaluate how good the statistics look on us after launch before we add it to the UI :) - would only add it once we have decent numbers

**Comment by anxolin** [comment]
Done
