### ISSUE TITLE
Slight delay with wrong intermediate notification

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#484]
**Describe the bug**
If I chose a token when newly accessing the website or refreshingit,  it takes a short while until the trade info is shown.
This isn't a big issue, however, during that period the info `Insufficient liquidity for this trade` is shown

**How to Reproduce**
1. Go to CowSwap or refresh CowSwap
2. Select a from and to token
3. Insert any amount into the from input
4. for a short period of time `Insufficient liquidity for this trade` shows up until the trade info is displayed
5. For the same token pair this doesn't happen again until you refresh the website
6. When picking a new to token is happens again

**Expected behavior**
`Insufficient liquidity for this trade`shouldn't appear while loading the trade data

**Screenshots**

https://user-images.githubusercontent.com/34510341/115673324-cb626f80-a34c-11eb-80fb-15fa2ff570f1.mov

**Note**

I think this isn't a big issue for the upcoming release but might be good to look into once things are more calm

**Comment by anxolin** [comment]
Yep, there's a small time this happens. I think it's because we don't have the data yet, and this is how we show it. 

We would need to better handle the loading state. @W3stside could you help us to review this?

**Comment by MareenG** [comment]
I was assuming that it is connect to loading the data. If there is a quick fix would be cool to address it but if it takes longer it is sth that can wait until after the release.

**Comment by elena-zh** [comment]
Seems to be not reproducible in v 0.17
