### ISSUE TITLE
Add recipient remains after disabling expert mode 

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#505]
**Describe the bug**
If I open the add send and disable the expert mode. The send to a reciepient field sremains and I can send it to another address eventhough the expert mode was disabled. 

**How to Reproduce**
1. Enable the expert mode
2. Click on add a send
3. disable expert mode
4. Enter recipient address
5. Trade
6. Tokens get send to recipient

**Expected behavior**
I would assume that with disabling the expert mode this feature would be removed as well

**Screenshots**
<img width="468" alt="Bildschirmfoto 2021-04-23 um 10 48 00" src="https://user-images.githubusercontent.com/34510341/115846380-2023ea00-a422-11eb-94fc-a1d82adc70d4.png">

**Comment by anxolin** [comment]
Not 100% related to this, but we could solve this when we implement this other one https://github.com/gnosis/gp-swap-ui/issues/578 (not planned super soon, but I think it would be interesting)
