### ISSUE TITLE
Price Update

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#534]
**Is your feature request related to a problem? Please describe.**
I encountered a price update for the first time.It came up quite unexpected and I was wondering what the prior price was. Might be cool to display the old price or more prominent if it is already displayed

**Comment by anxolin** [comment]
this uses uniswap default behaviour. 
It's reasonable, but i'm not sure if users will appreciate this enough to make the effort. 
I would wait for feedback for this one. 

cc/  @annamsgeorge

**Comment by anxolin** [comment]
Now we show clearly when we update the price, the nose picking cow loader and a shining effect.

We have some loading indicators. It feels way better, closing, please reopen if you still feel we should change something.
