### ISSUE TITLE
Every other moooh missing

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#553]
**Describe the bug**
On Mobile some mooohs are missing

**How to Reproduce**
1. Open MM app, go to the browser and then insert the Cowswap url
2. Do a few trades
3. Not all moohs happen

**Expected behavior**
After signing a trade and after a succesfull or failed trade one should hear a moooh

**Additional context**
I used a Redmi Note Pro8 (Android) 
Also I noticed that it is quite volume sensitive. One needs to put the volume quite high. However, even for max vol some moohs are missing.

**Comment by elena-zh** [comment]
@MareenG , I also have noticed that I cannot hear sounds in iOS
I user iPhone 12 mini with 14.6 iOS, and I have not managed to head sounds of transactions/CowGame
