### ISSUE TITLE
ETH/WETH flow not shown if input is higher than the balance

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#558]
**Describe the bug**
If the input is higher than the ETH balance the ETH/WETH workflow is not displayed 

**How to Reproduce**
1. Go to Cowswap
2. Chose ETH as from token
3. Chose any other to token
4. Insert ETH value that is higher than balance

**Suggested behavior**
It might be good to always display the ETH/WETH workflow when choosing ETH as a from token. 
The User might have enough WETH to do the trade and should be informed that he should switch to WETH

**Screenshots**
<img width="493" alt="Bildschirmfoto 2021-04-29 um 10 36 35" src="https://user-images.githubusercontent.com/34510341/116524838-227dbc80-a8d8-11eb-8a93-7a216b4d58fd.png">
<img width="444" alt="Bildschirmfoto 2021-04-29 um 10 36 42" src="https://user-images.githubusercontent.com/34510341/116524846-24478000-a8d8-11eb-8b68-c9b0038ed5e9.png">

**Comment by biocom** [comment]
Thanks for this ticket @MareenG 

- I understand your point about anticipating the user that they have WETH to trade with. 
- The way I see it, in this flow the user is dealing with ETH and ETH amounts. If you input more ETH than your balance, you simply can't continue with that trade (insufficient balance). The question is, should we at that point ask the user to switch to WETH? Only if the input amount (1 ETH from your example) is exactly available in their WETH balance?

---

**My current assumptions:**
- A user who already owns WETH, has either a good understanding of what WETH is and is aware of their WETH balance **or** they at least wrapped their ETH once. I'd assume this user is aware of how to switch themselves to WETH.
- It will not make sense to show our existing 'WRAP your ETH' component, if they are inputting more ETH than their balance (as per your example above).

That being said, it would be good to help the user when needed. I see two types of users:
1. A user **wants** to explicitly only use ETH for their trade. They are not interested in using their existing WETH balance.
2. A user for some reason picked ETH and isn't aware they have WETH to trade with instead.

---

**My suggestions based on yours:**
1. A very simple approach: Show the 'SWITCH TO WETH' button next to the 'INSUFFICIENT ETH BALANCE' when they have sufficient WETH for their original inputted (ETH input amount) trade.
2. A more elaborate approach: Clarify that indeed, they have insufficient ETH balance for this trade, but they do have sufficient WETH for that same trade + the SWITCH TO WETH button.

**Comment by anxolin** [comment]
I feel this is and edge case, only make sense to send the user to WETH in this case if he has enough WETH. 
And I also think that the user is already familiar on ETH/WETH logics if he has WETH

Technically this message is correct imo, we oriented the workflow to make the user select the exact trade he wants to do (this is why he selects also the buy token). If he goes above the balance, we show insufficient balance because the trade cannot happen --> coherent with all the other tokens
