### ISSUE TITLE
Please don't moooooooo more

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#565]
**Description**
Let the user silence the moooooo

**Describe the solution you'd like**
When you trade the first time, it moooos, but the confirmation modal would show you a sign to silence the Cow.

I would let the user silence:
- All sounds!
- Just the moooooo when you send the transaction. this way we can still hear the success/error moooooo 

It would be nice to have it both:
- In the settings as two switches. If you switch all off, of course also switches the success/error trade mooooo
- In the confirmation modal you get after signing the tx

**Describe alternatives you've considered**
One independent but fun feature to do, is to let the user use his own mooooo sounds. 

**Additional context**
![image](https://user-images.githubusercontent.com/2352112/116554615-b01ed380-a8fb-11eb-8b67-681053df1ff7.png)

**Comment by alfetopito** [comment]
Duplicate of https://github.com/gnosis/gp-swap-ui/issues/561
Or vice-versa

**Comment by anxolin** [comment]
People love it!
