### ISSUE TITLE
Add Recipient switch in Settings

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#578]
**Description**
The recipient is currently enabled when you enable advanced mode. 

I think it would be nice to add a toggle for adding the recipient address, so users that want to send to another address can do so without in a simpler way.

Also, it would make it more clear that this option is available, instead of being hidden behind the "advanced" one.

**Comment by MareenG** [comment]
ParaSwap over this feature. I think it would be great to implement this. 
<img width="231" alt="Bildschirmfoto 2021-11-03 um 15 46 31" src="https://user-images.githubusercontent.com/34510341/140083145-324e0b47-6133-4f82-86a4-95dad29c8885.png">

**Comment by ramirotw** [comment]
@alfetopito @MareenG @alongoni following the case of ParaSwap, they have a 4 step flow:

1. Swap & Transfer toggle
2. Click in `Set address` button
3. Paste the address in the modal's input
4. Check the confirmation checkbox

![image](https://user-images.githubusercontent.com/3328006/143464695-892a73a2-dc70-46dd-a853-2f2b313e2576.png)


What do you have in mind for CowSwap?

**Comment by biocom** [comment]
Was asked to share my comments here:

> In my view the main question should be: Is this feature used by the majority of users or only a small subset of user?
> 
> If only a small subset, are these the same type of users who use 'expert' mode features? If yes, I'd keep them hidden in settings to toggle on/off
> 
> Otherwise, I'd opt for a similar solution as Paraswap "Swap & Transfer".
>
> The sole reason why I think this should not be exposed by default, is mainly to keep the initial swap container as compact and lean as possible.

**Comment by alfetopito** [comment]
Based on Michel's comments, I've changed my mind and agree that we should use the initially proposed idea.

Add the toggle only to the settings and no further confirmation.

If the toggle is on OR in expert mode show the button
![Screenshot from 2021-11-25 07-47-43](https://user-images.githubusercontent.com/43217/143487082-0226d9b5-7d2d-40ac-ab70-f27facbd3e05.png)

Otherwise keep does not render it in the page

**Comment by anxolin** [comment]
For me both options are fine: switch in the setting or some way close to paraswap (or close to what we have in expert mode). 

I feel the sentiment is have it in the settings, and i think that might be even easier in terms of implementation.

Both have pros/cons. Michel, what would you intuition tell you is our best lucky guess

**Comment by ramirotw** [comment]
So to recap:

1. The `Toggle recipient` on/off button will be in the Settings modal below the `Toggle Expert Mode` 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/3328006/144656786-9938805a-52af-4e12-8a3c-5e06db64b6a1.png">
2. When enabled, the Swap screen will show the `Add a send (optional)` button, same as in the Expert mode 
![image](https://user-images.githubusercontent.com/3328006/144656953-2ab8e284-c19f-41b6-b68a-900ea9f62b65.png)

**Comment by biocom** [comment]
@ramirotw Yes. The question then is, if we enable the recipient field _automatically_, whenever a user toggles Expert mode **on**.

**Comment by anxolin** [comment]
Yes @ramirotw 

> @ramirotw Yes. The question then is, if we enable the recipient field automatically, whenever a user toggles Expert mode on.

I would not do it. Since it's in it's own setting, then is best to make expert mode, and add recipient a separated feature.
The UI would need to remember the user setting (persist in the browser), although that probably will happen by default.
