### ISSUE TITLE
Approving tokens are pending forever

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#584]
**Describe the bug**
Issue approving tokens. Pending forever.

This is kind of a more severe version of #584, and potentially they could both be solved by the same solution.

**How to Reproduce**
1. Select TOKEN-A in the FROM, where TOKEN-A is a token you haven't approved yet
2. Select any other token in the TO
3. Send the transaction to enable the TOKEN-A for trading
4. Before the transaction is mined, cancel it using metamask
5. Observe how the transaction is loading forever

**Expected behavior**
Ideally we would detect this situation

We could review the options

**Comment by anxolin** [comment]
@W3stside can you review the options?

The first option that come to mind is:

**1. Keep track of pending tx**
For all pending tx, we keep also track of what is their nonce (we keep track only of their hash right now). 

**2. Check the mempool**
Then if we see a tx with a higher hasPrice in the mempool that is the replacement tx.

Once we know the replacement tx, I understand that we can mark the previous tx as canceled/canceling (depending if it's confirmed or not)

Once we see the cancelation/increase-gas-price transaction, we can create a new pending transaction (so this tx goes to step number 1).

**3. Cancellations**
Cancellations is an special case we should detect. Normally is a tx wich has no data. We should show in the description that this is a cancelation.

## Some additional consideration
It's possible that the cancelation or the increase gas are not mined, and instead the original tx is. In this case, we would show:

For example for "Canceling approval"
* [replacement tx] `Cancel approval of WETH` --> `Failed cancelation: Approve WETH`
* [original tx] ---> `Approve WETH (trying to cancel)` ---> `Success`



**Challenge: Recursive nature**
This is a recursive problem, you can increase gas price 5 times, and then cancel. The key afaik is to keep track of the nonces. I would think we only need to show the first and last transaction.


## Regarding the UI
@michelbio how would you show nicely this information here?
![image](https://user-images.githubusercontent.com/2352112/116975023-41f15c80-acbf-11eb-86a1-cf2a792dcdfd.png)

**Comment by anxolin** [comment]
Thanks for the detailed info, yep, we thought about doing something in this lines. However, we don't want to discard using using a third party solution which gives you cancelation and replacement functionality already.

Reasons to at least consider it:
- It can make development way shorter. The proposed solution will have some race conditions, we have to do also wrapping or any other operation we do onchain in the future.
- These services will be more reliable, events in frontend has been a bit unreliable, and we will need to handle reorgs and other edge cases related to race conditions for a quite small functionality
- I consider this functionality a "satelite" functionality. Good to have, but if it's not working it should not break the app. So trusting this to a service i find it ok.
- These service have smarter logics and watch the mempool already, so no need to wait until the tx is mined, better UX
- I believe, they give you already information if it's a cancelation or a replacement, and also the new transaction. This would allow us to give this information with low effort and cost

Not saying we should use these services, but at least I feel is justified to evaluate their use

**Comment by ramirotw** [comment]
> However, we don't want to discard using using a third party solution which gives you cancelation and replacement functionality already

@anxolin what 3rd party services did you evaluate for this? I've used Blocknative API before and it offers speedups/canceled txs https://docs.blocknative.com/webhook-api#transaction-events-state-changes

I can work on a draft to integrate it to see how it works.

**Comment by alfetopito** [comment]
Addressed on https://github.com/gnosis/cowswap/pull/1302
