### ISSUE TITLE
Approve and Swap buttons are disabled (edge case)

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#585]
**Describe the bug**
There's an edge case happening when you approve a token, and then you switch to another account. The other account won't let you do anything (you can't approve or swap with it).

The user is forced to refresh the browser, which solves the issue.

**How to Reproduce**
1. Select a token that is not enabled for trading
2. Approve the token
3. Switch to another account that has:
- balance in that token
- hasn't approved yet the token
4. See that once you change to the other account, you cannot do anything: The approve button is disabled

**Expected behavior**
Each account state should be independent.

**Screenshots**
![image](https://user-images.githubusercontent.com/2352112/116971872-83cbd400-acba-11eb-8ec7-8e20a4bbb43e.png)

**Additional context**
This came reported as feedback by a CowSwap user (thanks @1man.1dog.1cat)

**Comment by anxolin** [comment]
Moving this task up, since I saw it in several feedbacks already

**Comment by elena-zh** [comment]
Another case is that buttons become disabled when you approve a certain amount of tokens to spend.
On the video below I approved 0.003 WETH to spend, so when I enter 0.004 WETH to trade I get SWAP and Approve buttons disabled
https://drive.google.com/file/d/1n8yD-PAwgX4POuJ9ATQK5lXSwVD2YnNB/view

**Comment by fapesteguia** [comment]
@maria-vslvn @matextrem Can you retest this in order to check if you can reproduce it?.

**Comment by elena-zh** [comment]
Btw, I have not faced the issue for a month or so.

**Comment by elena-zh** [comment]
No longer reproducible.
