### ISSUE TITLE
Stuck in Confirmation 

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#594]
**Describe the bug**
The Waiting for Confirmation modal does not disappear after signing the transaction. 
Swaps are not executed.

**How to Reproduce**
1. Connect to CowSwap with Trust wallet via wallet connect
2. Place a swap and confirm swap 
3. Sign transaction
4. The wait for Confirmation modal  doesn't disappear 

**Expected behavior**
The confirmation modal should disappear and the swap should be executed. 
_Note: Earlier today ( 11:30am) it worked nicely_

**Screenshots**
Keeps spinning and nothing happens.

<img width="660" alt="Bildschirmfoto 2021-05-05 um 11 58 18" src="https://user-images.githubusercontent.com/34510341/117126481-1b085880-ad9b-11eb-8848-bff9567cb6b6.png">

**Additional context**
- According to the Trust wallet the transaction was signed
- the swap is not executed
- I can get back to the landing page by closing the modal

**Comment by MareenG** [comment]
The issue was solved once I disconnected and connected again

**Comment by alfetopito** [comment]
I had a bunch of issues with Trust via WC and their dApp browser.
It seems like their RPC node is very unstable and there are errors happening more often than not :(

Not very optimistic about being able to solve them on our side without some significant effort.

**Comment by anxolin** [comment]
okok, we can see if we can do something about it, or asses how often does it happen. this wallet is quite important, the few tests i did with trust worked fine for me
