### ISSUE TITLE
Wrong notifications are back

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#596]
**Describe the bug**
Every now I get two different notification modals. 
Recent activities shows wrong status of trade
_Note: this only happened in PRs or on dev_

**How to Reproduce**
1. Cowswap
2. Place several trades observe
3. Every now and then two confirmation modals with different status appear
4. Recent activities displays trade as expired
5. Explorer indicated that the trade was executed

**Expected behavior**
- Only one modal should appear, should be either successfull or fail
- explorer and recent activities should show the same status

**Screenshots**
Modals:

<img width="353" alt="Bildschirmfoto 2021-05-05 um 13 19 46" src="https://user-images.githubusercontent.com/34510341/117134116-70496780-ada5-11eb-9a26-daf379c71af3.png">

Recent activities

<img width="434" alt="Bildschirmfoto 2021-05-05 um 13 19 56" src="https://user-images.githubusercontent.com/34510341/117134163-82c3a100-ada5-11eb-9e4f-9ef84e852db5.png">

Explorer

<img width="1425" alt="Bildschirmfoto 2021-05-05 um 13 20 05" src="https://user-images.githubusercontent.com/34510341/117134231-9e2eac00-ada5-11eb-8e70-579c94ce410c.png">

https://gnosis-protocol.io/rinkeby/orders/0xda9f1b3887298dc49f633f9e147311ebb279140e0982251f626c575ec37c37e28bc0fe84022542e1611ff252090028df741ad67060927db7

**Comment by anxolin** [comment]
Strange, @W3stside tested this very much. Maybe something changed in our last release?
