### ISSUE TITLE
List most popular tokens on top 

### ISSUE THREAD

**Issue by annamsgeorge** [gnosis/cowswap#599]
Not urgent at all, but a nice touch from Uniswap v3: they are listing the most popular tokens on top so users don't have to scroll through the list to find them. 
I think it makes sense to pick the all-time most popular tokens (ETH, WETH and stable coins) as they did it. There are other tokens that are popular at times, but that would have to be updated regularly, so I would recommend putting those tokens on top that are consistently the top traded ones :) 

![Screenshot 2021-05-06 at 11.31.44.png](https://images.zenhubusercontent.com/6059d7cca7474e5d8699f72c/6f226d87-bd6d-4a77-962f-f265ed54b939)

**Comment by anxolin** [comment]
Maybe we get this for free if we try to update. 
We can do an attempt to se how much breaks the new changes into our codebase.

**Comment by annamsgeorge** [comment]
If we make this change, then this issue is also solved: 
Show WETH always as the first currency in the list #465

**Comment by elena-zh** [comment]
Implemented in #1053

**Comment by anxolin** [comment]
Implemented in v0.17. We can revisit the selection we do. Maybe we want to add remove some. Closing this one. Open if you want to modify the list
