### ISSUE TITLE
Price impact

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#617]
**Describe**
Price impact was removed in https://github.com/gnosis/gp-swap-ui/pull/614 because it need to be reevalulated after integrating the API

Some people suggested we shouldn't display it, although imo it has some utility. It helps to protect the user from choosing a bad price.

**Describe the solution you'd like**
I would calculate it using the spot price of the API. 

For that, we need to query the spot price also on every time we query for the price. Then the price impact would be the relationship between the two prices. 

**Describe alternatives you've considered**
- Removing it
- Leaving it as suggested above

**Additional context**
Crypto Orca suggested in the chat this is a confusing concept introduced by uniswap. That is a slippage. But they also allow to modify the slippage in the settings, so it's kind of a mixed concept.

**Comment by anxolin** [comment]
David, this is our most important issue right now I believe. 
Now u managed to merge UniV3 we should try to add as many protection to our users:

Some questions that you might 
 - Do we prevent them from trading? In which cases?
 - Where and how we get the price impact? 
 - Is price impact absolute, only depending on the sold/received tokens, or does it use the impact depending on the path or price feed used?
 - What visual indications we show? i.e. Should we show it also in the open orders, or that's overkill?

**Comment by W3stside** [comment]
Uni price impact is based on fiat values:
```
function computeFiatValuePriceImpact(
  fiatValueInput: CurrencyAmount<Token> | undefined | null,
  fiatValueOutput: CurrencyAmount<Token> | undefined | null
): Percent | undefined {
  if (!fiatValueOutput || !fiatValueInput) return undefined
  if (!fiatValueInput.currency.equals(fiatValueOutput.currency)) return undefined
  if (JSBI.equal(fiatValueInput.quotient, JSBI.BigInt(0))) return undefined
  const pct = ONE_HUNDRED_PERCENT.subtract(fiatValueOutput.divide(fiatValueInput))
  return new Percent(pct.numerator, pct.denominator)
}
```

**Comment by anxolin** [comment]
> which is based on USDC price (they just query the currency against USDC using their own swap to get USDC price).

Cool, so they use USDC price and their own price.
And do they get the USD estimation using a mid market price or an execution price of a representative amount (like 1 ETH or sth)

> So an easy approach for us would be to keep everything the same and just change their function useUSDCPrice to use our API / price feeds

@fleupold @nlordell mentioned they would consider that maybe they would add USD estimation in the price endpoint as other protocols do (matcha, 1inch, paraswap). 
This feature is nice for others using our API, although probably we would prefer to use our own estimation to prevent different USD estimations for our different price feeds (Paraswap has its own, is best to be coherent with the value of the tokens).

If we assume the USD estimation doesn't change that much and is just an absolute amount (not volume related), we could maintain in the UI the current USD price for the selected tokens (i.e. update every 30-60sec). Then when we get the price estimation we can already compute in the client the price impact and USD estimation of the sold/bought tokens.

**Comment by alfetopito** [comment]
> And do they get the USD estimation using a mid market price or an execution price of a representative amount (like 1 ETH or sth)

For reference, this is how it's done https://github.com/gnosis/cowswap/blob/e137b4bd5a9daa7d6e7d0080c50d2f56f4489262/src/hooks/useUSDCPrice.ts

They use their mid price https://github.com/gnosis/cowswap/blob/e137b4bd5a9daa7d6e7d0080c50d2f56f4489262/src/hooks/useUSDCPrice.ts#L42-L45

And it's used with the input values https://github.com/Uniswap/uniswap-interface/blob/dfe550c43bc383ac8ec61d4531ca2ca9aa912196/src/pages/Swap/index.tsx#L143-L144

**Comment by anxolin** [comment]
Paraswap does this, pls take it into account. 

* Yes, if it's 15% or more price impact, (this limit can be changed when using the API directly) --> `Uni does sth similar`
* We use CoinGecko mostly (and also ChainLink for a few coins) --> `is this sth we are interested, how do we deal with rare tokens?`
* Our fallback is to use ParaSwap's internal pricing algorithm to sell 1 token for ETH ignoring gas, and then use the ETH/USD price ---> `do we need to change params for the call to paraswap for excluding gas?`
