### ISSUE TITLE
Appzi offline mode

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#639]
Load JS from a bundle, to avoid injecting external JS files.

**Comment by elena-zh** [comment]
Seems that the app data is stored in the local storage and the app works in the offline mode for a while. 
@anxolin , @alfetopito , can we close this?

**Comment by alfetopito** [comment]
@elena-zh this is for Appzi, the feedback service

This issue is about bundling Appzi code with the deployed CowSwap instead of fetching it on page load
