### ISSUE TITLE
amountWithFee or withoutFee confusing

### ISSUE THREAD

**Issue by W3stside** [gnosis/cowswap#651]
comment @anxolin
I always feel confused by the terminology With/Without. I think we should use After/Before

Note that with fees, can mean:
- "With" plus fee (gross amount, aka before fees)
- "With" fee applied (net amount, aka after fees)

_Originally posted by @anxolin in https://github.com/gnosis/gp-swap-ui/pull/642#discussion_r634742045_

--

change to `inputAmountAfterFee` and `inputAmountBeforeFee` etc

low prio

**Comment by elena-zh** [comment]
Seems that the issue is no longer relevant
![image](https://user-images.githubusercontent.com/70885163/154262996-8ed38f7f-a131-45b2-8eef-b82ce922e424.png)
