### ISSUE TITLE
Issue with dancing values 💃

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#662]
**Describe the bug**
The FROM or TO inputs in the widgets get sometimes a very wrong value. Then the issue is solved automatically.

**How to Reproduce**
1. Select any token pair. Input a value in the TO to make a buy order
2. Then input another very different value in the FROM
3. Notice how the old from value "jumped" to the TO, then once the new TO is calculated, the value is updated to the right value.

Maybe we should just make it blank the field when is not calculated yet? (or a spinner)?

https://user-images.githubusercontent.com/2352112/118989451-5782a980-b982-11eb-8d3c-2dffe809bdce.mp4

**Comment by annamsgeorge** [comment]
I think a spinner is better, that shows the user that there is some progress.
