### ISSUE TITLE
Wrong error message 

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#665]
**Describe the bug**
Wrong notification if time to sign transaction exceeds transaction deadline
As reported in Slack:
https://gnosisinc.slack.com/archives/CSGLUC1BN/p1621547912055400

**How to Reproduce**
1. Set time to 1 min
2. Swap, etc
3. Don't sign yet. Hold it for a few minutes
4. Sign order

**Expected behavior**
`Valid to is in the past `Should be shown instead

**Screenshots**
<img width="330" alt="Bildschirmfoto 2021-05-21 um 10 32 06" src="https://user-images.githubusercontent.com/34510341/119107751-d1b53b80-ba1f-11eb-95af-7d4bc81cd66b.png">

**Comment by alfetopito** [comment]
Fixed by #666

**Comment by W3stside** [comment]
demon issue

**Comment by elena-zh** [comment]
@MareenG , the issue seems to be fixed
