### ISSUE TITLE
Colour contrast for block number on bottom right

### ISSUE THREAD

**Issue by bh2smith** [gnosis/cowswap#667]
Is difficult to see the current block in the bottom corner because of the contrast with the grass colour.

![Screenshot 2021-05-21 at 11 34 49](https://user-images.githubusercontent.com/11778116/119116678-c31f5200-ba28-11eb-97d4-1559ef262b51.png)

**Comment by alfetopito** [comment]
cc @biocom

**Comment by biocom** [comment]
> cc @biocom

Fixed in #622
