### ISSUE TITLE
[WalletConnect] Change of networks in the wallet not reflected

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#671]
## Steps to reproduce
1. Connect with MM mobile via WalletConnect
2. Balance loads, all good.
3. Switch networks in the app
4. Not reflected in the UI at all
    Had to disconnect and connect again in the other network to make it work.

_Originally posted by @alfetopito in https://github.com/gnosis/gp-swap-ui/issues/633#issuecomment-848054622_

**Comment by elena-zh** [comment]
I think, the issue might be closed as after network switcher implementation a user is notified that a connected wallet does not supports network switching. 
![image](https://user-images.githubusercontent.com/70885163/140342416-ad56ff2a-dbaf-4b79-98d5-3d5ef66757b5.png)
