### ISSUE TITLE
Dark mode misc

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#681]
- issues with modals
- connect
- small things
- eth wrap component

**Comment by alfetopito** [comment]
- fix FAQ table 
![screenshot_2021-05-26_13-35-45](https://user-images.githubusercontent.com/43217/119727524-3eb54080-be27-11eb-814d-0bbae2914b1a.png)

**Comment by alfetopito** [comment]
From https://github.com/gnosis/gp-swap-ui/pull/692

- Privacy policy links
![screenshot_2021-05-27_07-26-53](https://user-images.githubusercontent.com/43217/119844259-22fc7980-bebd-11eb-88dd-8474da02321a.png)
- Privacy policy emphasized text
![screenshot_2021-05-27_07-28-16](https://user-images.githubusercontent.com/43217/119844319-2f80d200-bebd-11eb-8c93-dfc8a0a289e6.png)

**Comment by anxolin** [comment]
@biocom small one also related to DM: 
![image](https://user-images.githubusercontent.com/2352112/119874504-f7fa4000-bf25-11eb-864f-e20a9d3830a6.png)

**Comment by anxolin** [comment]
Tiny issue with the buttons, when they are disabled, the background matches the normal background, so they are invisible buttons:
![image](https://user-images.githubusercontent.com/2352112/120219702-ef627c00-c23b-11eb-8e23-1c7b5ccc049e.png)

**Comment by W3stside** [comment]
unsupported token:
<img width="490" alt="Screenshot 2021-06-08 at 11 26 19" src="https://user-images.githubusercontent.com/21335563/121332351-b1d2b280-c90f-11eb-82dd-755dc5ede47d.png">

**Comment by W3stside** [comment]
Fee when Fee Exceeds Amount
`FeeGreaterMessage` is component

![image](https://user-images.githubusercontent.com/21335563/121332537-dfb7f700-c90f-11eb-979c-c9584f0f9c50.png)

**Comment by biocom** [comment]
Empty toke image
<img width="202" alt="Screen Shot 2021-06-15 at 16 12 48" src="https://user-images.githubusercontent.com/31534717/122068247-8874c380-cdf4-11eb-9cd4-664043a7422e.png">

**Comment by biocom** [comment]
Issues addressed.
