### ISSUE TITLE
Figma design for USD estimation and Percentage

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#686]
Proposal for https://github.com/gnosis/gp-swap-ui/issues/686

Tricky part is the fee thing. We should consider the options, both for sell orders and buy orders.

**Comment by biocom** [comment]
Designs done and proposal preferences collected to move forward with integration.

**Comment by alfetopito** [comment]
@biocom can you share the links here for future reference?

**Comment by biocom** [comment]
Proposals:

**A.** USD est. only. Existing swap UI - Minimal | [Link](https://www.figma.com/proto/bcoZf5RIgVKDItdOaTZq18/GP-Swap?page-id=993%3A2&node-id=993%3A3&viewport=1220%2C-1235%2C0.11761524528265&scaling=min-zoom)
**B.** USD est. only. Existing swap UI - Expanded | [Link](https://www.figma.com/proto/bcoZf5RIgVKDItdOaTZq18/GP-Swap?page-id=993%3A2&node-id=1058%3A123&viewport=1220%2C-1235%2C0.11761524528265&scaling=min-zoom)
**C.** USD est. &amp; receive incl. fees. V3 UNI - Minimal | [Link](https://www.figma.com/proto/bcoZf5RIgVKDItdOaTZq18/GP-Swap?page-id=993%3A2&node-id=1060%3A158&viewport=1220%2C-1235%2C0.11761524528265&scaling=min-zoom)
**D.** USD est. &amp; receive incl. fees. V3 UNI - Expanded | [Link](https://www.figma.com/proto/bcoZf5RIgVKDItdOaTZq18/GP-Swap?page-id=993%3A2&node-id=1044%3A0&viewport=1220%2C-1235%2C0.11761524528265&scaling=min-zoom)

Moving forward with either proposal C or D.

**Comment by anxolin** [comment]
My prefered option would be D with a small change, I added it as a comment. 

@biocom, do you think we can show the buy order for option D, and share C and D with the broader team?
