### ISSUE TITLE
Metamask Android App connect issue

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#711]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2352112/119998947-824bae00-bfd1-11eb-9fcb-e495f857a0cf.png)

**Comment by alfetopito** [comment]
Tried again in my Android phone:
1. Reset Metamask app. Removed account, etc
2. Synced again with Browser extension
3. Connected to https://cowswap.staging.gnosisdev.com/#/swap via WalletConnect
4. Placed order

No issues

5. Connected via in app browser to https://cowswap.staging.gnosisdev.com/#/swap
6. Placed order

No issues either.

Maybe this is an issue that should be reported to Metamask team as suggested in that screen?
