### ISSUE TITLE
Autoconnect to last connected wallet

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#728]
**Description**
Auto-connect to last connected wallet.

Right now, it defaults to connect to Metamask or any other injected wallet instead of remembering what was your last connected wallet. 

**Proposal**
Save in the browser the last connected wallet, and make an initial attempt of using it before initiating the normal sequence of wallets.

**Additional context**
It's annoying that when you connect with Metamask, and Wallet Connect, then every time you come back to the website or refresh, it defaults to Metamask

The behaviour is inherited from Uniswap, but we can try to address it.

**Comment by elena-zh** [comment]
still reproducible in v.0.17

**Comment by anxolin** [comment]
Closing, thanks for noticiing the duplicate
