### ISSUE TITLE
Improve message when there's not price yet

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#730]
**Description**
When there's no price yet, and while we are loading the information we show "Insufficient Liquidity" message, which is misleading. 

In the following video we can briefly see that for a moment we show this message. When the backend is slow, we show it for a few seconds. When it's fast, it creates a flickery effect.
https://user-images.githubusercontent.com/2352112/120474836-f6f36380-c3a8-11eb-8955-ace322956bac.mp4

**Proposal**
@W3stside u can make a proposal since you were addressing the loading state. Maybe this is even handled now, pls confirm.

**Comment by W3stside** [comment]
confirming that it's something im aware of, will tackle
