### ISSUE TITLE
Executed Order shown as Expired

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#742]
**Description**
The order shows expired when it's in fact executed

It happens when the trade occurs while the dapp is closed.
When you open it again, they show as expired.

**How to Reproduce**
- Place orders
- leave/close page
- come back 30 minutes later
- Order filled, but get both moo sounds and both cards and in the Pending tab shows as order expired.

**Expected behavior**
Detect that they are executed, and change the state from expired to executed.
Also, don't show the double toast (expired + traded)

**Screenshots**
![image](https://user-images.githubusercontent.com/2352112/120987824-43121f80-c77e-11eb-8bac-225bb7c6d3bd.png)
![image](https://user-images.githubusercontent.com/2352112/120987834-460d1000-c77e-11eb-804e-7ba8a53b00ae.png)

**Additional context**
@W3stside solved a similar error. Afaik now we check the backend even after the expiration period. At least for a while. If it's confirmed later, we change the state.
Probably is because we stop checking after some time. 

Maybe in the initial warm up of the app, we can reevaluate all the canceled orders?

**Comment by alfetopito** [comment]
Somewhat related to what I'll do for cancelled orders.
I can take a look after/during that

**Comment by alfetopito** [comment]
Fixed by https://github.com/gnosis/cowswap/pull/753
