### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#776]
https://docs.google.com/spreadsheets/d/1R1ALTKw9wRcJz6JAISClr1hfJ8wpIUmcg29DXh8zTq4/edit#gid=0

- [ ] David
- [ ] Michel
- [x] Leandro

**Comment by alfetopito** [comment]
I've filled in the initial skeleton and added some stuff on top.

Check it out https://docs.google.com/document/d/1nsu_1wsNYOGTfd8SIdbDSwoVbZAQxYbQ6DD-uzqh9wg/edit

**Comment by alfetopito** [comment]
Pretty much done
