### ISSUE TITLE
Onboarding and development materials

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#777]
Onboarding new members:
- [x] Mod guide → David. Update improve the current doc
- [x] Deployments, dev process → Michel
- [x] Good practices, tips for the team → Leandro kick start, we all participate
- [x] Update Onboarding Frontend: https://docs.google.com/document/d/1p5J0JOKtOb_W98m4dFIhrd7VQlDmIEc6h3vCm6jbTbI/edit#heading=h.f4kcfdhgwb3b 
- [x] Quick look to the current onboarding
- [x] Small tasks for the beginning
i.e Batch graph, after all was his challenge

**Comment by alfetopito** [comment]
I have updated the previous onboarding doc https://docs.google.com/document/d/1p5J0JOKtOb_W98m4dFIhrd7VQlDmIEc6h3vCm6jbTbI/edit#
and created a new doc with rules https://docs.google.com/document/d/1MnECjqhwM0iCWDoVn5lENQ5e4LN69AIxbnvLJoQq8qo/edit#heading=h.jcp5mvc45b2s

Also updated the links doc with the most up to date info
