### ISSUE TITLE
Improve price estimation

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#780]
**Description**
Query prices from a dex aggregator (like paraswap or 1inch) to make sure we offer those prices.

**Proposal**
Still TBD, but one initial suggestion is to query both the API and a DEX aggregator, and we select the best price of the two.

**Additional context**
The backend price estimation has some difficulties adding new prices for the short term. We might want to add it in the front end so:
- It gives a faster response
- It gives users a better price. So we are as good as the dex aggregators but with less fees

**Execution**
- [x] Basic integration. Generalize price quote querying to allow multiple sources
- [x] Add paraswap
- [x] Do we need to timeout if the API is too slow? 

**Improvements for later** 
https://github.com/gnosis/cowswap/issues/841

**Comment by W3stside** [comment]
Thinking out loud:
- both queries respond same time, we take better of the 2
- one query comes in before the other, we take that one, replace it ONLY IF the next one comes in and is better, else skip
- keep 10s poll

pseudo code: `Promise.race([getGpApiPrice(params), getDexAggPrice(params)])`

thoughts? @anxolin @alfetopito
