### ISSUE TITLE
Quote fetch errors: Message improvement

### ISSUE THREAD

**Issue by biocom** [gnosis/cowswap#782]
For now the only scenarios we show this error message "Error loading quote. Try again later":

- User is offline/lost internet connectivity.
- Price feed is down

Any other scenarios? I wonder if these are the only two scenario's, if we could customize the message (as per my comment in #770 ) to make it more actionable. E.g.

- Offline - "Error - You appear to be offline."
- Price feed error - "Error - Can't reach price feed." (try again later...)

**Comment by anxolin** [comment]
Good point, I think it's important to make a good review on these cases. 

Simulating Offline is easy: 
![image](https://user-images.githubusercontent.com/2352112/123404635-56f4b880-d5a9-11eb-857f-301d6767b6db.png)


Simulating an error, is also easy, u just throw an error here: 
 - https://github.com/gnosis/cowswap/blob/d97e6cd506ee1b6ae9117d57757fa691a6f3059f/src/custom/utils/operator/index.ts#L201
- and here [const](https://github.com/gnosis/cowswap/blob/d97e6cd506ee1b6ae9117d57757fa691a6f3059f/src/custom/utils/paraswap.ts#L57-L57)


I can see we have currently an issue with error handling:

![image](https://user-images.githubusercontent.com/2352112/123403371-00877a00-d5a9-11eb-9e98-513e9df20643.png)

**Comment by anxolin** [comment]
I think this issue is fixed. Let me know if something is still unaddressed
