### ISSUE TITLE
Pending color styles to be fixed

### ISSUE THREAD

**Issue by biocom** [gnosis/cowswap#796]
<img width="486" alt="Screen Shot 2021-06-23 at 15 16 43" src="https://user-images.githubusercontent.com/31534717/123103264-1cb6da00-d436-11eb-978a-2fea49b5eff7.png">
<img width="472" alt="Screen Shot 2021-06-23 at 15 16 32" src="https://user-images.githubusercontent.com/31534717/123103276-1e809d80-d436-11eb-8d2d-c7c9730a1239.png">
<img width="450" alt="Screen Shot 2021-06-23 at 15 15 54" src="https://user-images.githubusercontent.com/31534717/123103281-1fb1ca80-d436-11eb-96fc-9ed751e0ea93.png">
<img width="493" alt="Screen Shot 2021-06-23 at 15 15 39" src="https://user-images.githubusercontent.com/31534717/123103284-204a6100-d436-11eb-9585-5057f23a8d96.png">
<img width="481" alt="Screen Shot 2021-06-23 at 15 15 10" src="https://user-images.githubusercontent.com/31534717/123103286-204a6100-d436-11eb-9c84-d36d829b1ec4.png">

**Comment by anxolin** [comment]
@biocom i'll move you this one to in progress since it's reference in your PR.

If you write in the PR closes #number then it will close automatically the issues when merged.

**Comment by biocom** [comment]
Yeah though these aren't addressed in any PR yet. Just things I spotted to be addressed in a future PR.

**Comment by anxolin** [comment]
ahh, ok, so i move it back to pending

**Comment by biocom** [comment]
![Screen Shot 2021-06-29 at 11.05.35.png](https://images.zenhubusercontent.com/5c3f06b5116ade5d16d9b8c2/aee8244a-ca39-4128-953c-aaf4e104e95b)![Screen Shot 2021-06-29 at 11.05.10.png](https://images.zenhubusercontent.com/5c3f06b5116ade5d16d9b8c2/10896d9a-e66c-4567-acde-a5500b7a8f21)
