### ISSUE TITLE
issue with broken invariant: negative number because of fee

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#799]
**Description**
Error with invariant

![image](https://user-images.githubusercontent.com/2352112/123110215-28a59a80-d43c-11eb-8486-8e0c4c4a870f.png)

It looks like this is the source of the issue:
![image](https://user-images.githubusercontent.com/2352112/123110230-2ba08b00-d43c-11eb-83c7-f190b74b39a7.png)

Likely cause the amount is smaller than the fee. And this creates a negative number which the library used by the SDK can't parse.

**Comment by alfetopito** [comment]
Same as https://github.com/gnosis/cowswap/issues/811?
So, fixed by https://github.com/gnosis/cowswap/pull/817?

**Comment by W3stside** [comment]
@anxolin closing this was fixed
