### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#811]
Trying to swap DAI on Rinkeby leads to white screen
Oddly this only happens for values between 20-29

**How to Reproduce**
1. Go to cowswap - Rinkeby
2. Choose Dai as From token 
3. Choose any other to token
4. See white screen

**Screenshots**

https://user-images.githubusercontent.com/34510341/123641110-2bc8ce00-d822-11eb-9488-9bd0229fe9b7.mov

**Additional context**
Only experienced this so far for Rinkeby DAI

**Comment by MareenG** [comment]
**Update**It also happens on mainnet eg. I was trying to swap DAI for UNI entered a value for DAI corrected my input and got the white screen. It only happens occasionally.

**Comment by MareenG** [comment]
I tested https://cowswap.exchange/#/swap

**Comment by anxolin** [comment]
This is related to https://github.com/gnosis/cowswap/issues/799 we thought it was not happening in production. We will do a hotfix for this asap.
