### ISSUE TITLE
Bad handling when the fee is unavailable

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#827]
**Description**
I belive the error handling for the fee is not right.

The service was down for a second, and I got a big error:
![image](https://user-images.githubusercontent.com/2352112/123939603-9439bb80-d998-11eb-967f-a1c94aa1f823.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/2352112/123939501-79ffdd80-d998-11eb-8045-04c79bb4c346.png)

**Comment by W3stside** [comment]
you didn't take the changes in develop in utils/operator:
https://github.com/gnosis/cowswap/blob/d12d109fe56282d906609f43cd6c40b607c54663/src/custom/utils/operator/index.ts#L187
and down

**Comment by W3stside** [comment]
fixed already in `release/0.16` branch, do we want to hotfix into 0.15.3 with this code first?

**Comment by anxolin** [comment]
No it's fine as long as it's in 0.16
