### ISSUE TITLE
Price seems incorrect, or it takes the fee into account

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#828]
**Description**
Theoretically, we show the price not taking the fee into account. 

However, here I used an amount too close to the fee, and I'm getting a very big price. So I think at some point we started to include the fee in the price:
![image](https://user-images.githubusercontent.com/2352112/123940185-348fe000-d999-11eb-9963-42d118e61499.png)

![image](https://user-images.githubusercontent.com/2352112/123940513-8c2e4b80-d999-11eb-8d29-99379edb765f.png)

**How to Reproduce**
1. Select BAL and USDT
2. Input 0.41 BAL
3. See the output
4. Increase the amount of BAL

Related to https://github.com/gnosis/cowswap/issues/822

**Comment by W3stside** [comment]
Saving some notes here, I don't think anythig is wrong with the price calc.

(Testing in V3 merge but the logic is ours thus the same as V2)
```
Selling 1 WETH <> DAI
/*
[useDerivedSwapInfo] Price quote:  2210331398835280682470
[useDerivedSwapInfo] Fee quote:  1680000000000000
*/

Input after fee (real input): trade.inputAmountWithFee.quotient.toString() >> "998320000000000000"
Output: trade.outputAmount.quotient.toString() >> "2210331398835280682470"

Display/Trade price: trade.executionPrice.toFixed(12) >> "2214.051004522879"

Manual calc:
1/(998320000000000000/2210331398835280682470)
2214.0510045228793
```

**Comment by anxolin** [comment]
I'm a bit concern cause in my screenshot, u can see how the price was 14K USDT

The price of BAL is around 25 USD
![image](https://user-images.githubusercontent.com/2352112/124595197-027ef200-de61-11eb-98c4-f318bcb39741.png)

I can reproduce this in production:
![image](https://user-images.githubusercontent.com/2352112/124595162-f8f58a00-de60-11eb-8bcd-42f0666f3bca.png)

If I increase the volume, the price get's better. Can you get to the bottom of this?

**Comment by W3stside** [comment]
![image](https://user-images.githubusercontent.com/21335563/125092563-60ae0e00-e0c9-11eb-9393-28adc235bb94.png)

GP Quote api for a small BAL amount, just barely above the fee:
ATOMS: 10888040435651072
EXACT:  0.010888040435651072
https://protocol-mainnet.gnosis.io/api/v1/markets/0xba100000625a3754423978a60c9317c58a424e3d-0xdac17f958d2ee523a2206206994597c13d831ec7/sell/10888040435651072
![image](https://user-images.githubusercontent.com/21335563/125093959-c2bb4300-e0ca-11eb-8562-4f6123934b53.png)

and for paraswap:
https://apiv4.paraswap.io/v2/prices/?from=0xba100000625a3754423978a60c9317c58a424e3D&to=0xdAC17F958D2ee523a2206206994597C13D831ec7&amount=10888040435651072&fromDecimals=18&toDecimals=6&maxImpact=100&side=SELL&network=1
![image](https://user-images.githubusercontent.com/21335563/125094284-09a93880-e0cb-11eb-8106-9040cb763786.png)

**Comment by W3stside** [comment]
discussed internally here:
https://gnosisinc.slack.com/archives/CPZA1AGKY/p1625842666050500

**Comment by W3stside** [comment]
it is NOT an issue on the FE side - the issue is that the pool sizes are small and we don't have hops.

For example: 0.0041 BAL for USDC > only 2 USDC in the pool, so 1 USDC is quote returned and 0.0041 BAL for 1 USDC is a terrible price.

To fix we could show a different error/warning about current price being bad and block trade

**Comment by anxolin** [comment]
In the thread you mentioned we discussed a solution to this problem. I think it would improve the UX if we do that
