### ISSUE TITLE
Wrong button text after buy order

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#830]
**Description**
After a buy order is placed the main button displays **fees exceed from amount** instead of **enter an amount**

**How to Reproduce**
1. Place a buy order
2. Confirm the trade
3. **fees exceed from amount** button appears instead of **enter amount**

**Screenshots**
Buy order: 
<img width="915" alt="Bildschirmfoto 2021-06-30 um 12 02 02" src="https://user-images.githubusercontent.com/34510341/123942645-a2d5a200-d99b-11eb-890c-9180d6f43e08.png">

Sell order: 
<img width="894" alt="Bildschirmfoto 2021-06-30 um 12 07 15" src="https://user-images.githubusercontent.com/34510341/123942741-bc76e980-d99b-11eb-8474-8c6c3dc1313b.png">

**Comment by W3stside** [comment]
hmm just made a buy order WETH<>DAI on mainnet and it didn't do this

will keep trying..

**Comment by W3stside** [comment]
also nothing on rinkeby using the same tokens as you PAX<>DAI
![image](https://user-images.githubusercontent.com/21335563/124114164-26f35c80-da64-11eb-8efa-14e2928107c4.png)

**Comment by MareenG** [comment]
Yup, seems to be gone now. I also don't get it anymore.
