### ISSUE TITLE
Paraswap price fails if price impact is too high

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#835]
**Description**
The paraswap price fails if the price impact is too high

**How to Reproduce**
1. Go to Cowswap choose a random token pair
2. Do the same on Paraswap
3. Insert a value in Paraswap for which the price impact is too high or around 10%
4. Use this value on Cowswap
5.  The Price on Coswap is worse than Paraswap

**Expected behavior**
The same price should be displayed

**Screenshots**
<img width="1344" alt="Bildschirmfoto 2021-07-01 um 09 44 10" src="https://user-images.githubusercontent.com/34510341/124089852-96615000-da54-11eb-8809-aa85837a106a.png">
<img width="1320" alt="Bildschirmfoto 2021-07-01 um 10 05 58" src="https://user-images.githubusercontent.com/34510341/124090533-38813800-da55-11eb-8cac-899309b5a872.png">

**Comment by anxolin** [comment]
This is related to https://github.com/gnosis/cowswap/issues/825 and https://gnosisinc.slack.com/archives/C0203Q9R4JJ/p1625127648003500 

we will do a small fix to display their error even if ther's high price impact. 

In the future we will also show the price impact, and maybe even block the user from trading

**Comment by anxolin** [comment]
Fixed and deployed, let us know if u still see issues. Thx!
