### ISSUE TITLE
[price] Add Uniswap price

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#837]
**Description**
Now we consume prices from APIs, but we could also use our old Uniswap price as one extra price we take into account. 

Not sure if this is worth it, because the API already takes uniswap into account. Actually, both of the APIs are a bit smarter and take gas costs into account to decide on the hops.

**Proposal**
Query Uniswap price, and show the best of all the prices.

**Comment by alfetopito** [comment]
The backend already does that and returns it in the query, if better than Sushiswap.
I believe this is not worth it.
Unless we want to show a break down of several price sources, like 1inch etc.

**Comment by anxolin** [comment]
I just thought it's a free of cost price we already have, and adds resilience and maybe a faster price response (when we do eager updates)

But agree is not a prio. I find matcha more important integration

**Comment by W3stside** [comment]
dup of #1336
