### ISSUE TITLE
[Affiliate] Handle the default metadata doc

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#853]
**Description**
Handle the default metadata doc

**Proposal**
- Cowswap should use as a default one hash with a document that would credit all the trades to CowSwap UI. If there's no referral link, it would use this by default
- Otherwise it uses the referral hash (if it passes the validations)

**Additional context**
Draft wireframes proposal https://www.figma.com/file/P0AIwKkIUpEZtLukkCUM94/CowSwap_-Affiliate?node-id=48%3A224
Affiliate main doc https://docs.google.com/document/d/1PsdWn9WPFf2BNeoJNtClyra8jNvWk_bJ-g33TbpUf8s/edit#heading=h.wc3ppxg7l1mo

## Update 2021/07/16

- Nested metadata field should be a json object instead of an array:

``` json
{
  version: “1.0.0”,
  appCode: "CowSwap",
  metadata: {}
}
```

- Let's skip IPFS pinning. We are considering not using IPFS for this at all

## Update 2021/07/14

- ~This is the default document used when no referral link is used (from the doc above):~

``` json
{
  version: “1.0.0”,
  appCode: "CowSwap",
  metadata: []
}
```

- ~This doc should be manually uploaded/pinned to IPFS and its hash saved as a constant. Probably we should ask DevOps to internally pin in. For reference https://docs.ipfs.io/concepts/persistence/#persistence-versus-permanence~

**Comment by elena-zh** [comment]
Hi @alfetopito , 
seems to be that links to wireframes proposals in this task as well as in the rest ones (848-851) are outdated/broken. 

Could you please check and provide valid ones?

Thanks

**Comment by alfetopito** [comment]
Indeed, the figma org has been updated.
I'll update the link as soon as I get it.

**Comment by alfetopito** [comment]
Updated link https://www.figma.com/file/P0AIwKkIUpEZtLukkCUM94/CowSwap_-Affiliate?node-id=0%3A1

For those who want to see it, let me know, I need to manually give permission to external emails

**Comment by ramirotw** [comment]
No longer applies
