### ISSUE TITLE
CowGame glitches

### ISSUE THREAD

**Issue by biocom** [gnosis/cowswap#858]
<img src="https://user-images.githubusercontent.com/43217/124515020-3d1a5900-dd93-11eb-86f4-0a0920d5303d.png" alt="screenshot_2021-07-05_13-16-40" style="max-width:100%;">

### Steps:
Open the app at any page https://pr856--gpswapui.review.gnosisdev.com/
Open the game using the menu
Go back to swap page (click on header)
Open the game using the menu again
Cow is huge, game doesn't start.

Also, the text jumping still happen every time I start the game (when "Press space to start game" message disappears)

**Comment by anxolin** [comment]
- [ ] Mobile: Press space bar?? 
- [ ] Unmount and cleanup
- [ ] Change key to something that doesn't conflict with the app

**Comment by alfetopito** [comment]
Fixed on https://github.com/gnosis/cow-runner-game/pull/2
