### ISSUE TITLE
Landing website

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#859]
Creation of a website, home for the protocol. 

This website would explain what is GP, the key features and would link to the dev portal, explorer, different uis and the white paper. 

- [ ] Define the why and goals of the website
- [ ] Prototype, define content. Reiterate until everyone is happy with the result
- [ ] Design and validate internally and externally (UX research)
- [ ] Execute and deploy

We might want to do this as a new website, although another option is to do it in the explorer project. https://github.com/gnosis/gp-ui since it already have some components and styles (i.e. maybe we want to include some stats that the explorer has). 
We should be able to fully decide on this once the prototypes are complete. 

cc/ @annamsgeorge @biocom @alfetopito

**Comment by alfetopito** [comment]
Is this sort of a doc page?

**Comment by anxolin** [comment]
Something like: https://uniswap.org/ :)

**Comment by alongoni** [comment]
Hey team! I've made these wireframes for the [Gnosis Protol landing page](https://www.figma.com/proto/Ufc9uPGBQgoS9BYqPwR3Wp/GP-Landing-Page?node-id=6%3A739&viewport=-1058%2C-1733%2C0.4989266097545624&scaling=min-zoom&page-id=6%3A729%3Ffuid%3D789860674698606135). The proposal was based on two things: 
- https://gnosis-safe.io/ (Gnosis Safe) 
- https://uniswap.org/

All of the texts were simulated and we can start defining them in this prototype. Also, you can comment your opinions or suggestions in Figma (there are two pages).

**Comment by avsavsavs** [comment]
I like the suggestion in terms of the design of text, banners etc. Although, I find it a bit "plain" in terms of colors of headlines, buttons etc. Of course, depending on the branding this is something that can change.

**Comment by alongoni** [comment]
> I like the suggestion in terms of the design of text, banners etc. Although, I find it a bit "plain" in terms of colors of headlines, buttons etc. Of course, depending on the branding this is something that can change.

hey @avsavsavs Thanks! Yes, the idea was to start with a basic wireframe without "design details". After that we can try adding more color, buttons, backgrounds, animations, etc.

**Comment by biocom** [comment]
My suggestion would be, to take this into Figma first (wireframes) so we can define the general layout first.

**Comment by biocom** [comment]
Just noticed the Figma URL (overlooked it!) - Will review this week.

**Comment by biocom** [comment]
Added to the GP Figma workspace -> https://www.figma.com/file/SLo9yZD8iBCwuofPunCYx1/GP-Landing-Page?node-id=6%3A729 @alongoni sent you an invinte.

**Comment by alfetopito** [comment]
> Just noticed the Figma URL (overlooked it!) - Will review this week.

@biocom FYI, this has been put on hold.
Anna/Alex V will work on defining the content first before moving ahead.
Also, the priority for this is down at the bottom as there are many more things to define first.

All this to say, low priority :)

**Comment by biocom** [comment]
> > Just noticed the Figma URL (overlooked it!) - Will review this week.
> 
> @biocom FYI, this has been put on hold.
> Anna/Alex V will work on defining the content first before moving ahead.
> Also, the priority for this is down at the bottom as there are many more things to define first.
> 
> All this to say, low priority :)

Low priority, check ✅

**Comment by anxolin** [comment]
I like this comparison you did: 

![image](https://user-images.githubusercontent.com/2352112/126987579-4533ff22-7957-45f6-9514-af970f7bd916.png)

Some ideas for features:
**GPv1:**
* Batch Auctions
* Ring trades
* Uniform clearing prices
* Solver competition

**Some features of GPv2:**
* No need to deposit
* Faster batches (1 block, 1 batch)
* Coincidence of wants
* Gas-less orders
* Onchain liquidity agnostic
* MEV Resistant

**Some features of GPv3:**
I wouldn't call it GPv3, i would show it as NEXT, for example.

* Decentralised solver competition
* MEV Geth protected
* More onchain liquidity integrations
* Onchain smart orders
* Gnosis Safe integration


Each feature should be clickable, and should explain what is it in plain terms.

Maybe we can even do a different comparison between: AMMs, Dex Agg, CowSwap
- Low gas for simpler trades (AMM, CowSwap)
- Split order in different onchain sources (DEX Agg, CowSwap)
- Path change resistant (CowSwap)
- Uniform clearing price (CowSwap) 
- MEV resistant (CowSwap) 
- Peer to peer trading (CowSwap) 
- Gass-less trading (CowSwap) 
- Concurrent users have positive impact (CowSwap) 

We could explain also for every ✅ and ❌ why is the case.

cc/ @annamsgeorge @michelbio @fleupold
