### ISSUE TITLE
Improvements - cancelation of orders

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#860]
I am adding here a few improvements for the cancelation of orders process: 

Recent Activities:
I think the **green x** is a bit missleading. I would suggest to rather go for a **grey -**
<img width="445" alt="Bildschirmfoto 2021-07-06 um 10 45 27" src="https://user-images.githubusercontent.com/34510341/124571609-3c8fca00-de48-11eb-8eb9-ad803d932e25.png">
<img width="445" alt="Bildschirmfoto 2021-07-06 um 10 45 27 Kopie" src="https://user-images.githubusercontent.com/34510341/124571600-3b5e9d00-de48-11eb-8f4e-aecc7cc85920.png">

Same for the pop up modal confirming the cancelation
<img width="379" alt="Bildschirmfoto 2021-07-06 um 10 50 41" src="https://user-images.githubusercontent.com/34510341/124572664-1ae31280-de49-11eb-8ba0-dfebd6b56891.png">

I think it might be good to allow the cancelation already in the pop up modal. 
<img width="390" alt="Bildschirmfoto 2021-07-06 um 10 49 32" src="https://user-images.githubusercontent.com/34510341/124571918-7fea3880-de48-11eb-994a-aa46f0e8d804.png">

**Comment by MareenG** [comment]
The explorer doesn't show a difference between a requested cancelation and a successfull cancelation. If possible it would make sense to have **cancelation requested**  instead of **Cancled**
<img width="1427" alt="Bildschirmfoto 2021-07-06 um 11 03 07" src="https://user-images.githubusercontent.com/34510341/124574004-57633e00-de4a-11eb-9900-a9e5cdc22c42.png">
<img width="1439" alt="Bildschirmfoto 2021-07-06 um 11 04 21" src="https://user-images.githubusercontent.com/34510341/124574008-58946b00-de4a-11eb-970e-2bdc86d260b4.png">

**Comment by MareenG** [comment]
Maybe incude in the FAQs how we cancel the order and what you are signing if you cancel the order
<img width="392" alt="Bildschirmfoto 2021-07-06 um 12 51 50" src="https://user-images.githubusercontent.com/34510341/124588413-0d358900-de59-11eb-9f8d-5f5e17ff3da4.png">

**Comment by MareenG** [comment]
Include a cancelation request pop up:

https://user-images.githubusercontent.com/34510341/124591718-e7aa7e80-de5c-11eb-80df-72465abc5e0a.mov

**Comment by alfetopito** [comment]
All great suggestions!

Regarding the first one, the account details will be re-worked. Take a look at this proposal by Michel https://www.figma.com/proto/bcoZf5RIgVKDItdOaTZq18/GP-Swap?page-id=1459%3A2&node-id=1468%3A367&viewport=-6038%2C-829%2C0.35277482867240906&scaling=min-zoom

**Comment by elena-zh** [comment]
Seems that almost all cases are addressed: 
1. side bar is re-worked,
2. Modals are being reworked in #1483 
3. FAQ contains section about an order cancelling
4. I have created a separate issue for statuses sync in GP-UI repository https://github.com/gnosis/gp-ui/issues/702

So, I will close the current task
