### ISSUE TITLE
Cowgame: free space

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#864]
The free space below the text looks a bit odd. 
Maybe we can enlarge the game or centre it more.
<img width="782" alt="Bildschirmfoto 2021-07-06 um 11 38 47" src="https://user-images.githubusercontent.com/34510341/124578812-d6f30c00-de4e-11eb-870f-8ee71d5ebe0f.png">

**Comment by biocom** [comment]
Fixed in https://github.com/gnosis/cowswap/pull/872
