### ISSUE TITLE
Update FAQ link in cancelation process

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#865]
**Description**
The FAQ link when requesting a cancelation does link to the FAQ page. Might be good to directly link to the _Can I cancel my order_ section: 

https://user-images.githubusercontent.com/34510341/124581311-4669fb00-de51-11eb-8d19-4364121bf5df.mov

**Comment by biocom** [comment]
Incoming anchor link not working (#/faq#can-i-cancel-an-order) as expected. This is a known issue and should be fixed IMO.

Related to the same issue reported originally here https://github.com/gnosis/cowswap/issues/787
