### ISSUE TITLE
[Mobile] Play - 'Press Space to start' is displayed when start a game

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#866]
1. Open the game in the app in a mobile device (no matter if it is Android or iOS)
2. Start the game

**AR**:  'Press Space to start' is displayed when start/finish the game
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/8768484b-967d-4ad3-afa5-40dd7f7e8fa0) ![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ffe35fc5-8c9b-490b-96be-5a795306508c)

**ER**: the message should not be displayed

**Comment by biocom** [comment]
Need to check the library we forked (https://wayou.github.io/t-rex-runner/) as they don't support touch/mobile either I see. But looking at this other version https://trex-runner.com/ - it does for me there.

**Comment by biocom** [comment]
Should be fixed with https://github.com/gnosis/cow-runner-game/pull/2 - That needs to be merged in first.
