### ISSUE TITLE
Cowgame: Dark and light mode mix sometimes

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#869]
**Description**
In the light mode sometimes the background of the dark mode is shown (moon and stars) 
In the dark mode sometime the background of the light mode is shown( only clouds) 

<img width="736" alt="Bildschirmfoto 2021-07-06 um 13 10 43" src="https://user-images.githubusercontent.com/34510341/124590684-b7161500-de5b-11eb-9eb8-153dd387cc9c.png">
<img width="726" alt="Bildschirmfoto 2021-07-06 um 13 08 56" src="https://user-images.githubusercontent.com/34510341/124590688-b8dfd880-de5b-11eb-9bd3-75cab9fd3a18.png">

**How to Reproduce**
Didn't quite figure out how to reproduce but it might be related to switching between dark and light mode

**Comment by biocom** [comment]
Thanks for checking. It's expected/intended and sprite image related. Won't fix for now.
