### ISSUE TITLE
Cowgame: Game doesn't close properly

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#870]
**Description**
When you close the game e.g. click on swap. The game seems to be still open somehow. 
When pressing space you can hear the jump sound

**How to Reproduce**
1. Go to https://cowswap.staging.gnosisdev.com/#/play
2. Play
3. Click on Swap
4. Press Space
5. Hear jumping sound

**Expected behavior**
Once you leave the game screen no more sound should be present

**Comment by biocom** [comment]
I have a hunch this is related to this issue @alfetopito reported (and I created an issue for) https://github.com/gnosis/cowswap/issues/858

**Comment by biocom** [comment]
CowGame component doesn't get unmounted on route change.

**Comment by alfetopito** [comment]
Fixed on https://github.com/gnosis/cow-runner-game/pull/2
