### ISSUE TITLE
[iPhone+ iOS14.6] Swap: background is loaded with a delay + cow is not fully visible when scroll the screen

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#873]
Open Swap page in iPhone
1. switch to dark/light modes
2. scroll the screen up and down

**AR**: 
1. background (cow) is loaded with a delay
2.  cow is not fully visible
https://drive.google.com/file/d/1oPEBUwk27B31hZ4qlbGwF4vlNR9WU3ox/view?usp=sharing

**ER**: 
1. no delay with a loaded background
2. cow should become visible when scroll the screen

**Comment by alfetopito** [comment]
@biocom any idea what could be causing this delay?

**Comment by biocom** [comment]
- There is a transition in place here `src/custom/theme/cowSwapTheme.tsx` - L104. Perhaps that doesn't play nice on iOS. I removed it in this PR https://github.com/gnosis/cowswap/pull/899 and should work correct now:

https://user-images.githubusercontent.com/31534717/124926444-d0ef5d80-dffd-11eb-909b-52917da0ea2d.mov

- As for the Cow being visible on scroll: I believe iOS disabled `background-attachment: fixed` when used with the `background-size: cover` setting for performance reasons (https://stackoverflow.com/questions/61945988/background-attachment-fixed-does-not-work-in-safari and https://caniuse.com/?search=background-attachment). Low prio and would say 'no-fix' for now.
- What does AR / ER stand for ? :)

**Comment by elena-zh** [comment]
@biocom , 
'AR' = 'Actual  Result'
'ER' = 'Expected Result' 
Sorry using these abbreviations. They just let me save time when reporting issues :)

**Comment by biocom** [comment]
@elena-zh Thanks, now I will remember 🤓

**Comment by elena-zh** [comment]
Changes look good to me. 
I have created a separate issue #903 for the scroll bug in case if one day solution how to fix it appears.

**Comment by W3stside** [comment]
can this be closed?
