### ISSUE TITLE
[iPhone+ iOS14.6]  slippage selection is not highlighted 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#875]
1. Open 'Swap' page in iPhone+ iOS14.6
2. Open Settings and change slippage

**AR**: selection is not highlighted until close-reopen the modal
https://drive.google.com/file/d/1eUnK-4Vby1HRLT2qg4yW6PMVnbnrxCId/view?usp=sharing

**ER**: selection is highlighted

**Comment by alfetopito** [comment]
@W3stside may have fixed (or broken it :D) with v3 merge, it could have been fixed "for free"

**Comment by elena-zh** [comment]
Fixed in 0.17
