### ISSUE TITLE
Token with a 'broken' icon is added to MM

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#885]
I'm not sure if it is connected to exactly CowSwap app, however, when I add a token to my MM wallet using 'Add token' option, it is added with a 'broken' icon to the wallet
https://drive.google.com/file/d/1dOEKAy9RBH1H7w_wli8BxgmQ0-wl0-gy/view

**Expected**: the icon is not 'broken'

**Comment by elena-zh** [comment]
Reproducible in Rinkeby only.

**Comment by alfetopito** [comment]
I'd say this is a non-issue.
Token images are checked against TrustWallet's assets repo using the token address.
The mapping is only for mainnet addresses though.
We might have some logic in the app for a few specific tokens, but Metamask has their own image sources out of our control.
