### ISSUE TITLE
Redesign recent history of orders

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#892]
- [x] Create component
- [x] HTML/CSS
- [x] Using the component in the "recent history"?
- [ ] use the component in the toast notifications? 
- [ ] can we use it for the trade/history of orders?

**Comment by biocom** [comment]
@anxolin Should we close this one, and address the 'toast notification' in a specific ticket?

**Comment by anxolin** [comment]
> @anxolin Should we close this one, and address the 'toast notification' in a specific ticket?

Yep. Pls, go for it
