### ISSUE TITLE
Warning when fees are too high

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#896]
**Description**
Display a warning when the fee is too high.

**Proposal**
Show "The trade size is small (?)" or "Fees are high for this trade size (?)"

In the question-mark we show a tooltip:
```
The fees for this trade are significant for this trade size. You can still trade if you are ok with it, but it would be good to increase the trade size.

Every trade has some fixed fee costs you need to pay to have it executed. When you trade small amounts you will be paying this part of the fee. This is in fact very similar to any other decentralised exchanges, where you have some fixed costs for the gas of the transaction. One difference for CowSwap, is that you only pay this fee if you trade, so submission and cancelation are free.
```

**Alternatives**
- Decide on better texts than the ones i proposed above ^^^ 
- Decided on which percentage is high and experiment with it. 
- Ask in discord about this, and even share a demo link to try it out
- 

**Additional context**
![image](https://user-images.githubusercontent.com/2352112/124882695-f154f300-dfd0-11eb-9143-7f476a6592f2.png)
☝️ In this example, 48% goes to the fee, so I get that this is a stupid trade to do

![image](https://user-images.githubusercontent.com/2352112/124884621-bce23680-dfd2-11eb-8952-8d8c5ba6c979.png)
☝️ With 2 GNO I pay a bit above 3%

**Comment by W3stside** [comment]
@gnosis/gp-contracts @gnosis/gp-frontend 

I would like to start a conversation on what constants to use here. Proposal:

- when fee >= 30% of sell amount, show the fee warning
- warning location:
![image](https://user-images.githubusercontent.com/21335563/130204351-4c3a551c-44fd-4bb7-94aa-841e30fd1473.png)
- warning text on expansion:
```
Fees for this swap are significant relative to the swap size.
You may still move forward with this swap but it is highly recommended that you increase the swapped amounts.

Every swap incurs some fixed fee costs in order to execute.
With CowSwap however, users do NOT incur fees should their swap not execute!

No more wasted gas fees and greater peace of mind when trading. Compare that to other on-chain exchanges where failed transactions can be extremely expensive based on gas prices.
```
Expanded screenshot:
![image](https://user-images.githubusercontent.com/21335563/130204914-baa03924-f9f1-40ef-bb70-b421d49c8dc2.png)
- also viewable in confirmation modal:
![image](https://user-images.githubusercontent.com/21335563/130205613-58fe8845-0f8d-4ae5-8356-717bee6b9d8a.png)

WDYT?

**Comment by anxolin** [comment]
Great! Just cross-linking with the conversation in slack, let see what input we get https://gnosisinc.slack.com/archives/CSGLUC1BN/p1629448724163200

**Comment by biocom** [comment]
@W3stside I like your suggestion and visual example. A couple of comments:
- I'd cut-off the text from ("..Every swap incurs...") and on. The initial text above is the most relevant, in terms of 'high fee vs. swap amount'. Instead we could link to an external FAQ.
- I'd use a bigger + and ditch the text "Show More" to reduce some visual noise.

**Comment by fedgiac** [comment]
I personally like how the warning is presented graphically.
I have some comments about the text:
1. It feels weird that we ask for an "increased swapped amount". Unless I'm testing the app I'd say I want to trade a specific amount and I'm not going to trade more because of what effectively is a limitation of the platform. A sentence to a similar effect could be "Every swap incurs a fixed fee, and the amount you are trading is close to this fee", this way it should be clear for those who want to do it that increasing the traded amount would be worthwhile. We can also say that the fee depends on the network gas price, so waiting might bring down the fees.
2. The second half of the text is not really related to the warning (to me, it sounds like an ad: "yes, this isn't good, but we are still great because &lt;unrelated&gt;").

In terms of percentages, I would already be annoyed by a 5% fee (show warning?), and if the fee reaches 30% I'd require advanced mode for trading. However I don't have any info on what's the usual percent of fee paid for a trade in GPv2, so maybe users might be more cautious or more tolerant than I expect.

**Comment by W3stside** [comment]
I haven't read the comments yet and want to paste one of the proposed changes I've made:

With percentage amounts:
![image](https://user-images.githubusercontent.com/21335563/130221465-cf044bb0-5715-4935-899c-f78f85d1c22e.png)

**Comment by W3stside** [comment]
> @W3stside I like your suggestion and visual example. A couple of comments:
> 
> * I'd cut-off the text from ("..Every swap incurs...") and on. The initial text above is the most relevant, in terms of 'high fee vs. swap amount'. Instead we could link to an external FAQ.
> * I'd use a bigger + and ditch the text "Show More" to reduce some visual noise.

ok sounds good, i agree the other text is irrelevant//fluff. Indeed feels like an ad as @fedgiac commented 😂

**Comment by W3stside** [comment]
> I personally like how the warning is presented graphically.
> I have some comments about the text:
> 
> 1. It feels weird that we ask for an "increased swapped amount". Unless I'm testing the app I'd say I want to trade a specific amount and I'm not going to trade more because of what effectively is a limitation of the platform. A sentence to a similar effect could be "Every swap incurs a fixed fee, and the amount you are trading is close to this fee", this way it should be clear for those who want to do it that increasing the traded amount would be worthwhile. We can also say that the fee depends on the network gas price, so waiting might bring down the fees.
> 2. The second half of the text is not really related to the warning (to me, it sounds like an ad: "yes, this isn't good, but we are still great because <unrelated>").
> 
> In terms of percentages, I would already be annoyed by a 5% fee (show warning?), and if the fee reaches 30% I'd require advanced mode for trading. However I don't have any info on what's the usual percent of fee paid for a trade in GPv2, so maybe users might be more cautious or more tolerant than I expect.

yep good points. will slim text down and change wording. @koeppelmann also basically summarised the same

**Comment by fedgiac** [comment]
About the updated text: I like it, but both suggestions could be hard to understand for a non-technical user. There could be a link below each suggested actions (wait for lower fees -> Question: how long should I wait?, move to xDAI -> Question: what is xDAI?).

**Comment by W3stside** [comment]
> About the updated text: I like it, but both suggestions could be hard to understand for a non-technical user. There could be a link below each suggested actions (wait for lower fees -> Question: how long should I wait?, move to xDAI -> Question: what is xDAI?).

@avsavsavs we don't have anything specific for:
> wait for lower fees -> Question: how long should I wait?, move to xDAI -> Question: what is xDAI?).

do we?

**Comment by bh2smith** [comment]
Not sure if this has been mentioned yet, but I would slightly prefer to use the term "sell amount" in place of "swap amount". No strong feelings though and it seems like this issue discussion has come along quite well so I will just leave it at this.
