### ISSUE TITLE
FAQ typos

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#901]
<img width="432" alt="Bildschirmfoto 2021-07-08 um 15 57 41" src="https://user-images.githubusercontent.com/34510341/124934737-46aaf780-e005-11eb-9114-7f8fdc810a36.png">

**Comment by MareenG** [comment]
<img width="632" alt="Bildschirmfoto 2021-07-08 um 16 07 11" src="https://user-images.githubusercontent.com/34510341/124936325-b8377580-e006-11eb-8f66-f28a3920bd08.png">
<img width="641" alt="Bildschirmfoto 2021-07-08 um 16 06 53" src="https://user-images.githubusercontent.com/34510341/124936331-b968a280-e006-11eb-8e36-99a781ce7b72.png">

**Comment by MareenG** [comment]
There are a few sections where the **.** is missing at the end. Maybe you can do a quick check.

**Comment by alfetopito** [comment]
Regarding the first part, the table has been re-organized, so it probably doesn't apply anymore.
See the changes https://github.com/gnosis/cowswap/pull/786

It's on develop and will come out in the next release (0.16)

**Comment by avsavsavs** [comment]
I will review that we dont miss any points. Regarding the table, it doesn't apply anymore
