### ISSUE TITLE
Bug checking state of orders

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#904]
**Description**
![image](https://user-images.githubusercontent.com/2352112/125086062-89370780-e0cb-11eb-9b07-1ab0fa0cab79.png)

Issue checking tx hash in DEV. 
Probably part of merging V3.
Its trying to use a order id to get the tx receipt of a normal tx, which is wrong.

**Comment by anxolin** [comment]
Let's make sure before releasing to PROd v0.17 this is not present any more

**Comment by alfetopito** [comment]
This code only checks for transactions stored in the global state.
Looking at the code I could not find a place where an order is being added as a transaction.

Any chance you can share more data regarding the issue?
Could it be that this was a pending tx sped up and caused it to not exist in the blockchain?

**Comment by anxolin** [comment]
We didn't see this one again, so I will assume was fixed
