### ISSUE TITLE
Locale number format not respected

### ISSUE THREAD

**Issue by bh2smith** [gnosis/cowswap#905]
**Description**
I would expect to see a dot (`.`) as decimal separator in the swap interface, but recently on staging this has changed to a `,` everywhere except in the price quote (circled in black on screenshot)

Note that this is only an issue on `Firefox` as far as I can tell.

<img width="654" alt="Screenshot 2021-07-09 at 09 28 45" src="https://user-images.githubusercontent.com/11778116/125087086-34c76400-e09a-11eb-982c-7bd0cb2b478e.png">

**How to Reproduce**

Not exactly sure how to explicitly reproduce but I can share my system preferences for local and possibly also my browser ones.

This is specifically happening only on Firefox.

<img width="512" alt="Screenshot 2021-07-09 at 09 49 42" src="https://user-images.githubusercontent.com/11778116/125087999-0007dc80-e09b-11eb-9fc1-d24edc1cbe54.png">

and could be that Firefox has open bugs it "WONTFIX" about how the system locale isn't respected.

**Expected behavior**
I would expect to see is what I see on the production environment (i.e. decimal separators everywhere)

<img width="642" alt="Screenshot 2021-07-09 at 09 42 44" src="https://user-images.githubusercontent.com/11778116/125087189-4b6dbb00-e09a-11eb-8ebc-4450b7f2b11f.png">

**Additional context**
Also, if it's relevant for the described bug, add information like the browser or OS.

**Comment by alfetopito** [comment]
Fresh change from the oven added on https://github.com/gnosis/cowswap/pull/895

@W3stside we should disable the `localeAware`

**Comment by W3stside** [comment]
closed by #940
