### ISSUE TITLE
[Wallet] Cannot disconnect wallet connect

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#906]
**Description**
Can no longer disconnect WalletConnect on latest dev

**How to Reproduce**
1. On latest develop, connect using WalletConnect
2. Click on account details
3. There's no `disconnect` buttom

**Expected behavior**
There's a disconnect button and wallet can be disconnected from UI

**Screenshots**
![screenshot_2021-07-09_11-27-20](https://user-images.githubusercontent.com/43217/125121439-ca69f000-e0a8-11eb-961f-eb0d9cd15f5c.png)

**Additional context**
Also, the additional logic for displaying wallet name is no longer there.

**Comment by W3stside** [comment]
This is a simple uncomment job @alfetopito if you want to tackle it

**Comment by alfetopito** [comment]
> This is a simple uncomment job @alfetopito if you want to tackle it

Can't make any promises, a bit swamped right now
![](https://cdn5.img.sputniknews.com/images/104392/54/1043925446.jpg)

**Comment by W3stside** [comment]
_swamp-boy.jpeg_
