### ISSUE TITLE
Swap not displayed in recent activities

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#912]
**Description**
There was a still pending swap when I lastly closed CowSwap in staging. 
I got the notification today with a wrong token name (known issue #649).
However, it is also not displayed in my recent activities. 

**How to Reproduce**
1. Do a swap on Cowswap
2. Close while it is still pending
3. Open Cowswap again
4. Maybe see the errot

**Expected behavior**
The swap should be displayed under recent activities

**Screenshots**
Wrong pop up modal: 
<img width="398" alt="Bildschirmfoto 2021-07-13 um 14 40 17" src="https://user-images.githubusercontent.com/34510341/125453937-2296de2b-6d56-4eca-a427-1d3c05a99fb6.png">
No input in recent activities
<img width="551" alt="Bildschirmfoto 2021-07-13 um 14 40 30" src="https://user-images.githubusercontent.com/34510341/125453944-ea41f1d1-471d-4cce-bced-7fbee58fb8ef.png">

**Comment by MareenG** [comment]
Update: 
I did a trade today  on https://cowswap.exchange/#/swap. Closed the tab opened a new one and my recent history was cleared. This doesn't happen all the time.

**Comment by elena-zh** [comment]
Today I'm not able to see my transactions which I did yesterday in Staging.

**Comment by alfetopito** [comment]
For context, only trades in the last 24h are displayed.

At least I was sure of that, but I can't find where that happens in the code, so I might be wrong.
Will update if I find it.

**Comment by alfetopito** [comment]
Found it. Indeed, only orders from the last 24h are displayed https://github.com/gnosis/cowswap/blob/b366fa833887f6a86dacf93f425e2dc6f250c811/src/custom/hooks/useRecentActivity.ts#L35

Which, to be clear, is inherited from Uniswap.

Regarding you getting the notification and it not being displayed in the recent history, it's probably something we should fix.
I'd say not to show notification at all if the order won't be displayed (older than 24h)

If we want to display them longer, that can be discussed after the order history is reworked (Michel is working on it)
