### ISSUE TITLE
Game area is reduced when start a game

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#913]
1. Open Cowgame
2. Press space to start

**Actual Result:** the area is reduced
https://drive.google.com/file/d/1R8lw_8VPAD8JuNSLM-nK4TZPVrCrj9P9/view 

**Expected Result:** the area is fixed

**Comment by alfetopito** [comment]
Fixed by https://github.com/gnosis/cow-runner-game/pull/6
