### ISSUE TITLE
Wrong fee or wrong error message

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#917]
**Description**
I was looking into some token pairs which should roughly trade 1:1. (USDC,OWL, DAI, ...)
I was going to sell an amount of 100. In some cases it displayed that the fee exceed from amount. However when typing in the same amount again it worked and a fee of 10 was displayed. 
I know that the fees can vary but this is quite a big range. It happened 2-3 times but currently I can't reproduce it.

**Comment by alfetopito** [comment]
Not 100% sure, but from what you are describing this is the same as the issue David just fixed https://github.com/gnosis/cowswap/pull/919

**Comment by alfetopito** [comment]
cc @W3stside

**Comment by W3stside** [comment]
Yeah i think this is related to #919 

Basically the value being returned was experiencing race conditions. This no longer happens in staging
