### ISSUE TITLE
Messages are not displayed on a connection modal in a dark mode

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#929]
Connection modal: 
![conn modal.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e5a855bd-4c7b-480b-8d41-7f25071494b9)

MetaMask Connection:
![MM.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0445b2c0-fc21-477c-90d0-59e54aedefd3)

WC connection:
![wc.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/392655af-3a37-42d8-accd-96392b1ba45a)

**Expected**: messages should be displayed both in a dark and light modes

**Comment by alfetopito** [comment]
cc @biocom 

Although the wallet modal has been updated in the latest version after univ3 merge, so it might not apply 100%

**Comment by biocom** [comment]
Need to cherry pick this from my other 'Don't merge' PRs.

**Comment by W3stside** [comment]
@elena-zh still an issue in 0.17?

**Comment by elena-zh** [comment]
Not reproducible in 0.17. Closed
