### ISSUE TITLE
[Affiliate] Wire up affiliate status check

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#944]
# Summary

Using the component implemented on #943, show the appropriate message when user opens an affiliate link.

Once the affiliate link is loaded:
1. Create metadata doc
1. Create doc hash
1. Post data to backend enpoint
1. Based on response, display the appropriated message below
1. Store on redux state the doc+hash sent if call was sucessful

**Note**: Messages are not final, feel free to propose better ones.

1. Is it own link? (referral address matches connected wallet address) -> "Invalid code: cannot refer yourself"
1. Has account already traded without referral code? (check will come from an endpoint still TBD) -> "Invalid code: referral only valid for new accounts"
1. Has account already traded with a different referral code? (check will come from endpoint TBD) -> "Affiliate already active with a different referral code"
1. In case network failure or any unknown reason -> Use default error message (check `custom/operator/error/`)
1. Referall is valid and can be used -> "Affiliate program enabled"

# Requirements

- Build metadata doc
- Calculate hash
- Call the backend endpoint 
- Display messages according to referral code

# Out of scope

- Endpoint for checking account eligibility

# Additional context

- Wireframes: https://www.figma.com/file/P0AIwKkIUpEZtLukkCUM94/CowSwap_-Affiliate?node-id=48%3A224
- Design doc: https://docs.google.com/document/d/1PsdWn9WPFf2BNeoJNtClyra8jNvWk_bJ-g33TbpUf8s/edit#

**Comment by alfetopito** [comment]
I've created a flow chart with what was last discussed internally.

There won't be an endpoint for checking affiliate validity.
Instead, a few checks will be done, defined in the diagram.
The doc will also not need to be stored on local storage, only the referrer address and the appDataHash (appDocHash/appData, not sure on the name, feel free to suggest one if this doesn't make sense).

It might conflict with other tasks and what's written on this task (did not update it yet). Let use this as source of truth.

![screenshot_2021-07-30_16-15-57.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/c9c7b204-5a0f-4bd7-96d1-db354ca61b86)

I'll update in case anything changes

**Comment by ramirotw** [comment]
@alfetopito so basically this new workflow put several tasks that were already done on hold:
- #960 Implement api to get metadata doc: we don't need this endpoint anymore
- #853 Handle the default metadata doc: there's no need to get the default doc as we are only going to need a default appDataHash which is not defined yet
- #955 Hash metadata doc: we no longer need to hash the doc client-side as this is going to be done on the backend

**Comment by elena-zh** [comment]
Hi @alfetopito , I think that 1 condition is missing on the diagram:  `Has account already traded with a different referral code`
I believe, it might be covered by this condition, am I right?
![image](https://user-images.githubusercontent.com/70885163/128001114-7af21ccf-d69e-46b6-a7cd-e02a895e89df.png)

Also, I have one question: what should happen after a network failure or any unknown reason? Will a user be able to retry to use the affiliate link or so? At least, I think, we should add a 'Try again' button on the notification banner...

**Comment by biocom** [comment]
@alfetopito Looking at your schema, I wonder what happens if the user decides to *not* connect a wallet (after following a referral url). Thinking about a scenario a users for reasons, abandons the screen. 

Will it keep the affiliate ID in the local storage for next time the user comes back and connect their wallet?

**Comment by alfetopito** [comment]
@ramirotw 

> @alfetopito so basically this new workflow put several tasks that were already done on hold:

Unfortunately yes

> We need to create a new ticket to handle the GET /v1/trades?owner=<address> endpoint. I'd say to update the getAppDataDoc method created in #960 for this and replace it by the trades endpoint.

Yes for a new issue, not sure it makes sense to re-use `getAppDataDoc`.
I'd think of something like an utils function `hasUserTraded(networkId, userAddress)`, encapsulating a `getTrades` call.

---

@elena-zh 

> Has account already traded with a different referral code. I believe, it might be covered by this condition, am I right?

Yes, if the user traded once, doesn't matter with which referral, we simplify and say a new code cannot be applied

> Also, I have one question: what should happen after a network failure or any unknown reason? Will a user be able to retry to use the affiliate link or so? At least, I think, we should add a 'Try again' button on the notification banner...

Good point. In case of a failure anywhere in the flow (checking for trades OR uploading the metadata doc) we should notify the failure and do as you suggest.

---

@biocom 

> Will it keep the affiliate ID in the local storage for next time the user comes back and connect their wallet?

Initially I thought no. Bu maybe it makes sense to keep it until the wallet first connects.
What do you think makes more sense?

**Comment by ramirotw** [comment]
> Yes for a new issue, not sure it makes sense to re-use getAppDataDoc.
I'd think of something like an utils function hasUserTraded(networkId, userAddress), encapsulating a getTrades call.

Sorry I wasn't clear. I didn't mean reusing the method but having it replaced by a new method which for this use case works as a replacement. If not we'll need to remove it sooner than later.

**Comment by alfetopito** [comment]
> Sorry I wasn't clear. I didn't mean reusing the method but having it replaced by a new method which for this use case works as a replacement. If not we'll need to remove it sooner than later.

Not sure I get it 100%, but I'll it up to your judgement.

**Comment by biocom** [comment]
@alfetopito 
> Initially I thought no. Bu maybe it makes sense to keep it until the wallet first connects.
What do you think makes more sense?

I think it makes sense to keep it in -> Somebody clicked on a referral url. They might not repeat that step (clicking on an url) -> but might continue just connecting their wallet at some point. It would be nice to still capture the referral for the affiliate ID (holder) in that scenario.

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1405
