### ISSUE TITLE
v0.17 - wallet not recognised in Account info

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#946]
**Description**
The connected wallet is not recognised  in the account info.

**How to Reproduce**
1. Open Cowswap v0.17
2. Connect any wallet
3. Click on the wallet in the top right corner

**Expected behavior**
It should name the wallet that is connected e.g. MM or WC

**Screenshots**
<img width="498" alt="Bildschirmfoto 2021-07-15 um 10 57 07" src="https://user-images.githubusercontent.com/34510341/125760926-cb9c63c0-7951-45b5-aea5-5d35a20102ce.png">

**Comment by alfetopito** [comment]
I believe @W3stside was working on that today, right?

**Comment by elena-zh** [comment]
seems to be fixed in v.0.17 for supported wallets
