### ISSUE TITLE
v0.17- $ Estimation for ANT missing

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#948]
**Description**
The $ estimation for ANT tokens are not displayed. 

**How to Reproduce**
1. Go to Cowswap v0.17
2. Do a trade with ANT
3. Observe that no $ estimation is displayed

**Expected behavior**
$ estimation should be displayed

**Screenshots**
<img width="526" alt="Bildschirmfoto 2021-07-15 um 13 47 35" src="https://user-images.githubusercontent.com/34510341/125783434-7804bd75-e85a-4bf2-8e8e-f71befed0182.png">
<img width="544" alt="Bildschirmfoto 2021-07-15 um 13 47 04" src="https://user-images.githubusercontent.com/34510341/125783448-06a361c5-fad5-4d77-8cdb-36901edcf1d7.png">

**Thought**
I don't now where we get the $ price estimation from but maybe ANTv1 (0x960b236A07cf122663c4303350609A66A7B288C0) is not included here? 
Especially since it works for ANTv2 (0xa117000000f279d81a1d3cc75430faa017fa5a2e)
<img width="541" alt="Bildschirmfoto 2021-07-15 um 13 52 50" src="https://user-images.githubusercontent.com/34510341/125783794-34bffbe1-640d-44e6-9609-2b65e3546f16.png">

**Comment by elena-zh** [comment]
Currently, I see USD estimation for ANT tokens: 
ANTv2 (0xa117000000f279d81a1d3cc75430faa017fa5a2e)
![image](https://user-images.githubusercontent.com/70885163/127659316-c5ee52f7-a9b1-4208-817b-5612b6adb8b6.png)


ANTv1 (0x960b236A07cf122663c4303350609A66A7B288C0)
![image](https://user-images.githubusercontent.com/70885163/127659384-1920c4e8-b2e2-489d-8421-f3d327b64411.png)


I'm closing the issue...
