### ISSUE TITLE
[Affiliate] Set metadata doc hash to order

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#957]
# Summary

Set metadata doc hash to order.

On order creation, use the metadata doc hash stored on redux and add it to the order.
Replace this https://github.com/gnosis/cowswap/blob/5f6fcb953b/src/custom/utils/trade.ts#L78

Should probably be loaded with a hook at a previous step on `useSwapCallback` https://github.com/gnosis/cowswap/blob/5f6fcb953b3c19d7ee6ba1c091f0398f33b38a9f/src/custom/hooks/useSwapCallback.ts#L54

# Requirements

- Set metadata doc hash to order

# Out of scope

- Store metadata doc has on redux

# Additional context

- Wireframes: https://www.figma.com/file/P0AIwKkIUpEZtLukkCUM94/CowSwap_-Affiliate?node-id=48%3A224
- Design doc: https://docs.google.com/document/d/1PsdWn9WPFf2BNeoJNtClyra8jNvWk_bJ-g33TbpUf8s/edit#

**Comment by alfetopito** [comment]
I've created a simple flowchart to define the expected way this is handled![screenshot_2021-07-30_16-16-05.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/8b4398d8-d4d9-49db-8e37-cf6e22af8817)

This handles the case where there's nothing set and instead uses a default hash. Hash not yet defined, you can use a garbage placeholder if this tasks is started before it's defined.

**Comment by ramirotw** [comment]
Closed by https://github.com/gnosis/cowswap/pull/1191
