### ISSUE TITLE
[Affiliate] Profile page design

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#958]
# Summary

Profile page design

Based on the following mock, propose a design

![Profile_page_proposal.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/4a4f216e-fb8b-4fac-897b-4cbbbf13a7a5)

**Notes:**
- We'll have a single page for now
- The page, links and everything else will be named "Profile"
- Should sync with Michel for overall guidelines

# Requirements

- Figma design for the "Profile" page

# Out of scope

- 

# Additional context

- Wireframes: https://www.figma.com/file/P0AIwKkIUpEZtLukkCUM94/CowSwap_-Affiliate?node-id=48%3A224
- Design doc: https://docs.google.com/document/d/1PsdWn9WPFf2BNeoJNtClyra8jNvWk_bJ-g33TbpUf8s/edit#

**Comment by elena-zh** [comment]
@alfetopito , how should the 'Profile' page look like to a not connected user?
Or it should not be displayed at all when a user has not connected a wallet yet?

Thanks

**Comment by alfetopito** [comment]
> @alfetopito , how should the 'Profile' page look like to a not connected user?
> Or it should not be displayed at all when a user has not connected a wallet yet?
> 
> Thanks

Great question! 

I'd say, for the first version, the `Profile` tab and pages are always visible.
While not connected, the profile will display only a `Connect wallet` button.

I'll work with the team to refine the contents and behaviour

**Comment by annamsgeorge** [comment]
I would have probably just not displayed it to anyone who isn't connected, then we don't have to worry about a screen for this case and as a user I get a bit annoyed when being asked to connect my wallet too frequently. But fine either way. :)

We also have to think about what it shows in case of a connected wallet that has done 0 trades on CowSwap so far. The straight forward but maybe a bit boring case would be just to display "0" everywhere. 
Alternatively we could have a sad looking cow and display the text "You have done 0 trades on CowSwap so far. Try one to boost up your scores!"

**Comment by alongoni** [comment]
This is the first approach to the Profile design:

https://www.figma.com/proto/sIhnnyGY1t6acoHlMFODpL/CowSwap_-Affiliate_Design?node-id=236%3A100&viewport=513%2C332%2C0.37476223707199097&scaling=min-zoom&page-id=236%3A99&starting-point-node-id=236%3A100&hide-ui=1

Please let me know your suggestions.
cc @alfetopito @annamsgeorge @michelbio

**Comment by alfetopito** [comment]
I like it!

I just have one concern regarding the cards.
Of course, this wasn't part of the requirement so you wouldn't have known, but we have for a next version (when we are able to fetch the data) to include another item in the top section. It might not fit the 3 cards design.

Here's the second version
![Screenshot 2021-07-16 at 20 11 54](https://user-images.githubusercontent.com/43217/126408781-79015d62-f42d-4165-8fcc-d060331a8b27.png)

No need to add the new field to the design right now.
Just think how that would look like if we have another field in there.

Still, I suggest to wait for Michel's and Anna's feedback. They might have different ideas.

**Comment by annamsgeorge** [comment]
Heey, really cool already!
A few thoughts:
For the screen that says you haven't done any trade yet: 
- it should link to the "Swap" section to guide users where they should go to. One way of doing this would be to link it in the words "Try one", but maybe there's a nicer way of doing it
- I would remove the emoji-cow or add another emoji next to it, right now the emoji cow looks a bit lost to me

The profile with scores:
- Leandro is right that there will be something added ($$ lost in MEV), though that number will be negative for the user (money they lost by trading on other DEXes) so it might actually be a good idea to visually separate it from the positive numbers. I really like how the three positive numbers are highlighted on top :)
- here also I would remove the emoji cow, it looks odd that the number is not centered 
- Note that "trading volume" and "Surplus" will both be displayed in USD and this should be made clear somehow
- Lets ideally use the terms "Trading Volume"; "Participation in CoWs"; "Surplus" (with this spelling) 
- Love the referral code section
- The numbers aren't aligned here:
<img width="52" alt="Screenshot 2021-07-21 at 10 11 41" src="https://user-images.githubusercontent.com/33424780/126454804-f9e8c291-e177-41bc-8480-0255cdf40eb7.png">

**Comment by alongoni** [comment]
I've made the changes suggested. We use the same link:

https://www.figma.com/proto/sIhnnyGY1t6acoHlMFODpL/CowSwap_-Affiliate_Design?node-id=236%3A100&viewport=513%2C332%2C0.37476223707199097&scaling=min-zoom&page-id=236%3A99&starting-point-node-id=236%3A100&hide-ui=1

Also I added the numbers for: $$ lost in MEV-unprotected DEXes, just for start to think about it.

@alfetopito @annamsgeorge

**Comment by annamsgeorge** [comment]
Cool! :)
- in the large box (where users have volume), the title "Your profile" looks a bit heavy. Could we either try to move it centric, or use another more light/fun colour?
- Can we make the numbers of the referral section (# of trades done via referral & volume done via referral) a bit larger / more prominent? We want to show the users that we are paying attention to this and that this might influence the amount of airdrop they might get from us 
- I like the variant with the $$ lost on MEV & the red colours for the lost amounts

**Comment by annamsgeorge** [comment]
How will it look in dark mode?

**Comment by alongoni** [comment]
hey @annamsgeorge here we have the prototype with the changes applied: 
- I've reduced the font-weight of the titles for the sections, based on the implementation that we already have running.
- Increase the size of the numbers in referral section.
https://www.figma.com/proto/sIhnnyGY1t6acoHlMFODpL/CowSwap_-Affiliate_Design?node-id=236%3A100&scaling=min-zoom&page-id=236%3A99&starting-point-node-id=236%3A100


Regarding the dark mode, I made the design, maybe some general components are a bit off, but the Profile things are better and aligned!
https://www.figma.com/proto/sIhnnyGY1t6acoHlMFODpL/CowSwap_-Affiliate_Design?node-id=288%3A78&scaling=min-zoom&page-id=236%3A99&starting-point-node-id=288%3A78

![image](https://user-images.githubusercontent.com/622217/126709184-e6a65f61-6269-4447-9f7e-c073fd179135.png)

**Comment by alongoni** [comment]
Final version here:
https://www.figma.com/file/bcoZf5RIgVKDItdOaTZq18/GP-Swap?node-id=1989%3A2

**Comment by alongoni** [comment]
Here is the dark version.

https://www.figma.com/file/bcoZf5RIgVKDItdOaTZq18/GP-Swap?node-id=2041%3A4

![v1 7 - desktop - dark mode](https://user-images.githubusercontent.com/622217/128560430-798d7d76-121b-42b9-9ff9-a60092847714.png)

cc @biocom and @alfetopito

**Comment by alfetopito** [comment]
> Here is the dark version.
> 
> https://www.figma.com/file/bcoZf5RIgVKDItdOaTZq18/GP-Swap?node-id=2041%3A4
> 
> ![v1 7 - desktop - dark mode](https://user-images.githubusercontent.com/622217/128560430-798d7d76-121b-42b9-9ff9-a60092847714.png)
> 
> cc @biocom and @alfetopito

Looking pretty good :+1: 

One question: why is the background of the referral url card lighter than the others?
On light mode they are the same

**Comment by biocom** [comment]
@alongoni Thanks for doing it. Only comment is to try use/match the background we also use for the swap container (so the dark blue). This version I'd say is quite light for a dark version. Background = good!

**Comment by elena-zh** [comment]
@alfetopito , @alongoni , just to be clear on the final decision: 

1. How the page should look like to a not connected user

2. When a user is connected, has not traded before, profile should look like  https://www.figma.com/proto/sIhnnyGY1t6acoHlMFODpL/CowSwap_-Affiliate_Design?node-id=288%3A78&scaling=min-zoom&page-id=236%3A99&starting-point-node-id=288%3A78

OR zeros are displayed in these sections? 
![image](https://user-images.githubusercontent.com/70885163/128719374-dadcbc43-b595-4477-aa0d-62998d9c1167.png)

and @alfetopito , some question related to the logic: 
1. Total trades includes all orders signed by a user: filled/expired/cancelled/not trades by any reason. Correct?
2. Traded COWs counter contains only filled orders
3. Total referrals contains an amount of successfully placed and **filled** orders with this referral code. 
Am I correct?

**Comment by biocom** [comment]
> How the page should look like to a not connected user?

We could optionally show the 'Profile' menu item only to connected users. Nonetheless if someone does end up on this page (while not being connected) we'd need to show a message 'connect a wallet'. In my view for a first version it could hide all the elements.

> When a user is connected, has not traded before, profile should look like

I would simply show a `-` sign there without any other information/actionable items. The referral url is valid regardless.

**Comment by elena-zh** [comment]
@alfetopito ,
> and @alfetopito , some question related to the logic: 
> 1. Total trades includes all orders signed by a user: filled/expired/cancelled/not trades by any reason. Correct?
> 2. Traded COWs counter contains only filled orders
> 3. Total referrals contains an amount of successfully placed and **filled** orders with this referral code. 
> Am I correct?

No.. I'm wrong about the 1st and the 2nd points. =/
1. All successful trades should be countered under 'Total trades' 
2. Trade which is executed using Coincidence Of Wants should be countered under 'Traded COWs'..

But then I have another question: how can I check whether an order is executed using Coincidence Of Wants or AMM?

**Comment by alfetopito** [comment]
> @alfetopito ,
> 
> > and @alfetopito , some question related to the logic:
> > 
> > 1. Total trades includes all orders signed by a user: filled/expired/cancelled/not trades by any reason. Correct?
> > 2. Traded COWs counter contains only filled orders
> > 3. Total referrals contains an amount of successfully placed and **filled** orders with this referral code.
> >    Am I correct?
> 
> No.. I'm wrong about the 1st and the 2nd points. =/

Yes you were :)
Point 3 is correct, though

> 
>     1. All successful trades should be countered under 'Total trades'

:+1: 

>     2. Trade which is executed using Coincidence Of Wants should be countered under 'Traded COWs'..

:+1: 
 
> But then I have another question: how can I check whether an order is executed using Coincidence Of Wants or AMM?

We'll have that check on the backend/the graph

You can "manually" check that by looking at the transaction and seeing whether there are more trades matching your order.
To be honest, I'm still not able to tell 100% when looking at it myself.
Example with an order with a CoW https://etherscan.io/tx/0x670db187b8c10d751f4d558afeb8231a36c8ee86b1a80641e440cd07de14a99e

**Comment by alongoni** [comment]
> @alongoni Thanks for doing it. Only comment is to try use/match the background we also use for the swap container (so the dark blue). This version I'd say is quite light for a dark version. Background = good!

Hey @biocom, I've made some adjustments here:
![CowSwap - Account page (affiliate-v1 7 - desktop - dark mode](https://user-images.githubusercontent.com/622217/128748366-62736cba-5623-4945-b42d-c801c712b999.png)

**Comment by alfetopito** [comment]
## Update

Fields that will be available ([reference](https://docs.google.com/document/d/1Zu-ygdI1QpsFrJp_Ux4Q5KQx6iQLRfVscjebaYB_RV0/edit#bookmark=id.hlkjin6fzzra)):
- Total trades
- Total referrals
- Trade volume USD
- Referral Volume USD
- Last updated - this field is toindicate how fresh the data is, since we won't have real-time updates. It can even be empty if data has never been fecthed for this user

**Comment by alfetopito** [comment]
# What's left

## 1. Update the design to include the fields defined above

- Remove `Traded COWs`
- Add `Trade Volume` and `Referral Volume`
- Add `Last updated`. I see this as indicator on top right with less emphasis than the other fields

## 2. Behaviour when empty

Show a `-` for all fields have no value

Actually this might be implementation detail and not design related.

## 3. Behaviour when not connected

Same as `2`, with the addition of `Connect wallet` button on the bottom, like the initial design.
Also, referral URL will be empty as well.
