### ISSUE TITLE
[Release 0.17] Big price impact for small amounts

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#964]
**Description**

Users noticed a big price impact (in USD) when trading small amounts.

**How to Reproduce**
1. Pick two tokens
2. Inset a small amount, ~10 USD
The price impact will be quite high

**Expected behavior**
Low price impact?

**Screenshots**
![](https://cdn.discordapp.com/attachments/852275858844811275/865581969675780126/Screenshot_2021-07-16_at_09.13.13.png)

**Additional context**
Likely this is a non-issue.
The prices currently account for the fees, so the price looks very bad.

**Comment by W3stside** [comment]
@alfetopito was closed with lowering of USDC buy threshold, can you confirm?

**Comment by alfetopito** [comment]
Nah, think the issue was regarding the expectations.
We were showing the price after the fees, which on lower amounts is more clear.
Now we show the price before the fees, so this is no longer a problem.
