### ISSUE TITLE
[Release 0.17] Editing "to" input amount freezes UI

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#965]
**Description**

From user: 

> When I try to change the amount of token I want to receive it become impossible to swap
> After a hard refresh it work again
> Yes tried to change the "TO" amount freeze the UI but not a big issue after a hard refresh everything works fine(doesn't have the console open at this moment :/ )

Solved after a refresh.

Pair: USDC => WETH

**How to Reproduce**

**Expected behavior**
No freezes

**Screenshots**
N/A

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

**Comment by elena-zh** [comment]
might be related to #1264

**Comment by elena-zh** [comment]
Fixed in #1490
