### ISSUE TITLE
[Release 0.17] Broken screen on xDai

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#966]
**Description**

"Error: Invariant failed" while on xDai

Pair: xDai -> xDai
Type: sell

User clicked on `max` button to fill in the input

**How to Reproduce**

**Expected behavior**
App doesn't break

**Screenshots**
![](https://cdn.discordapp.com/attachments/852275858844811275/865584953718603836/unknown.png)

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

**Comment by W3stside** [comment]
fixed in #936
