### ISSUE TITLE
Can't place orders with Ledger

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#967]
**Description**

2 users reported issues placing orders with Ledger via Metamask, one using Chrome, other Firefox

**How to Reproduce**
1. Try to place order using Ledger via Metamask.
2. It fails

**Expected behavior**
Order should be placed

**Screenshots**
One user (on Firefox 90.0) got:
![](https://cdn.discordapp.com/attachments/852275858844811275/865591346332827688/unknown.png)

Other user (on Chrome) got:
![](https://cdn.discordapp.com/attachments/852275858844811275/865586453375746058/unknown.png)

> Ok, I got an error signing transactions with my ledger.
> Once I click sign on metamask, the UI shows the "signature denied" instantly even though MM asks my ledger to sign.
> I did sign on the ledger after, but not sure if it got sent back to the UI

**Additional context**
From community Kaffeeasdjas meeting

**Comment by alfetopito** [comment]
Just tested on Firefox 90; Metamask 9.8.0, both Prod (cowswap.exchange) and 0.17 (https://pr924--gpswapui.review.gnosisdev.com/#/swap)

Both worked fine. Even using a new `signed typed data` hash signing not available before if I remember correctly.

Will test Chrome next.

**Comment by alfetopito** [comment]
Having issues connecting Ledger to Chromium :disappointed: 
Will see if I have any luck with Brave

**Comment by alfetopito** [comment]
On Brave I could reproduce the Chrome bug reported above.
Brave Version 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit); Metamask 9.7.1
Using MM through Brave's Crypto Wallet version 1.0.32.

Updated to latest MM version (9.8.1) and the issue remains.
Investigating...

Looks like there's an overlay on the signature prompt.
Not all data is displayed
![screenshot_2021-07-21_14-30-14](https://user-images.githubusercontent.com/43217/126562665-f39fe1e8-c01b-43cf-b2c0-9db31bb4bcc9.png)
When I hit sign, I get the signature denied error:
![screenshot_2021-07-21_14-31-38](https://user-images.githubusercontent.com/43217/126562726-c4340fd7-9102-47d5-b5bf-f41dd5cb659e.png).
The error code is 4001
![screenshot_2021-07-21_14-32-02](https://user-images.githubusercontent.com/43217/126562801-407a5e7c-3495-4077-a233-0e16ba5ab1af.png)

The prompt to sign the message on ledger is shown, though, much like when it worked on Firefox.

The same happens on latest v0.17 and latest Prod.

**Comment by anxolin** [comment]
Very weird! This used to work, so I assume there's an issue introduced in a new version of chrome/MM/Ledger

Recently they changed the communication channel, so it uses Ledger live. There was an issue in the past with MM and displaying the boolean. Maybe is related to this and affects somehow? 

Since it's not part of the version, we can solve it independently of the version, but I think it's important. I suggest contacting both to Metamask in Discord, and in Ledger chat, they will probably help.

**Comment by MareenG** [comment]
I tried today to place order in the new version with Ledger. 
Currently, I can't place any order when using Chrome. 
The two confirmation modal in MM mask are shown but no message on my ledger device. 
Further I don't even get an error message Im a just stuck in the confirmation modal. 
When using brave it works fine

**Comment by anxolin** [comment]
@MareenG Maybe we can do a session with you and try to see if we can debug it.
For me it works, although is a pain to setup Ledger.

I would try to follow this troubleshooting.

1. Download Ledger live, make sure is the last version

2. Update your firmware to the latest version
![image](https://user-images.githubusercontent.com/2352112/129267887-24d91e2b-2938-4491-99c4-d5b013dee364.png)

3. Make sure Ledger live is enable in Metamask settings
![image](https://user-images.githubusercontent.com/2352112/129268046-50dfc35d-83e9-4af2-b300-85df765f324d.png)

4. Make sure the `Contract data` is enabled in Ethereum app, inside your ledger

5. Connect USB, add Ledger to your metamask following the instructions in Metamask

6. Trade in `BobineSwap`

**Comment by alfetopito** [comment]
From time to time we get these requests on Discord
I recall at least 3 like this.

It's solved by upgrading Ledger firmware to latest and using Firefox.

Closing
