### ISSUE TITLE
[v.0.17.0] USD estimation <  0.000000000000000... when token's amount too small

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#972]
Related to #924, #1075

I'd say it is an edge case, but when my token's amount is too small in the 'From' field, I see dollar estimation `<  0.000000000000000... `
**Video:** https://drive.google.com/file/d/1o0fRl9ZSq_l4hLNLc_MT36YROs7GKHyu/view

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/df6a0561-625d-4792-86b0-6aa91fb9c175)
![image](https://user-images.githubusercontent.com/70885163/127305061-23dec0ac-f41a-403b-8551-c7fe50be023e.png)

Moreover, in a mobile view, this value exceeds the field's width
![mobile overlaps.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f7f55762-366e-4914-90d1-92d20bdc6060)

I'd propose to show USD estimation as `<0.01` when token amounts are too small.

**Comment by alfetopito** [comment]
Agree, USD estimations should always be limited to 2 decimals

**Comment by anxolin** [comment]
I'll put this one in progress, cause I think is addressed by lendro #1135 wich fixes

Fixes #1120
Fixes #1129
