### ISSUE TITLE
[v.0.17.0] FAQ and CowGame are displayed as links in the menu

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#973]
Related to #924

Open the app menu

**AR:** FAQ and CowGame are displayed as links
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6ad50414-031d-46c8-ad75-070ea301043d)

**ER:** FAQ and CowGame are not displayed as links

**Comment by alfetopito** [comment]
Also, probably the icon to `FAQ` should not be the same as `Code`

**Comment by biocom** [comment]
Addressed in https://github.com/gnosis/cowswap/pull/1118
