### ISSUE TITLE
[v.0.17.0] No 'New to Ethereum' message on the connection modal

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#975]
Related to #924

Open the connection modal

**AR:** No 'New to Ethereum' message on the connection modal
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1491d0fc-8284-41c3-955c-b593770341e7)

**ER:**  message is displayed at the bottom of the modal: 
'New to Ethereum?  Learn more about wallets', where 'Learn more about wallets' link, navigates to https://ethereum.org/en/wallets/

**Comment by W3stside** [comment]
closed by #1003
