### ISSUE TITLE
Need to sign a permission to trade UNI/DAI token each half an hour

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#978]
Slack discussion: https://altoros.slack.com/archives/C025G521XQD/p1626708552006700

When select UNI token to trade, user needs to sign (not Confirm token spend) GP smart contract permissions  to use the token in the connected wallet. 
Sign transaction has a time limitation  (approximately for a half of an hour). Besides, it is reset when disconnect/reconnect a wallet. 

**Video:** https://drive.google.com/file/d/1J3RXu4ea3Wjk0heR6VtVnQwNPpL8BYju/view
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2e3be5e4-b485-4972-8e08-feaa7a2db8b8)

This behavior does not correspond to the logic we use for all rest tokens (approve token spend transaction only once). 

We could:
1. Change it so everything uses the old gas based allowance like before
2. Handle so gas less allowance can be used.
Although for 2 we need to check whether our smart contracts already support this

**Comment by alfetopito** [comment]
I think handling this is high-priority for v0.17, as without it user's won't be able to enable UNI (and maybe other tokens)

**Comment by elena-zh** [comment]
The same issue is for DAI token: user needs to sign spend approval transaction each 20 min

**Comment by elena-zh** [comment]
I agree with @alfetopito that the issue is a high priority one as a user is not able to trade UNI/DAI tokens 
![image](https://user-images.githubusercontent.com/70885163/126304476-3d75d2f2-6423-4220-9b27-8843128c4f09.png)

**Comment by W3stside** [comment]
Will go into `0.17.0-RC.1` or later
