### ISSUE TITLE
[v.0.17.0] Mobile: Content of the 'Import token' modal exceeds its area

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#979]
Related to #924

open 'From' (or To) token list in the Swap form on a Mobile device
search for a token that is not in the list
Press on the Import button

**Actual Result:**  Content (token address) of the 'Import token' modal exceeds its area + content seems to be not center-aligned 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2772509e-15a7-4c3f-9b41-497aac1552c5)

**Expected Result:** content should not exceed a modal's area
Uniswap: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c3add616-a378-41ba-8e49-1245dbb8d2b5)

**Comment by alfetopito** [comment]
@W3stside related to you recent changes (dark mode fix) by any chance?

**Comment by W3stside** [comment]
@alfetopito I TAKE NO RESPONSIBILITY

**Comment by W3stside** [comment]
yeah it was def me probably, i'll fix it one sec

**Comment by W3stside** [comment]
closed by #1004
