### ISSUE TITLE
[v.0.17.0] Token name is not visible in a dark 'Add custom token' modal

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#983]
Related to #924

1. Open the app in the dark mode
2. Open From dropdown, select 'Manage Token Lists' 
3. Press on the 'Tokens' tab and fill in an address of a custom token

**Actual Result:** Token name is not visible
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d4c671d5-d2f0-4f9a-bdf4-ce0015e5da16)

**Expected Result:** Token name is visible

**Comment by W3stside** [comment]
shit @biocom  this is still remaining, i fixed the other message but apparently not this one

**Comment by biocom** [comment]
@W3stside I'll check it out now.

**Comment by W3stside** [comment]
closed by #1005
