### ISSUE TITLE
Feedback is sent when no text/email there

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#985]
Reproducible in Prod/Staging/Dev

1. open Feedback form
2. do not fill in fields
3. press on the 'Next' --> to the 'Send' button

**AR**: the feedback is sent (at lease, I have got a confirmation message)
https://images.zenhubusercontent.com/192335743/f0dbf0ed-507f-40c9-a531-46ddb61bb0a6/untitled__jul_20__2021_2_38_pm.mp4

**ER**: do not allow to send a feedback when feedback is empty?

**Comment by MareenG** [comment]
I think this is intended. 
The user can stay anonymous this way also it is less personal data for us to handle :)

**Comment by elena-zh** [comment]
@MareenG , yes, I agree with being anonymous. But what about an empty feedback? Are we OK with it?=)

**Comment by anxolin** [comment]
well, is not completly empty :) 
they said the like something.

Anyways, i think is okeish. we don't get that many empty ones anyways
