### ISSUE TITLE
[Affilite] Implement page design

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#988]
# Summary

Implement the design that's the outcome of the task #958

# Requirements

- Design implemented on `Profile` page

**Comment by alfetopito** [comment]
Final design from https://www.figma.com/file/bcoZf5RIgVKDItdOaTZq18/GP-Swap?node-id=1759%3A2
![screenshot_2021-08-05_10-03-42.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/0cb4bbc6-0d4e-4c05-8c1a-233a54b7b422)

**Comment by alfetopito** [comment]
Dark mode version also available on #958

**Comment by fapesteguia** [comment]
What is remaining for this issue @maria-vslvn

**Comment by alfetopito** [comment]
We discussed this in the last sync.
With the change of data source, available fields are shuffling once again.
That will require another small design change.
