### ISSUE TITLE
Percentages are not rounded to 2 decimals 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#999]
percentages are not rounded to 2 decimals
![image](https://user-images.githubusercontent.com/70885163/126781754-846e9fe0-290e-4b19-bb65-52a3ac377e2a.png)
![image](https://user-images.githubusercontent.com/70885163/126781771-85114900-92cd-476f-a19b-2595608af237.png)

**Comment by W3stside** [comment]
mm well isn't that less clear? i think we preferred the precision. wdyt?

**Comment by elena-zh** [comment]
Frankly, I become a bit lost when I see a lot of decimals. 
I think, that it would be good to have up to 2 decimals, but it is my subjective opinion. 
If the case is not a bug, we can close it and leave changes as it is. 
Thanks!

**Comment by alfetopito** [comment]
Given that it's possible (and likely) to buy just a fraction of a token, limiting to only 2 decimals would result in displaying on something like "< 0.01" in several occasions, which is not a good thing.
The only places where I agree 2 decimal places are enough are:
1. Percentages
2. USD estimations

**Comment by elena-zh** [comment]
So, let leave the issue opened as percentages are not rounded to 2 decimals
![image](https://user-images.githubusercontent.com/70885163/126781754-846e9fe0-290e-4b19-bb65-52a3ac377e2a.png)
![image](https://user-images.githubusercontent.com/70885163/126781771-85114900-92cd-476f-a19b-2595608af237.png)

**Comment by elena-zh** [comment]
I have updated the issue description

**Comment by elena-zh** [comment]
Fixed in v.017

**Comment by elena-zh** [comment]
Re-opened: still reproducible
